.TITLE       GKS
.FACILITY    GKS,240/PREFIX=GKS__


.SEVERITY	INFORMATIONAL

.BASE		100
TOOZD	<No more available graphics descriptors>
ILLZD	<Unused error code>
TOMNY	<Unused error code>
ILLAC	<Illegal access mode>
UNKPA	<Parameter not associated with workstation>
NTACT	<Unused error code>
ISACT	<Parameter currently active>
EXCPA	<Unused error code>
ERACT	<Unused error code>
ERECH	<Unused error code>
ALOPN	<Unused error code>
UNRES	<Unused error code>
LCERR	<Unused error code>
CRERR	<Unused error code>
CNERR	<Unused error code>
WRERR	<Unused error code>
RDERR	<Unused error code>
ERROR	<An error has been reported from GKS itself>
DVERR	<Workstation name not defined by GNS>
.END
