.TITLE       DAT
.FACILITY    DAT,200/PREFIX=DAT__


.SEVERITY	INFORMATIONAL

.BASE		100
LOCIN	<Locator invalid>
LOCER   <Locator target erased>
TYPIN	<Type invalid>
NAMIN	<Name invalid>
MODIN	<Mode invalid>
CONIN	<Conversion invalid>
DELIN	<Deletion invalid>
DIMIN	<Dimensions invalid>
FILIN	<File invalid>
OBJIN	<Object invalid>
GRPIN	<Group invalid>
SUBIN	<Subscripts invalid>
COMEX	<Component already exists>
OBJNF	<Object not found>
TRUNC	<Text truncated>
ACCON	<Access conflict>
CONER	<Conversion error>
UNSET	<Primitive data undefined>
VERMM	<Version mismatch>
PRMAP	<Primitive data mapped>
RELIN	<Relationship invalid>
FILCK	<File locking error>
FILNF	<File not found>
FILPR	<File protected>
INCHK	<Integrity check>
FATAL	<Fatal internal error>
WEIRD	<Unknown error>
EXCPA	<Too many data parameters>
UNKPA	<Unknown data parameter>
ISOPN	<Parameter is currently active>
ERACT	<Error activating DAT>
EREXH	<Error establishing DAT exit handler>
NOMAP	<Not mapped>
ISMAP	<Data currently mapped>
STKOF	<Recursion stack overflow>
BOUND	<Outside bounds of object>
ACTIV	<HDS is already active>
FILCL	<File close error>
FILCR	<File create error>
FILMP	<File mapping error>
FILND	<File not deleted>
FILNX	<File not extended>
FILRD	<File read error>
FILWR	<File write error>
NOMEM	<Memory allocation error>
WLDIN	<Wild-card search context invalid>
NOCMP   <No component name>
DTRNC   <Dimensions truncate in Fortran INTEGER*4>
HDF5E   <Internal error from HDF5>
FILFM   <File not in the expected format>
THREAD  <Object not locked by current thread>
MUTEX   <Failed to initialise mutex>
.END
