#!/usr/local/bin/tcsh
#
# RE_LIGHT <EVEF> <RA> <DEC> <SNAME> <RADIUS> <OFFSET> <BRADIUS> <BINW>
#
#
# Author : P. McGale (pam@star.le.ac.uk)
# 1st Ver: 9th May 95


echo " "
echo "   RE_LIGHT -- Version 090595"
echo " "
echo "Please note that this version does not work with "
echo "background derived from an annulus!   Background is got"
echo "from a circle offset along s/c scan path.  Recommended "
echo "radii are 3am for source and 9am for background. "
echo "A typical offset value maybe 20am. "
echo "Moon times rejected. High background times NOT rejected."
echo " "


unsetenv PARLOG


# Check got all the input parameters.
if ($1 == "") then
  echo " "
  echo -n "   Give event file (eg mrgd_ev.fit): "
  set evf = $<
else
  set evf = $1
endif

if ($2 == "") then
  echo " "
  echo -n "   Give source RA (deg\hms): "
  set s_ra = $<
else
  set s_ra = $2
endif

if ($3 == "") then
  echo " "
  echo -n "   Give source Dec (deg\hms): "
  set s_dec = $<
else
  set s_dec = $3
endif

if ($4 == "") then
  echo " "
  echo -n "   Give source name : "
  set s_nme = $<
else
  set s_nme = $4
endif

if ($5 == "") then
  echo " "
  echo -n "   Give source box radius (arcmin): "
  set s_bx = $<
else
  set s_bx = $5
endif

if ($6 == "") then
  echo " "
  echo -n "   Give bgnd offset (arcmin): "
  set b_off = $<
else
  set b_off = $6
endif

if ($7 == "") then
  echo " "
  echo -n "   Give bgnd box radius (arcmin): "
  set b_bx = $<
else
  set b_bx = $7
endif

if ($8 == "") then
  echo " "
  echo -n "   Give time bin width in secs (eg 5760): "
  set binw = $<
else
  set binw = $8
endif

#
# Generate coords of background, and get ratio of areas.
"$re_progs"re_eoffset s_ra=$s_ra s_dec=$s_dec offset=$b_off  >! ~/ra_dec.offset
set rec=`sed -n "/./p" ~/ra_dec.offset`
set o_ra=`echo "$rec" | awk '{print $1}'`
set o_dec=`echo "$rec" | awk '{print $2}'`
rm -f ~/ra_dec.offset

set a_ratio=`echo "$s_bx $b_bx" | awk '{print ($2/$1)**2}'`

#
# Set up some convenient names
setenv srce    "$s_nme"_1
setenv srce_c  "$srce"_c
setenv bkgd    "$srce"_b
setenv bkgd_c  "$srce"_bc
setenv bkgd_cd "$srce"_bcd
setenv srce_s  "$srce"_s
setenv srce_x  "$srce"_x
setenv bkgd_x  "$srce"_bx

echo " "
echo "The following will be created in the default directory"
echo " "
echo "$srce     - Raw source time series in S1a"
echo "$srce_c   - Exp corrected source"
echo "$bkgd   - Raw background time series"
echo "$bkgd_c  - Exp corrected Background"
echo "$bkgd_cd - Exp corrected Background, area corrected"
echo "$srce_s   - Background subtracted source flux"
echo "$srce_x   - Exposure profile at the source"
echo "$bkgd_x  - Exposure profile at background"
echo " "
echo "Files as above but for the S2a filter"


echo " "
echo "   Sorting On source for S1A"
echo " "

"$re_progs"re_sort evefil=$evf show=n dtype=t ra=$s_ra dec=$s_dec inrad=0 outrad=$s_bx brej=n mrej=y filter="s1a" nbins=0 tbin=$binw irad=2.5 output=$srce \\

# Save start and end times to use below.
set rec=`sed -n "/./p" ~/strt_end.lcurve`
set strt_t=`echo "$rec" | awk '{print $1}'`
set end_t=`echo "$rec" | awk '{print $2}'`


#
# Exposure correct the time-series of the source
#

"$re_progs"re_timexp inp=$srce src=y out=$srce_c \\

#
# Set defaults for re_sort of time-series of the background
#
#
echo " "
echo "   Sorting Background for S1A"
echo " "

"$re_progs"re_sort evefil=$evf show=n dtype=t ra=$o_ra dec=$o_dec inrad=0 outrad=$b_bx brej=n mrej=y filter="s1a" tlo=$strt_t thi=$end_t nbins=0 tbin=$binw irad=2.5 output=$bkgd \\


#
# Exposure correct the time-series of the background
#

"$re_progs"re_timexp inp=$bkgd src=n out=$bkgd_c \\

#
# Subtract the background from source+background (normalised by area).
#
echo " "
echo "   Subtracting Background from source "
echo " "

arithmetic inp1=$bkgd_c inp2=$a_ratio out=$bkgd_cd oper=/ \\
arithmetic inp1=$srce_c inp2=$bkgd_cd  out=$srce_s  oper=- \\ 

echo " "
echo "   Produce exposure Profile for S1a"
echo " "

"$re_progs"re_exprof inpu=$srce inpc=$srce_c outf=$srce_x  \\
"$re_progs"re_exprof inpu=$bkgd inpc=$bkgd_c outf=$bkgd_x  \\


echo " "
echo "   Sorting On source for S2A"
echo " "

# Set up some convenient names
setenv srce    "$s_nme"_2
setenv srce_c  "$srce"_c
setenv bkgd    "$srce"_b
setenv bkgd_c  "$srce"_bc
setenv bkgd_cd "$srce"_bcd
setenv srce_s  "$srce"_s
setenv srce_x  "$srce"_x
setenv bkgd_x  "$srce"_bx


# Uses same start and end times as for S1a
"$re_progs"re_sort evefil=$evf show=n dtype=t ra=$s_ra dec=$s_dec inrad=0 outrad=$s_bx brej=n mrej=y filter="s2a" tlo=$strt_t thi=$end_t nbins=0 tbin=$binw irad=2.5 output=$srce \\

#
# Exposure correct the time-series of the source
#

"$re_progs"re_timexp inp=$srce src=y out=$srce_c \\

#
# Set defaults for re_sort of time-series of the background
#
#
echo " "
echo "   Sorting Background for S2A"
echo " "

"$re_progs"re_sort evefil=$evf show=n dtype=t ra=$o_ra dec=$o_dec inrad=0 outrad=$b_bx brej=n mrej=y filter="s2a" tlo=$strt_t thi=$end_t nbins=0 tbin=$binw irad=2.5 output=$bkgd \\


#
# Exposure correct the time-series of the background
#

"$re_progs"re_timexp inp=$bkgd src=n out=$bkgd_c \\

#
# Subtract the background from source+background (normalised by area).
#
echo " "
echo "   Subtracting Background from source "
echo " "

arithmetic inp1=$bkgd_c inp2=$a_ratio out=$bkgd_cd oper=/ \\
arithmetic inp1=$srce_c inp2=$bkgd_cd  out=$srce_s  oper=- \\ 

echo " "
echo "   Produce exposure Profile for S2a"
echo " "

"$re_progs"re_exprof inpu=$srce inpc=$srce_c outf=$srce_x  \\
"$re_progs"re_exprof inpu=$bkgd inpc=$bkgd_c outf=$bkgd_x  \\


# Tidy up and Leave script
exit:
rm -f  ~/strt_end.lcurve

