	SUBROUTINE DEVFCSSUB( DIMS1, DIMS2, ARRIN, XCEN, YCEN, XPOS,
     :	                      YPOS, ACTTHETA, CALTHETA, DEVTHETA, STATUS)

*  HISTORY
*     11-Aug-1994  Changed DIMS input so that routine will compile (SKL@JACH)
*

	IMPLICIT NONE

	INCLUDE 'SAE_PAR'

	INTEGER DIMS1, DIMS2, XCEN, YCEN, XPOS, YPOS, STATUS

	REAL ARRIN( DIMS1, DIMS2), ACTTHETA, CALTHETA, DEVTHETA, PI,
     :	     XEXT, YEXT

	PI = 3.141592654

	XEXT = REAL( XPOS - XCEN)
	YEXT = REAL( YPOS - YCEN)

	ACTTHETA = ARRIN( XPOS, YPOS)

	IF( ABS( XEXT) .GT. 1.0E-20) THEN

	  CALTHETA = ATAN( ABS( YEXT)/ABS( XEXT))*360.0/( 2*PI)

	ELSE

	  CALTHETA = 90.0

	END IF

	IF( XEXT .LT. 0.0 .AND. YEXT .GT. 0.0) THEN

	  CALTHETA = 180.0 - ABS( CALTHETA)

	ELSE IF( XEXT .GT. 0.0 .AND. YEXT .LT. 0.0) THEN

	  CALTHETA = 180.0 - ABS( CALTHETA)

	END IF

	IF( CALTHETA .GE. 0.0) THEN

	  DEVTHETA = CALTHETA - ACTTHETA

	ELSE

	  DEVTHETA = -999

	END IF

	END
