	SUBROUTINE HIST_MAXMIN( NX, NY, ARRAY, X_START, Y_START, X_END, Y_END,
     :	                        CALC_MAX, CALC_MIN)

	IMPLICIT NONE

	INTEGER NX, NY, X_START, X_END, Y_START, Y_END, J, K

	REAL ARRAY( NX, NY), CALC_MAX, CALC_MIN

	CALC_MAX = -1.0E20
	CALC_MIN = 1.0E20

	DO J = Y_START, Y_END

	  DO K = X_START, X_END

	    CALC_MAX = MAX( ARRAY( K, J), CALC_MAX)
	    CALC_MIN = MIN( ARRAY( K, J), CALC_MIN)

	  END DO

	END DO

	END
