	SUBROUTINE PHASESHIFTSUB( DIMSX, DIMSY, ARRIN, XPIX, YPIX,
     :	                          ARCSECPMM, FOCLEN, PLATSCAL)

	IMPLICIT NONE

	INTEGER DIMSX, DIMSY, XPIX, YPIX, J, K

	REAL ARRIN( DIMSX, DIMSY)
	REAL C, PIX, PIXMM, DV, ARCSECPMM, FOCLEN, PLATSCAL, ALPHA

	PARAMETER( C = 3.0E5)

	DO J = 1, DIMSY

	  DO K = 1, DIMSX

	    PIX = SQRT( REAL( ( K-XPIX))**2 + REAL( ( J-YPIX))**2)
	    PIXMM = PIX*PLATSCAL/ARCSECPMM
	    ALPHA = ATAN( PIXMM/FOCLEN)
	    DV = C*( 1-COS( ALPHA))

!	    IF( K .EQ. XPIX) THEN
!	      TYPE *, PIX, PIXMM, ALPHA, DV
!	    END IF

	    ARRIN( K, J) = DV

	  END DO

	END DO

	END
