	SUBROUTINE SPEC3DSUB( DIMSX, DIMSY, ARRIN, LUNO, NUMB, XPIX, YPIX)

	IMPLICIT NONE

	INTEGER DIMSX, DIMSY, LUNO, XPIX, YPIX

	REAL ARRIN( DIMSX, DIMSY), PIXVAL, NUMB

	IF( ( XPIX .GE. 1 .AND. XPIX .LE. DIMSX) .AND.
     :	    ( YPIX .GE. 1 .AND. YPIX .LE. DIMSY)) THEN
	   PIXVAL = ARRIN( XPIX, YPIX)
	ELSE
	   PIXVAL = -999
	END IF

	WRITE( LUNO, *) NUMB, PIXVAL

	END
