      TYPE *,'           --------------------------------------------'
      TYPE *,'             Specx v6.7-7 (Unix) ---- 15 May 2000'
      TYPE *,'                  Copyright (C)  R.Padman & PPARC'
      TYPE *,'            Acknowledgements to Horst Meyerdierks (PPARC)'
      TYPE *,'                 Remo Tilanus & Tim Jenness (JACH)'
      TYPE *,'           --------------------------------------------'
      TYPE *

