      TYPE *,'           --------------------------------------------'
      TYPE *,'             Specx v6.7-5 (Unix) ---- 15 April 1999'
      TYPE *,'                  Copyright (C)  R.Padman & PPARC'
      TYPE *,'            Acknowledgements to Horst Meyerdierks (PPARC)'
      TYPE *,'                 Remo Tilanus & Tim Jenness (JACH)'
      TYPE *,'           --------------------------------------------'
      TYPE *

