      PRINT *,'           --------------------------------------------'
      PRINT *,'             Specx v6.8-4 (Unix) ---- 16 April 2004'
      PRINT *,'                  Copyright (C)  R.Padman & PPARC'
      PRINT *,
     +  '            Acknowledgements to Horst Meyerdierks (PPARC)'
      PRINT *,'                 Remo Tilanus & Tim Jenness (JACH)'
      PRINT *,'                    Alan Chipperfield (Starlink)'
      PRINT *,'           --------------------------------------------'
      PRINT *

