      SUBROUTINE JTY_PREPARE(N,DATA,FT,NAP1,NAP2,PERCENT,
     :   K1,K2,K3,K4,RMS)
      REAL*4 DATA(1), JTY_RMSFILTER
      COMPLEX FT(1)
      LOG2N = NINT(ALOG(FLOAT(N))/ALOG(2.))
      CALL JTY_RRVECTOR(N,DATA,FT)
      CALL JTY_APODIZE(N,NAP1,NAP2,FT,PERCENT)
      CALL JTY_RCVECTOR(N,FT,FT)
      CALL JTY_FFT2C(FT,LOG2N,+1)
      RMS = JTY_RMSFILTER(N,K1,K2,K3,K4,FT)
      RETURN
      END
