*+EXPOS_S_SET Set the CORRECTED flags in a data set
	SUBROUTINE EXPOS_S_SET (LOC, STATUS)
	include 'DAT_PAR'
* Input
	CHARACTER*(DAT__SZLOC)	LOC		! dataset top locator
* Output
	INTEGER		STATUS		! HDS status
* M Denby Jan-90
* P McGale May 95 - UNIX mods
*-
* Local
	CHARACTER*(DAT__SZLOC)	MOR, AST, PRO
	CHARACTER*(DAT__SZLOC)	COR

* Get down to the corrected structure
	CALL DAT_FIND (LOC, 'MORE', 	  MOR, STATUS)
	CALL DAT_FIND (MOR, 'ASTERIX',    AST, STATUS)
	CALL DAT_FIND (AST, 'PROCESSING', PRO, STATUS)
	CALL DAT_FIND (PRO, 'CORRECTED',  COR, STATUS)

* switch deadtime and vignetting flags
	CALL CMP_PUT0L (COR, 'DEAD_TIME',  .TRUE., STATUS)
	CALL CMP_PUT0L (COR, 'VIGNETTING', .TRUE., STATUS)

* Clean up
	CALL DAT_ANNUL (MOR, STATUS)
	CALL DAT_ANNUL (AST, STATUS)
	CALL DAT_ANNUL (PRO, STATUS)
	CALL DAT_ANNUL (COR, STATUS)

	IF (STATUS.NE.0) THEN
	  WRITE(*,*) '   Error in EXPOS_S_SET'
	ENDIF

	END
