*+GRIDINT
	SUBROUTINE GRIDINT (ELOD,ELAD,ARR,NX,NY,EXP)
	IMPLICIT	NONE
* Input
	INTEGER		NX,NY
	REAL		ELOD, ELAD
	REAL		ARR(NX,NY)
* Output
	REAL		EXP

* Local
	REAL		XFRAC, YFRAC
	REAL		GRIDB, GRIDT
	INTEGER		IXL, IXH, IYL, IYH


	IXL = INT(ELOD)
	IXH = IXL + 1
	IYL = INT(ELAD+90.)+1
	IYH = IYL + 1

	IF (IXL.EQ.0) THEN
	  IXL = 360
	  IXH = 1
	  XFRAC = (ELOD - 0*1.)
	ELSE
	  XFRAC = (ELOD - IXL*1.)/1.
	ENDIF
	YFRAC = (ELAD + 90. - (IYL-1)*1.)/1.

	GRIDB = ARR(IXL,IYL) + (ARR(IXH,IYL) - ARR(IXL,IYL))*XFRAC
	GRIDT = ARR(IXL,IYH) + (ARR(IXH,IYH) - ARR(IXL,IYH))*XFRAC

	EXP = GRIDB + (GRIDT - GRIDB)*YFRAC

	END

