*+HK2MJD Convert to HK UT 1/2 seconds to MJD
	DOUBLE PRECISION FUNCTION HK2MJD (HKT)
	IMPLICIT	NONE
	INCLUDE 	'SMAPDEF.INC'
* Input
	INTEGER		HKT
* M. Denby Nov 89
* P McGale May 95 UNIX mods
*-
* Local
	DOUBLE PRECISION SECS2
	PARAMETER      (SECS2 = 86400.D0*2.D0)
*
	HK2MJD = S2_REF_MJD + DBLE(HKT)/SECS2

	END
