*+NUDGE Move a point inside the WFC fov
	SUBROUTINE NUDGE(DELRAD,AZ,EL)
	IMPLICIT 	NONE
	REAL		DELRAD, AZ, EL
	REAL		DAZ, DEL, THETA

	THETA=ATAN(EL/AZ)
	DAZ=ABS(COS(THETA)*DELRAD)
	DEL=ABS(SIN(THETA)*DELRAD)
	AZ=SIGN(1.,AZ)*(ABS(AZ)-DAZ)
	EL=SIGN(1.,EL)*(ABS(EL)-DEL)

	END
