.TITLE       PAR
.FACILITY    PAR,190/PREFIX=PAR__


.SEVERITY	INFORMATIONAL

.BASE		100
NOUSR	<No user available for input>
PARNF	<Parameter does not exist>
EOL	<End of parameter list>
NULL	<Null parameter value>
ABORT	<Parameter request aborted>
INVST	<Parameter in invalid state>
MDINV	<Invalid access mode specified>
ACINV	<Invalid access mode for parameter>
ICACM	<Inconsistent access mode>
ERROR	<Error>
FATAL	<Fatal internal error>
AMBIG	<Ambiguous option list>
.END
