      SUBROUTINE CAT0_GETXT (BCKTYP, CI, FINISH, CLASS, TEXT, STATUS)
      IMPLICIT NONE
      INTEGER BCKTYP, CI, STATUS
      LOGICAL FINISH
      CHARACTER CLASS*(*), TEXT*(*)
      INCLUDE 'CAT_PAR' 
      INCLUDE 'CAT1_PAR' 

      IF (STATUS .NE. CAT__OK) RETURN

      IF (BCKTYP .EQ. CAT1__BKFIT) THEN
         CALL CAT3_GETXT (CI, FINISH, CLASS, TEXT, STATUS)
      ELSE IF (BCKTYP .EQ. CAT1__BKSTL) THEN
         CALL CAT5_GETXT (CI, FINISH, CLASS, TEXT, STATUS)
      ELSE IF (BCKTYP .EQ. CAT1__BKTST) THEN
         CALL CAT6_GETXT (CI, FINISH, CLASS, TEXT, STATUS)
      END IF

      END
