      SUBROUTINE CAT0_PUTXT (BCKTYP, CI, CLASS, TEXT, STATUS)
      IMPLICIT NONE
      INTEGER BCKTYP, CI, STATUS
      CHARACTER CLASS*(*), TEXT*(*)
      INCLUDE 'CAT_PAR' 
      INCLUDE 'CAT1_PAR' 

      IF (STATUS .NE. CAT__OK) RETURN

      IF (BCKTYP .EQ. CAT1__BKFIT) THEN
         CALL CAT3_PUTXT (CI, CLASS, TEXT, STATUS)
      ELSE IF (BCKTYP .EQ. CAT1__BKSTL) THEN
         CALL CAT5_PUTXT (CI, CLASS, TEXT, STATUS)
      ELSE IF (BCKTYP .EQ. CAT1__BKTST) THEN
         CALL CAT6_PUTXT (CI, CLASS, TEXT, STATUS)
      END IF

      END
