      SUBROUTINE CAT0_CNEW (BCKTYP, CATNAM, CATFIL, EXTRA, CI, STATUS)
      IMPLICIT NONE
      INTEGER BCKTYP, CI, STATUS
      CHARACTER*(*) CATNAM, CATFIL, EXTRA
      INCLUDE 'CAT_PAR' 
      INCLUDE 'CAT1_PAR' 

      IF (STATUS .NE. CAT__OK) RETURN

      IF (BCKTYP .EQ. CAT1__BKFIT) THEN
         CALL CAT3_CNEW (CATNAM, CATFIL, EXTRA, CI, STATUS)
      ELSE IF (BCKTYP .EQ. CAT1__BKSTL) THEN
         CALL CAT5_CNEW (CATNAM, CATFIL, EXTRA, CI, STATUS)
      ELSE IF (BCKTYP .EQ. CAT1__BKTST) THEN
         CALL CAT6_CNEW (CATNAM, CATFIL, EXTRA, CI, STATUS)
      END IF

      END
