.TITLE       CAT   Catalogues access library
.FACILITY    CAT,1518/PREFIX=CAT__


.SEVERITY	ERROR
ERROR	<General CAT error>
INVOP	<Invalid STATE and MODE combination opening cat>
ILLOP	<Invalid parameters when opening catalogue>
INVBK	<Invalid back-end type>
MAXOP	<Maximum permitted number of open cats exceeded>
MAXID	<Maximum permitted number of identifiers exceeded>
MAXAT	<Maximum permitted number of attributes exceeded>
EOF	<End-of-file encountered>
TYPCV	<Type conversion error>
IMATT	<Attempt to modify an immutable attribute>
NOATT	<Attribute not found>
INVCN	<Invalid catalogue name>
NOLUN	<Failed to get a free Fortran logical unit number>
NOCMP	<Component not found>
INVDT	<Invalid data type>
INVRW	<Invalid row number>
INVGN	<Invalid genus for a column>
INVGT	<Invalid get (not column, parameter or expr)>
INVEX	<Invalid expression (unable to parse it)>
INVWT	<Attempt to write to a read-only catalogue>
INVPT	<Invalid put (not column, parameter or expr)>
IDNFD	<Identifier not found>
INVNL	<Invalid code to specify type of null for column>
INVEC	<Invalid specification of vector element>
INVCL	<Invalid column specification>
INVPR	<Invalid parameter specification>
INVID	<Invalid identifier>
INVSR	<Invalid operation on unsorted column>
INVAC	<Invalid access mode>
INVDS	<Invalid description file>
NOCAT	<Unable to open catalogue>
IOERR	<Catalogue I/O error>
INVCD	<Invalid catalogue description>
INVAS	<Invalid AST frame-set>
INVAP	<Invalid AST frame-set specification>
DUPNM	<Duplicate column, parameter or expression name>
CSIZE	<Character column size too large>
.END
