.TITLE       PRM
.FACILITY    PRM,1500/PREFIX=PRM__


.BASE		100
ARGIN	<argument/operand invalid>
FLTDZ	<floating point divide by zero>
FLTOF	<floating point overflow>
FLTUF	<floating point underflow>
INTDZ	<integer divide by zero>
INTOF	<integer overflow>
LOGZN	<logarithm of zero or negative number>
SLOST	<numerical significance lost>
SQRNG	<square root of negative number>
UDEXP	<undefined exponentiation>
FPERR	<floating point error>
.END
