.TITLE       NDF
.FACILITY    NDF,1506/PREFIX=NDF__


.SEVERITY	ERROR

.BASE		300
ACCIN	<access type invalid>
ACDEN	<access denied>
BADNS	<bad pixel values not supported>
BMOIN	<bounds matching option invalid>
CNMIN	<component name invalid>
DIMIN	<dimensions invalid>
DUDEF	<data component undefined>
EXSLT	<exceeded number of allocated slots>
FATIN	<fatal internal error>
FTPIN	<full data type invalid>
ICHIN	<chunk index invalid>
IDINV	<NDF identifier invalid>
ISMAP	<component is mapped>
MMDIN	<mapping mode invalid>
MODIN	<access mode invalid>
MSBEG	<missing call to NDF_BEGIN>
MXPIN	<maximum number of pixels invalid>
NDMIN	<number of dimensions invalid>
NGSTD	<negative standard deviation value(s) encountered>
NGVAR	<negative variance values(s) encountered>
NOCMP	<no component name>
NODAT	<data array not present>
NOEXT	<extension not present>
NOTRM	<bounds do not intersect>
NOQLY	<quality array not present>
NOTSP	<facility not yet supported>
NOTYP	<no data types>
NSHNM	<non-standard HDS component name>
NSXNM	<non-standard extension name>
NTMAP	<component not mapped>
PLINV	<NDF placeholder invalid>
QMPIN	<quality mapping invalid>
QUDEF	<quality component undefined>
SFTIN	<pixel-shift specification invalid>
TRUNC	<character string truncated>
TYPIN	<type invalid>
TYPNI	<processing of data type not implemented>
VARIN	<variant value invalid>
VUDEF	<variance component undefined>
XISTS	<extension already exists>
XNOIN	<extension number invalid>
XSDIM	<too many dimensions>
XSEXT	<too many extension names>
AXNIN	<axis number invalid>
AXOVF	<axis value overflow>
BNDIN	<bounds invalid>
INUSE	<structure already in use>
NOAXD	<no axis data present>
XTNIN	<extension invalid>
AXVIN	<axis values invalid>
IBLIN	<block index invalid>
NAMIN	<name invalid>
TPNIN	<tuning parameter name invalid>
TPVIN	<tuning parameter value invalid>
CVTER	<foreign format conversion error>
DELER	<foreign file deletion error>
DTMIN	<date/time specification invalid>
EXCER	<error executing external command>
FILIN	<file name invalid>
FILNF	<file not found>
FILPR	<file protected>
FMTIN	<foreign data format invalid>
HEXIN	<history extend size invalid>
HISTL	<history text lines too long>
HITIN	<history information item name invalid>
HRCIN	<history current record count invalid>
HRNIN	<history record number invalid>
HRORD	<history record date/time order invalid>
HUMIN	<history update mode component invalid>
INQER	<file enquiry error>
NOCVT	<no foreign format conversion command defined>
NOFIO	<no free Fortran I/O units>
NOHCD	<missing history creation date component>
NOHCM	<missing command component in history record>
NOHDT	<missing date component in history record>
NOHIS	<history component not present>
NOHRA	<missing history records array component>
NOHRC	<missing history current record component>
NOHTX	<missing text component in history record>
NOMEM	<unable to allocate memory>
STAIN	<state string invalid>
XSFMT	<too many foreign data formats>
NAXIN	<number of axes invalid>
NOWDT	<missing world coordinate system data component>
WCDTS	<world coordinate system data too short>
WCSIN	<world coordinate system information invalid>
ARCIN	<command line argument count invalid>
ARGIN	<command line argument invalid>
BDTIM   <date/time string invalid>
BADSF   <wrong array storage form>
ZERSC   <zero scale factor supplied>
BADCP   <incompatible data types for compression>
CMPAC   <attempt to change a read-only property of a compressed array>
BGSEC   <attempt to create a section containing too many pixels>
NOPAR   <attempt to cancel a parameter that is not associuated with an NDF>
WRAST   <error writing a line of WCS information to an NDF>
INERR   <error initialising thread data in the NDF library>
XSNDF   <Too many NDFs in use at once>
TOOBIG  <Array dimensions exceed limits of the 32 bit API>
THREAD  <The supplied NDF is not locked by the current thread>

.END
