#include "sae_par.h"
#include "dat_par.h"
#include "ndf1.h"
#include "ndf.h"
#include "mers.h"

void ndfCopy_( int indf1, int *place, int *indf2, int *status ){
/*
*+
*  Name:
*     ndfCopy

*  Purpose:
*     Copy an NDF to a new location.

*  Synopsis:
*     void ndfCopy( int indf1, int *place, int *indf2, int *status )

*  Description:
*     This function copies an NDF to a new location and returns an
*     identifier for the resulting new base NDF.

*  Parameters:
*     indf1
*        Identifier for the NDF (or NDF section) to be copied.
*     *place
*        An NDF placeholder (e.g. generated by the ndfPlace function) which
*        indicates the position in the data system where the new NDF will
*        reside. The placeholder is annulled by this function, and a value
*        of NDF__NOPL will be returned (as defined in the include file
*        "ndf.h").
*     *indf2
*        Returned holding the identifier for the new NDF.
*     *status
*        The global status.

*  Notes:
*     -  If this function is called with "status" set, then a value of
*     NDF__NOID will be returned for the "indf2" parameter, although no
*     further processing will occur. The same value will also be returned
*     if the function should fail for any reason.  In either event the
*     placeholder will still be annulled.  The NDF__NOID constant is
*     defined in the header file "ndf.h".

*  Copyright:
*     Copyright (C) 2018 East Asian Observatory
*     All rights reserved.

*  Licence:
*     This program is free software; you can redistribute it and/or modify
*     it under the terms of the GNU General Public License as published by
*     the Free Software Foundation; either version 2 of the License, or (at
*     your option) any later version.
*
*     This program is distributed in the hope that it will be useful,but
*     WITHOUT ANY WARRANTY; without even the implied warranty of
*     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
*     General Public License for more details.
*
*     You should have received a copy of the GNU General Public License
*     along with this program; if not, write to the Free Software
*     Foundation, Inc., 51 Franklin Street,Fifth Floor, Boston, MA
*     02110-1301, USA

*  Authors:
*     RFWS: R.F. Warren-Smith (STARLINK)
*     DSB: David S. Berry (EAO)

*  History:
*     3-APR-2019 (DSB):
*        Original version, based on equivalent Fortran function by RFWS.

*-
*/

/* Local Variables: */
   NdfACB *acb1;         /* Pointer to input NDF entry in ACB */
   NdfACB *acb2;         /* Pointer to output NDF entry in ACB */
   NdfPCB *pcb;          /* Pointer to placeholder entry in the PCB */
   char extn[ DAT__SZNAM + 1 ];    /* Dummy extension list */
   int cpf[ NDF__MXCPF ];/* Component propagation flags */
   int erase;            /* Whether to erase placeholder object */
   int i;                /* Loop count */
   int tstat;            /* Temporary status variable */

/* Ensure the NDF library has been initialised. */
   NDF_INIT( status );

/* Set an initial value for the "indf2" parameter. */
   *indf2 = NDF__NOID;

/* Initialise the component propagation flags. */
   for( i = 0; i < NDF__MXCPF; i++ ) cpf[ i ] = 1;

/* Save the "status" value and mark the error stack. */
   tstat = *status;
   errMark();

/* Import the NDF placeholder, converting it to a PCB index. */
   *status = SAI__OK;
   pcb = NULL;
   ndf1Imppl( *place, &pcb, status );

/* If there has been no error at all so far, then import the input
   NDF identifier. */
   if( ( *status == SAI__OK ) && ( tstat == SAI__OK ) ) {
      ndf1Impid( indf1, &acb1, status );

/* Make a copy of the NDF in place of the placeholder object by
   propagating all its components to the new data structure. */
      ndf1Prp( acb1, 0, &extn, cpf, pcb, &acb2, status );

/* Export an identifier for the new NDF. */
      *indf2 = ndf1Expid( ( NdfObject * ) acb2, status );

/* If an error occurred, then annul any new ACB entry that may have
   been acquired. */
      if( *status != SAI__OK ) ndf1Anl( &acb2, status );
   }

/* Annul the placeholder, erasing the associated object if any error has
   occurred. */
   if( pcb ) {
      erase = ( ( *status != SAI__OK ) || ( tstat != SAI__OK ) );
      ndf1Annpl( erase, &pcb, status );
   }

/* Reset the "place" parameter. */
   *place = NDF__NOPL;

/* Annul any error if "status" was previously bad, otherwise let the new
   error report stand. */
   if( *status != SAI__OK ) {
      if( tstat != SAI__OK ) {
         errAnnul( status );
         *status = tstat;

/* If appropriate, reset the "indf2" parameter, report the error context
   and call the error tracing function. */
      } else {
         *indf2 = NDF__NOID;
         errRep( " ", "ndfCopy: Error copying an NDF to a new location.",
                 status );
         ndf1Trace( "ndfCopy", status );
      }
   } else {
      *status = tstat;
   }

/* Release error stack. */
   errRlse();

/* Restablish the original AST status pointer */
   NDF_FINAL

}

