#include "sae_par.h"
#include "dat_par.h"
#include "ndf1.h"
#include "ndf.h"
#include "mers.h"

void ndfScopy_( int indf1, const char *clist, int *place, int *indf2,
               int *status ){
/*
*+
*  Name:
*     ndfScopy

*  Purpose:
*     Selectively copy NDF components to a new location.

*  Synopsis:
*     void ndfScopy( int indf1, const char *clist, int *place, int *indf2,
*                    int *status )

*  Description:
*     This function propagates (copies) selected components of an NDF to a
*     new location and returns an identifier for the resulting new base
*     NDF.

*  Parameters:
*     indf1
*        Identifier for the NDF (or NDF section) to be copied.
*     clist
*        Pointer to a null terminated string holding A comma-separated list
*        of the NDF components which are to be propagated to the new data
*        structure. By default, the HISTORY, LABEL and TITLE components are
*        propagated. All extensions are also propagated by default except
*        for any that have had a zero value assigned to the corresponding
*        "PXT..." tuning parameter using ndfTune. See the "Component
*        Propagation" section for further details.
*     *place
*        An NDF placeholder (e.g. generated by the ndfPlace function) which
*        indicates the position in the data system where the new NDF will
*        reside. The placeholder is annulled by this function, and a value
*        of NDF__NOPL will be returned (as defined in the include file
*        "ndf.h").
*     *indf2
*        Returned holding the identifier for the new NDF.
*     *status
*        The global status.

*  Notes:
*     -  If this function is called with "status" set, then a value of
*     NDF__NOID will be returned for the "indf2" parameter, although no
*     further processing will occur. The same value will also be returned
*     if the function should fail for any reason.  In either event the
*     placeholder will still be annulled.  The NDF__NOID constant is
*     defined in the header file "ndf.h".

*  Component Propagation:
*     -  The components whose values are to be propagated (copied) from the
*     existing NDF to the new data structure are specified via the "clist"
*     parameter. Thus "clist"="DATA,QUALITY" would cause the DATA and
*     QUALITY components to be propagated (if available) from the existing
*     NDF to the new structure, in addition to those propagated by default.
*     Component propagation may be suppressed by supplying a component name
*     with the prefix "NO". Thus "clist"="DATA,NOHISTORY" would propagate
*     the DATA component, but suppress propagation of HISTORY. If component
*     names appear more than once in the "clist" value, then the last
*     occurrence takes precedence.
*     -  Propagation of specific NDF extensions may be suppressed by using
*     "NOEXTENSION()" as one of the items in the "clist" parameter; a list
*     of the extensions to be suppressed should appear between the
*     parentheses. Thus "clist"="AXIS,NOEXTENSION(IRAS,ASTERIX)" would
*     propagate the AXIS component, but suppress propagation of the IRAS
*     and ASTERIX extensions (if present). Propagation of suppressed
*     extensions may be re-enabled by specifying "EXTENSION()" in a similar
*     manner at a later point in the "clist" value.
*     -  An asterisk (*) may be used as a wild card to match all extension
*     names. Thus "NOEXTENSION(*),EXTENSION(IRAS)" may be used to indicate
*     that only the IRAS extension should be propagated.
*     -  Whether or not a named extension is propagated by default can be
*     controlled via an NDF tuning parameter (see ndfTune). The defaults
*     established using ndfTune can be over-ridden by specifying the
*     extension explicitly within the "clist" parameter; e.g.
*     "EXTENSION(FITS)" or "NOEXTENSION(FITS)" can be used to over-ride the
*     default established by the PXTFITS tuning parameter.
*     -  Component names in the "clist" parameter may be abbreviated to 3
*     characters, but extension names must appear in full.

*  Copyright:
*     Copyright (C) 2018 East Asian Observatory
*     All rights reserved.

*  Licence:
*     This program is free software; you can redistribute it and/or modify
*     it under the terms of the GNU General Public License as published by
*     the Free Software Foundation; either version 2 of the License, or (at
*     your option) any later version.
*
*     This program is distributed in the hope that it will be useful,but
*     WITHOUT ANY WARRANTY; without even the implied warranty of
*     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
*     General Public License for more details.
*
*     You should have received a copy of the GNU General Public License
*     along with this program; if not, write to the Free Software
*     Foundation, Inc., 51 Franklin Street,Fifth Floor, Boston, MA
*     02110-1301, USA

*  Authors:
*     RFWS: R.F. Warren-Smith (STARLINK)
*     DSB: David S. Berry (EAO)

*  History:
*     3-APR-2019 (DSB):
*        Original version, based on equivalent Fortran function by RFWS.

*-
*/

/* Local Variables: */
   NdfACB *acb1;         /* Pointer to input NDF entry in ACB */
   NdfACB *acb2;         /* Pointer to output NDF entry in ACB */
   NdfPCB *pcb;          /* Pointer to placeholder entry in the PCB */
   char extn[ NDF__MXEXT ][ DAT__SZNAM + 1 ];/* Excluded ext. list */
   int cpf[ NDF__NCPF ];/* Component propagation flags */
   int erase;            /* Whether to erase placeholder object */
   int nextn;            /* Number of excluded extensions */
   int tstat;            /* Temporary status variable */

/* Ensure the NDF library has been initialised. */
   NDF_INIT( status );

/* Set an initial value for the "indf2" parameter. */
   *indf2 = NDF__NOID;

/* Save the "status" value and mark the error stack. */
   tstat = *status;
   errMark();

/* Import the NDF placeholder, converting it to a PCB index. */
   *status = SAI__OK;
   pcb = NULL;
   ndf1Imppl( *place, &pcb, status );

/* If there has been no error so far, then import the input NDF identifier. */
   if( ( *status == SAI__OK ) && ( tstat == SAI__OK ) ) {
      ndf1Impid( indf1, &acb1, status );

/* Get a list of all available extensions in the input NDF. */
      ndf1Xlst( acb1, NDF__MXEXT, extn, &nextn, status );

/* Parse the component propagation expression. */
      ndf1Pscpx( clist, NDF__MXEXT, extn, &nextn, cpf, status );

/* Selectively propagate the components of the input NDF to create a
   new base NDF and an ACB entry to describe it. */
      ndf1Prp( acb1, nextn, extn, cpf, pcb, &acb2, status );

/* Export an identifier for the new NDF. */
      *indf2 = ndf1Expid( ( NdfObject * ) acb2, status );

/* If an error occurred, then annul any ACB entry which may have been
   acquired. */
      if( *status != SAI__OK ) ndf1Anl( &acb2, status );
   }

/* Annul the placeholder, erasing the associated object if any error has
   occurred. */
   if( pcb ) {
      erase = ( ( *status != SAI__OK ) || ( tstat != SAI__OK ) );
      NDF__PCB_LOCK_MUTEX;
      ndf1Annpl( erase, &pcb, status );
      NDF__PCB_UNLOCK_MUTEX;
   }

/* Reset the "place" parameter. */
   *place = NDF__NOPL;

/* Annul any error if "status" was previously bad, otherwise let the new
   error report stand. */
   if( *status != SAI__OK ) {
      if( tstat != SAI__OK ) {
         errAnnul( status );
         *status = tstat;

/* If appropriate, reset the "indf2" parameter, report the error context
   and call the error tracing function. */
      } else {
         *indf2 = NDF__NOID;
         errRep( " ", "ndfScopy: Error selectively copying NDF components "
                 "to a new location.", status );
         ndf1Trace( "ndfScopy", status );
      }
   } else {
      *status = tstat;
   }

/* Release error stack. */
   errRlse();

/* Restablish the original AST status pointer */
   NDF_FINAL

}

