.TITLE       UFACE
.FACILITY    UFACE,280/PREFIX=UFACE__


.SEVERITY	INFORMATIONAL

.BASE		100
CHAR	<character got>
CTRLC	<control-C got>
CTRLU	<control-U got>
CTRLZ	<control-Z got>
DEL	<delete character got>
EOL	<end-of-line got>
ILLCONTEXT	<illegal context - not GET SET OBEY etc.>
INFORM	<informational message received>
MSG	<message received>
NOACT	<no ACTION given in SEND task OBEY action>
NOTASK	<no taskname given in SEND>
NOVAL	<no VALUE given in SEND task SET VALUE>
NOWORD	<expected word missing from string>
REQUEST	<parameter request received>
BYTCNT	<VMS I/O byte count quota exhausted>
OPNFL	<VMS open file quota exhausted>
PGFL	<VMS paging file quota exhausted>
SUBPRC	<VMS subprocess creation quota exhausted>
IFNF	<File not found>
HLPER	<Failure getting help>
.END
