# Output parameter definitions for the ndfpack_mon package
# Created automatically from ../kappa.ifd using ifd2iraf
# 19Dec97
#
set OutputParList(axconv) {}
set DynParList(axconv) {}
set OutputParList(axlabel) {}
set DynParList(axlabel) {}
set OutputParList(axunits) {}
set DynParList(axunits) {}
set OutputParList(chain) {}
set DynParList(chain) {}
set OutputParList(erase) {}
set DynParList(erase) {}
set OutputParList(fitsdin) {}
set DynParList(fitsdin) {}
set OutputParList(fitsexp) {}
set DynParList(fitsexp) {}
set OutputParList(fitsimp) {}
set DynParList(fitsimp) {}
set OutputParList(fitsin) {}
set DynParList(fitsin) {}
set OutputParList(fitslist) {}
set DynParList(fitslist) {}
set OutputParList(fitsmod) {}
set DynParList(fitsmod) {}
set OutputParList(fitstext) {}
set DynParList(fitstext) {}
set OutputParList(hiscom) {}
set DynParList(hiscom) {}
set OutputParList(hislist) {}
set DynParList(hislist) {}
set OutputParList(hisset) {}
set DynParList(hisset) {}
set OutputParList(native) {}
set DynParList(native) {}
set OutputParList(ndfcopy) {}
set DynParList(ndfcopy) {}
set OutputParList(ndftrace) {aend aform alabel amono anorm astart atype aunits avariance axis bad badbits dims extname exttype form history label lbound ndim nextn quality title type ubound units variance width}
set DynParList(ndftrace) {}
set OutputParList(reshape) {}
set DynParList(reshape) {}
set OutputParList(setaxis) {}
set DynParList(setaxis) {}
set OutputParList(setbad) {}
set DynParList(setbad) {}
set OutputParList(setbb) {}
set DynParList(setbb) {}
set OutputParList(setbound) {}
set DynParList(setbound) {}
set OutputParList(setext) {}
set DynParList(setext) {}
set OutputParList(setlabel) {}
set DynParList(setlabel) {}
set OutputParList(setnorm) {}
set DynParList(setnorm) {}
set OutputParList(setorigin) {}
set DynParList(setorigin) {}
set OutputParList(setsky) {}
set DynParList(setsky) {}
set OutputParList(settitle) {}
set DynParList(settitle) {}
set OutputParList(settype) {}
set DynParList(settype) {}
set OutputParList(setunits) {}
set DynParList(setunits) {}
set OutputParList(setvar) {}
set DynParList(setvar) {}
set OutputParList(wcsadd) {}
set DynParList(wcsadd) {}
set OutputParList(wcsattrib) {state value}
set DynParList(wcsattrib) {}
set OutputParList(wcscopy) {}
set DynParList(wcscopy) {}
set OutputParList(wcsframe) {}
set DynParList(wcsframe) {}
set OutputParList(wcsremove) {}
set DynParList(wcsremove) {}
set OutputParList(wcsshow) {}
set DynParList(wcsshow) {}
