! Currently choose a facility code in the Starlink batch
! rather than the JAC batch.
.TITLE     SMF
.FACILITY  SMF,1540/PREFIX=SMF__

.SEVERITY  ERROR

.BASE      100
FLATN      <Data already flatfielded>
NOHDR      <No FITS component>
STRUN      <String truncated>
BDTYP      <Bad data type>
NOMEM      <Memory Allocation Error>
NOKWRD     <Requested keyword is not present in header>
NOLUT      <Object does not contain a MAPCOORD extension>
INSMP      <Insufficient samples for statistics>
TORDB      <Time-ordered bolometer data>
BORDB      <Bolo-ordered bolometer data>
WDIM       <Wrong data dimensions>
DIVBZ      <Divide-by-zero detected>
INFREQ     <Invalid frequency specified>
BADQNM     <Unknown quality name>
BADFLAT    <Bad flatfield data>
NOSCI      <No science data found>
TELSTAT    <Telescope is stationary>
BADFIT     <Fit failed>
RCPPOS     <Inconsistent RECEPPOS detectors posisitions>
MEMCHK     <Memory check passed OK but no map created>
TOOBIG     <Output cube or map is too big to create>
REJECT     <Input data file has been rejected as unusable>

.END
