#!/bin/sh -
#
# To invoke the astrom utility, type:
#
#    astrom [input=inputfile] [report=reportfile] [summary=summaryfile]
#        [log=logfile] [fits=fitsfileroot] [wcsstyle=keyword]
#
# The parameters may be in any order.  Any or all parameters may be
# omitted, and default to
#    input=astrom.dat
#    report=astrom.lis
#    summary=<terminal>
# If `fits' is missing, no FITS WCS headers are generated, and if
# `wcsstyle=' is missing, the headers are in the default style.
# The specifiers `input=' and `report=' may be omitted: if so, then
# the first and second unspecified arguments are taken to be the input
# and report file names.
#
# Norman Gray, Starlink, 2003 May 2
# Based on an earlier version by P T Wallace, Starlink, 1993 December 8.

needinput=true
needreport=true
cmdline=

while test $# -ge 1; do
    if expr $1 : '.*=' >/dev/null; then
        cmdline="$cmdline $1"
    else
        if $needinput; then
            cmdline="$cmdline input=$1"
            needinput=false
        elif $needreport; then
            cmdline="$cmdline report=$1"
            needinput=false
        else
            echo "Lonely argument"
            exit 1
        fi
    fi
    shift
done

if $needinput; then
    cmdline="$cmdline input=astrom.dat"
fi
if $needreport; then
    cmdline="$cmdline report=astrom.lis"
fi

echo astrom.x $cmdline
astrom.x $cmdline

exit 0
