#! /bin/sh
#*******************************************************************************
# E.S.O. - VLT project
#
# "@(#) $Id: MakeLinks,v 1.2 2005/02/02 01:43:03 brighton Exp $"
#
# who       when      what
# --------  --------  ----------------------------------------------
# therlin  10/11/95  created
#

cd library
ln -s mkIndex.tcl mkIndex
cd ../demos
ln -s rtd.sh rtdctrl
ln -s rtd.sh rtdimage
ln -s rtd.sh rtd
ln -s ../../rtdevt/bin/rtdClient rtdClient
ln -s ../../rtdevt/bin/rtdServer rtdServer
cd ../images
ln -s ngc1275.gzfits test.gzfits

#
# ___oOo___
