#!/bin/sh -

# Little script to propagate the version stored in the file VERSION.  The
# version strings to be replaced must either be on a line which
# includes the string %%VERSION%% (probably in a comment) or comes
# immediately after such a line.  It must also be the first string
# which matches the regexp.

# Take list of files to be updated from the argument list.
# Insist that there's at least one file given.
if [ $# -le 0 ]; then
    echo "Usage: $0 <filelist>"
    exit 1
fi

# Work through the non-empty argument list doing the edit.
while [ $# -gt 0 ]; do
    f=$1

    echo -n "Updating $f..."
    mv $f $f~
    sed '/%%VERSION%%/{N;s/[0-9][0-9]*\.[0-9][0-9a-zA-Z.-]*/'`cat VERSION`'/;}' $f~ >$f
    if test $? = 0; then
	echo "ok"
    else
	echo "failed!"
    fi

    shift
done

exit 0

# $Id$


# Regression test:
#
# With file VERSION containing `1.3e', for example,
# this should successfully turn
#
#----------------------
# 1.2.3 %%VERSION%%
# 
# version 1 has version 1.2-3-B7, %%VERSION%%
# 
# Date: 2001/06/01, Version 1.2-17 %%VERSION%%
# Along with version 1.2
# 
# The version number is %%VERSION%%
# Release 12.3b4
# 
#----------------------
#
# into
#
#----------------------
# 1.3e %%VERSION%%
# 
# version 1 has version 1.3e, %%VERSION%%
# 
# Date: 2001/06/01, Version 1.3e %%VERSION%%
# Along with version 1.2
# 
# The version number is %%VERSION%%
# Release 1.3e
# 
#----------------------
