CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C LIMITS.INC Include file for max, min and invalid values  
C
C  alan penny                   ral         1991 Dec


      integer*2   int_invalss			!Bad pixel magic short value
      parameter ( int_invalss = '8000'X )

      integer     int_invalsi			!Bad pixel magic short 
      parameter ( int_invalsi = -32768  )	! (integer*4) value

      integer     int_invali			!Bad pixel magic integer value
      parameter ( int_invali  = '80000000'X )

      real        int_invalr			!Bad pixel magic real value
      parameter ( int_invalr  = 'FF7FFFFF'X )

      real        int_minrr			!Min 'real' value
      parameter ( int_minrr   = 'FF7FFFFF'X )

      real        int_maxrr			!Max 'real' value
      parameter ( int_maxrr   = '7F7FFFFF'X )

      real        int_minir			!Min 'int' value
      parameter ( int_minir   = -2147483648.0 )

      real        int_maxir			!Max 'int' value
      parameter ( int_maxir   = 2147483647.0 )

      integer     int_minii			!Min 'int' value
      parameter ( int_minii   = '80000000'X )

      integer     int_maxii			!Max 'int' value
      parameter ( int_maxii   = '7FFFFFFF'X )

      real        int_minsr			!Min 'short' value
      parameter ( int_minsr   = -32768 )

      real        int_maxsr			!Max 'short' value
      parameter ( int_maxsr   = 32767 )

      integer*2   int_minss			!Min 'short' value
      parameter ( int_minss   = '8000'X )

      integer*2   int_maxss			!Max 'short' value
      parameter ( int_maxss   = '7FFF'X )

