.TITLE       GNS
.FACILITY    GNS,1504/PREFIX=GNS__

.SEVERITY  ERROR

INWKID     <Invalid workstation identifier>
WKNDEF     <Workstation type not defined in database>
NOTINT     <Not an interactive job>
NAMNR      <Device name not recognized>
PKGNS      <Package not supported>
DBINV      <Database file has an invalid format>
DBOVF      <Database file contains too many records>
DBOPE      <Unable to open database file>
DBRDE      <Error reading database file>
DBFME      <Database format error>
UNKCHA     <Unknown characteristic>
AMBNAM     <Ambiguous workstation name>
VNSUP      <Description file version not supported>
AGTND      <AGI type not defined>
AGNNR      <AGI name not recognised>
CIOVF      <No more connection identifiers can be assigned>
NOVER      <No overlay on the device>

.END

