      SUBROUTINE PDA_CHRCNT(XMESS,NMESS)
C***BEGIN PROLOGUE  CHRCNT
C***REFER TO  SQED
C***ROUTINES CALLED  (NONE)
C***END PROLOGUE  CHRCNT
C     COUNT THE NUMBER OF NON-BLANK CHARACTERS IN XMESS.
C     RETURN THE RESULT IN NMESS.
      CHARACTER * (*)  XMESS
      INTEGER NMESS
      DO 10 I = LEN(XMESS),1,-1
         IF (XMESS(I:I).NE.' ') THEN
             NMESS = I
             RETURN
*
         END IF
*
   10 CONTINUE
      NMESS = 0
      RETURN
      END
