      SUBROUTINE PDA_PRT8(N,VM,XOPT,X)

      DOUBLE PRECISION  VM(*), XOPT(*), X(*)
      INTEGER  N

      WRITE(*,'(/,
     1  '' INTERMEDIATE RESULTS AFTER STEP LENGTH ADJUSTMENT'',/)')
      CALL PDA_PRTVEC(VM,N,'NEW STEP LENGTH (VM)')
      CALL PDA_PRTVEC(XOPT,N,'CURRENT OPTIMAL X')
      CALL PDA_PRTVEC(X,N,'CURRENT X')
      WRITE(*,'('' '')')

      RETURN
      END
