      SUBROUTINE PDA_DRFFTI (N,WSAVE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION       WSAVE(*)
      IF (N .EQ. 1) RETURN
      CALL PDA_DRFTI1 (N,WSAVE(N+1),WSAVE(2*N+1))
      RETURN
      END
