      SUBROUTINE PDA_DCFFTI (N,WSAVE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION       WSAVE(*)
      IF (N .EQ. 1) RETURN
      IW1 = N+N+1
      IW2 = IW1+N+N
      CALL PDA_DCFTI1 (N,WSAVE(IW1),WSAVE(IW2))
      RETURN
      END
