C------------------------------- SUBROUTINE 'RCI' ----------------------
C
C+++++++++++++++++++++++++++++
C
      SUBROUTINE RCI(IMAGE)
C
C+++++++++++++++++++++++++++++
C
C     THIS SUBROUTINE IS CALLED BY 'EPHDSK' TO READ THE BLOCKED
C     CHARACTER-ENCODED FORMAT OF THE TAPES EXPORTED FROM JPL.
C     IT OUTPUTS ONE 80-CHARACTER CARD IMAGE PER CALL. THE OUTPUT
C     IS IN THE CHARACTER*80 VARIABLE 'IMAGE'.
C
C     IF THE TAPE SENT TO YOU HAS OTHER THAN 24 IMAGES PER BLOCK,
C     CHANGE THE PARAMETER 'INUM' TO THE CORRECT NUMBER.
C
      SAVE
C
C       NUMBER OF CARD IMAGES PER LOGICAL INPUT RECORD
C
      PARAMETER (INUM=24)
C
C       OUTPUT IMAGE LOCATION IN CALLING SEQUENCE
C
      CHARACTER*80 IMAGE
C
C       STORAGE BUFFER FOR INPUT BLOCKED RECORDS
C
      CHARACTER*80 CB(INUM)
C
C       NUMBER OF IMAGES READ IN BLOCK SO FAR
C
      INTEGER NC
      DATA NC/1000000/
C
C
C       ENTRY POINT -- CHECK TO SEE WHETHER A NEW BLOCK HAS TO BE READ
C
      IF(NC.GE.INUM) THEN
        READ(9,100,END=1)CB
  100   FORMAT(A)
        NC=0
      ENDIF
C
C       TRANSFER NEXT IMAGE IN BLOCK
C
      NC=NC+1
      IMAGE=CB(NC)
      RETURN
C
C       RE-ENTRY FOR EOF ON TAPE READ
C
    1 WRITE(6,101)
  101 FORMAT('0 UNEXPECTED EOF ON TAPE READ.')
      STOP 'TAPE EOF EXIT'
C
      END
