*+
*     E C H _ M O D U L E _ P R O P S
*
*    Description : Functions to determine module properties
*    Keywords : UTILITY
*
*    This routine file contains a set of functions which access
*    various bits in the 'module_properties' byte array.
*
*-
        LOGICAL FUNCTION MODULE_NEEDS( OBJECT, MODULE )
*
        INCLUDE 'ECH_MODULES.INC'
        INTEGER MODULE, OBJECT
        INTEGER IAMINT

        IAMINT = MODULE_PROPERTIES( OBJECT, MODULE )
        MODULE_NEEDS = ( IAND( 1, IAMINT ) .EQ. 1 )

        END


        LOGICAL FUNCTION MODULE_NEEDS_QUALITY( OBJECT, MODULE )
*
        INCLUDE 'ECH_MODULES.INC'
        INTEGER MODULE, OBJECT
        INTEGER IAMINT

        IAMINT = MODULE_PROPERTIES( OBJECT, MODULE )
        MODULE_NEEDS_QUALITY = ( IAND( 2, IAMINT ) .EQ. 2 )

        END


        LOGICAL FUNCTION MODULE_NEEDS_ERRORS( OBJECT, MODULE )
*
        INCLUDE 'ECH_MODULES.INC'
        INTEGER MODULE, OBJECT
        INTEGER IAMINT

        IAMINT = MODULE_PROPERTIES( OBJECT, MODULE )
        MODULE_NEEDS_ERRORS = ( IAND( 4, IAMINT ) .EQ. 4 )

        END


        LOGICAL FUNCTION MODULE_UPDATES( OBJECT, MODULE )
*
        INCLUDE 'ECH_MODULES.INC'
        INTEGER MODULE, OBJECT
        INTEGER IAMINT

        IAMINT = MODULE_PROPERTIES( OBJECT, MODULE )
        MODULE_UPDATES = ( IAND( 8, IAMINT ) .EQ. 8 )

        END


        SUBROUTINE MNEEDS( OBJECT, MODULE )
*
        INCLUDE 'ECH_MODULES.INC'
        INTEGER MODULE, OBJECT
        INTEGER IAMINT

        IAMINT = MODULE_PROPERTIES( OBJECT, MODULE )
        IAMINT = IOR( IAMINT, 1 )
        MODULE_PROPERTIES( OBJECT, MODULE ) = IAMINT

        END


        SUBROUTINE MNEEDS_QUALITY( OBJECT, MODULE )
*
        INCLUDE 'ECH_MODULES.INC'
        INTEGER MODULE, OBJECT
        INTEGER IAMINT

        IAMINT = MODULE_PROPERTIES( OBJECT, MODULE )
        IAMINT = IOR( IAMINT, 2 )
        MODULE_PROPERTIES( OBJECT, MODULE ) = IAMINT

        END


        SUBROUTINE MNEEDS_ERRORS( OBJECT, MODULE )
*
        INCLUDE 'ECH_MODULES.INC'
        INTEGER MODULE, OBJECT
        INTEGER IAMINT

        IAMINT = MODULE_PROPERTIES( OBJECT, MODULE )
        IAMINT = IOR( IAMINT, 4 )
        MODULE_PROPERTIES( OBJECT, MODULE ) = IAMINT

        END


        SUBROUTINE MUPDS( OBJECT, MODULE )
*
        INCLUDE 'ECH_MODULES.INC'
        INTEGER MODULE, OBJECT
        INTEGER IAMINT

        IAMINT = MODULE_PROPERTIES( OBJECT, MODULE )
        IAMINT = IOR( IAMINT, 8 )
        MODULE_PROPERTIES( OBJECT, MODULE ) = IAMINT

        END
