*+
*  Name:
*     ECH_GRAPHICS.INC

*  Purpose:
*     Constants for graphics and plotting routines.

*  Authors:
*     MJC: Martin Clayton (Starlink, UCL)

*-
      INTEGER COL_BLACK
      PARAMETER ( COL_BLACK = 1 )

      INTEGER COL_RED
      PARAMETER ( COL_RED = 2 )

      INTEGER COL_GREEN
      PARAMETER ( COL_GREEN = 3 )

      INTEGER COL_BLUE
      PARAMETER ( COL_BLUE = 4 )

      INTEGER COL_WHITE
      PARAMETER ( COL_WHITE = 5 )

      INTEGER COL_CYAN
      PARAMETER ( COL_CYAN = 6 )

      INTEGER COL_MAGENTA
      PARAMETER ( COL_MAGENTA = 7 )

      INTEGER COL_YELLOW
      PARAMETER ( COL_YELLOW = 8 )

      INTEGER STY_FULL
      PARAMETER ( STY_FULL = 1 )

      INTEGER STY_DASH
      PARAMETER ( STY_DASH = 2 )

      INTEGER STY_DOTD
      PARAMETER ( STY_DOTD = 3 )


