*+  PSF_INTRO - Introduce a dataset to the psf system
      SUBROUTINE PSF_INTRO( ID, SLOT, STATUS )
      IMPLICIT NONE
      INCLUDE 'SAE_PAR'
      INCLUDE 'DAT_PAR'
      CHARACTER*(DAT__SZLOC) LOC
        INTEGER ID,SLOT,STATUS
      LOGICAL THERE
      IF ( STATUS.NE.SAI__OK) RETURN
      CALL ADI_THERE( ID, '.PSF_SLOT', THERE, STATUS )
      IF ( THERE ) THEN
        CALL ADI_CGET0I( ID, '.PSF_SLOT', SLOT, STATUS )
      ELSE
        CALL ADI1_GETLOC( ID, LOC, STATUS )
        CALL PSF_GETSLOT( ID, SLOT, STATUS )
        CALL ADI_CPUT0I( ID, '.PSF_SLOT', SLOT, STATUS )
        CALL PSF_CHKAXES( SLOT, STATUS )
      END IF

      END
