.TITLE       PARSE
.FACILITY    PARSE,160/PREFIX=PARSE__


.SEVERITY	INFORMATIONAL

.BASE		100
GLOBACC	<invalid ASSOCIATION access symbol>
IFLOPN	<failed to open interface text file>
IVCONV	<type conversion failed>
IVLIST	<constraint list cannot contain structures or logicals>
IVPOS	<POSITION specifier is not an integer>
IVSYN	<invalid syntax - latest word obtained was not expected>
IVVPATH	<invalid VPATH specifier>
NOACT	<requested action name not defined>
NOEND	<missing ENDINTERFACE or ENDMONOLITH statement>
NOMEM	<parameter/action storage space full>
NOPAR	<requested parameter name not defined>
OLDACT	<attempt to define an action which is already defined>
OLDPAR	<attempt to define a parameter which is already defined>
OLDPOS	<attempt to define a POSITION which is aready in use>
OLDREQ	<name repeated on a NEEDS list>
READERR	<error reading interface text file>
VALSYN	<syntax error in an attempt to give a parameter value>
VALTYPE	<mismatch between given constant value and declared type>
IVCOORD	<menu coordinate is not an integer>
IVPPATH	<invalid PPATH specifier>
OLDACTKEY	<duplicate action KEYWORD>
ACTLEN	<action name too long>
PARLEN	<parameter name too long>
IFCOPN	<failed to create output (.IFC) file>
BIGVEC	<token storage overflow>
NCPOS	<Parameter positions are not a contiguous set>
MISEND	<Missing ENDINTERFACE>
.END
