proc cgs4drShowEnv {taskname} {
  global env
  cgs4drClear $taskname
  cgs4drInform $taskname "PID                = $env(PID)"
  cgs4drInform $taskname "CGS4_CT            = $env(CGS4_CT)"
  cgs4drInform $taskname "CGS4_TEMPLATES     = $env(CGS4_TEMPLATES)"
  cgs4drInform $taskname "CGS4_NDF_TEMPLATES = $env(CGS4_NDF_TEMPLATES)"
  cgs4drInform $taskname "CGS4_DST_TEMPLATES = $env(CGS4_DST_TEMPLATES)"
  cgs4drInform $taskname "CGS4_ARLINES       = $env(CGS4_ARLINES)"
  cgs4drInform $taskname "CGS4_DOCS          = $env(CGS4_DOCS)"
  cgs4drInform $taskname "CGS4_EXE           = $env(CGS4_EXE)"
  cgs4drInform $taskname "CGS4_ICL           = $env(CGS4_ICL)"
  cgs4drInform $taskname "CGS4_CONFIG        = $env(CGS4_CONFIG)"
  cgs4drInform $taskname "CGS4_HOME          = $env(CGS4_HOME)"
  cgs4drInform $taskname "CGS4_ENG           = $env(CGS4_ENG)"
  cgs4drInform $taskname "CGS4_INDEX         = $env(CGS4_INDEX)"
  cgs4drInform $taskname "CGS4_DATA          = $env(CGS4_DATA)"
  cgs4drInform $taskname "CGS4_DATE          = $env(CGS4_DATE)"
  cgs4drInform $taskname "CGS4_FORMAT        = $env(CGS4_FORMAT)"
  cgs4drInform $taskname "CGS4_MASKS         = $env(CGS4_MASKS)"
  cgs4drInform $taskname "CGS4_EXE           = $env(CGS4_EXE)"
  cgs4drInform $taskname "RED4_FORMAT        = $env(RED4_FORMAT)"
  cgs4drInform $taskname "P4_ROOT            = $env(P4_ROOT)"
  cgs4drInform $taskname "P4_EXE             = $env(P4_EXE)"
  cgs4drInform $taskname "P4_ICL             = $env(P4_ICL)"
  cgs4drInform $taskname "P4_CT              = $env(P4_CT)"
  cgs4drInform $taskname "P4_HOME            = $env(P4_HOME)"
  cgs4drInform $taskname "P4_CONFIG          = $env(P4_CONFIG)"
  cgs4drInform $taskname "P4_HC              = $env(P4_HC)"
  cgs4drInform $taskname "P4_DATE            = $env(P4_DATE)"
  cgs4drInform $taskname "P4_DATA            = $env(P4_DATA)"
  cgs4drInform $taskname "QMAN_ROOT          = $env(QMAN_ROOT)"
  cgs4drInform $taskname "QMAN_EXE           = $env(QMAN_EXE)"
  cgs4drInform $taskname "QMAN_ICL           = $env(QMAN_ICL)"
  cgs4drInform $taskname "QMAN_CONFIG        = $env(QMAN_CONFIG)"
  cgs4drInform $taskname "QMAN_DATE          = $env(QMAN_DATE)"
  if {$env(DOMAIN) != "ukirt.jach.hawaii.edu."} {
    cgs4drInform $taskname "QMAN_PASS          = $env(QMAN_PASS)"
    cgs4drInform $taskname "QMAN_LOCK          = $env(QMAN_LOCK)"
  }
  cgs4drInform $taskname "IDIR               = $env(IDIR)"
  cgs4drInform $taskname "ODIR               = $env(ODIR)"
  cgs4drInform $taskname "RIDIR              = $env(RIDIR)"
  cgs4drInform $taskname "RODIR              = $env(RODIR)"
  cgs4drInform $taskname "RGDIR              = $env(RGDIR)"
  cgs4drInform $taskname "FIGARO_FORMATS     = $env(FIGARO_FORMATS)"
}
