.TITLE		AST_ERR
.FACILITY	AST,1521/PREFIX=AST__
!author		R.F. Warren-Smith & D.S. Berry (STARLINK)

.SEVERITY	ERROR
.BASE 300

ATGER           <attribute getting error>
ATSER           <attribute setting error>
ATTIN           <attribute value invalid>
AXIIN           <axis index invalid>
BADAT           <bad attribute name>
BADBX           <zero-sized box given>
BADIN           <bad input data>
BADNI           <bad number of input coordinates>
BADNO           <bad number of output coordinates>
BADWM           <WinMap contains no bounds information>
BDBRK           <bad break index>
BDFMT           <bad field specifier>
BDFTS           <invalid FITS keyword value found>
BDOBJ           <inappropriate Object supplied>
CLPAX           <wrong number of clipping axes>
CORNG           <range of coordinates invalid>
CVBRK           <too many breaks in a curve>
DIMIN           <array dimensions invalid>
DTERR           <date/time error>
ENDIN           <invalid use of astEnd>
EOCHN           <end of input Channel encountered>
EXPIN           <attempt to export Object pointer from level zero>
FCRPT           <corrupted FitsChan supplied>
FMTER           <error while formatting coordinate value>
FRMIN           <Frame index invalid>
FRSIN           <FrameSet invalid>
FTCNV           <cannot convert FITS data value type>
GRFER           <low level graphics error>
INHAN           <invalid Handle>
INNCO           <incompatible numbers of coordinates>
INTER           <internal programming error>
INTRD           <incompatible transformation directions>
LDERR           <class loader error>
LUTII           <invalid lookup table increment>
LUTIN           <invalid number of lookup table elements>
MEMIN           <requested memory size invalid>
MTR23           <not a 2d or 3d MatrixMap>
MTRAX           <null rotation axis supplied>
MTRML           <bad matrix shapes for multiplication>
MTRMT           <null matrix supplied>
NAXIN           <number of axes invalid>
NCHIN           <number of characters invalid>
NCOIN           <number of coordinates invalid>
NCPIN           <number of coordinates per point invalid>
NELIN           <number of array elements invalid>
NOCTS           <number of output coordinates too small>
NODEF           <transformation not defined>
NOFTS           <required FITS keywords missing>
NOMEM           <unable to allocate memory>
NOPTS           <number of output points too small>
NOWRT           <attribute is read-only>
NPTIN           <number of points invalid>
OBJIN           <Object invalid>
OPT             <invalid Plot option>
PDSIN           <points data structure invalid>
PLFMT           <no numerical labels can be produced>
PRMIN           <permutation invalid>
PTRIN           <pointer invalid>
PTRNG           <range of points invalid>
RDERR           <read error>
REMIN           <invalid attempt to remove last Frame>
SCSIN           <sky coordinate system invalid>
SELIN           <axis selection invalid>
SLAIN           <bad SLALIB transformation type>
TRNND           <coordinate transformation not defined>
UNMQT           <unmatched quotes>
VSMAL           <valid area too small>
WCSAX           <non-existent longitude or latitude axis>
WCSNC           <too few mapping coordinates>
WCSPA           <invalid projection parameters>
WCSTY           <unknown projection type>
XSOBJ           <too many Objects in use at once>
ZOOMI           <zoom factor invalid>

!  New codes introduced for V1.1.
ILOST           <FrameSet integrity lost>
ITFER           <error in IntraMap transformation function>
ITFNI           <IntraMap transformation function name invalid>
MBDNF           <Mapping bounds not found>
MRITF           <multiple registration of IntraMap transformation function>
OCLUK           <Object class unknown>
UNFER           <error while unformatting a coordinate value>
URITF           <unregistered IntraMap transformation function>

.END
