      SUBROUTINE TSP_MON(STATUS)

*  Top level routine of TSP monolith

      INCLUDE 'SAE_PAR'
      INCLUDE 'PAR_PAR'

      INTEGER STATUS
      CHARACTER*(PAR__SZNAM) NAME

      CALL NDF_BEGIN

      CALL TASK_GET_NAME(NAME,STATUS)

      IF (NAME .EQ. 'PPLOT') THEN
          CALL PPLOT(STATUS)
      ELSE IF (NAME .EQ. 'SPLOT') THEN
          CALL SPLOT(STATUS)
      ELSE IF (NAME .EQ. 'FPLOT') THEN
          CALL FPLOT(STATUS)
      ELSE IF (NAME .EQ. 'LTCORR') THEN
          CALL LTCORR(STATUS)
      ELSE IF (NAME .EQ. 'PHASEPLOT') THEN
          CALL PHASEPLOT(STATUS)
      ELSE IF (NAME .EQ. 'QPLOT') THEN
          CALL QPLOT(STATUS)
      ELSE IF (NAME .EQ. 'QUMERGE') THEN
          CALL QUMERGE(STATUS)
      ELSE IF (NAME .EQ. 'QUPLOT') THEN
          CALL QUPLOT(STATUS)
      ELSE IF (NAME .EQ. 'QUSUB') THEN
          CALL QUSUB(STATUS)
      ELSE IF (NAME .EQ. 'RFIGARO') THEN
          CALL RFIGARO(STATUS)
      ELSE IF (NAME .EQ. 'RHDSPLOT') THEN
          CALL RHDSPLOT(STATUS)
      ELSE IF (NAME .EQ. 'RIRPS') THEN
          CALL RIRPS(STATUS)
      ELSE IF (NAME .EQ. 'TMERGE') THEN
          CALL TMERGE(STATUS)
      ELSE IF (NAME .EQ. 'TBIN') THEN
          CALL TBIN(STATUS)
      ELSE IF (NAME .EQ. 'TSHIFT') THEN
          CALL TSHIFT(STATUS)
      ELSE IF (NAME .EQ. 'TSPLOT') THEN
          CALL TSPLOT(STATUS)
      ELSE IF (NAME .EQ. 'TDERIV') THEN
          CALL TDERIV(STATUS)
      ELSE IF (NAME .EQ. 'IPCS2STOKES') THEN
          CALL IPCS2STOKES(STATUS)
      ELSE IF (NAME .EQ. 'CCD2STOKES') THEN
          CALL CCD2STOKES(STATUS)
      ELSE IF (NAME .EQ. 'FLIP') THEN
          CALL FLIP(STATUS)
      ELSE IF (NAME .EQ. 'COMBINE') THEN
          CALL COMBINE(STATUS)
      ELSE IF (NAME .EQ. 'REVERSE') THEN
          CALL REVERSE(STATUS)
      ELSE IF (NAME .EQ. 'CALFIT') THEN
          CALL CALFIT(STATUS)
      ELSE IF (NAME .EQ. 'CALIB') THEN
          CALL CALIB(STATUS)
      ELSE IF (NAME .EQ. 'XCOPY') THEN
          CALL XCOPY(STATUS)
      ELSE IF (NAME .EQ. 'SUBSET') THEN
          CALL SUBSET(STATUS)
      ELSE IF (NAME .EQ. 'PTHETA') THEN
          CALL PTHETA(STATUS)
      ELSE IF (NAME .EQ. 'SCRUNCH') THEN
          CALL SCRUNCH(STATUS)
      ELSE IF (NAME .EQ. 'SPFLUX') THEN
          CALL SPFLUX(STATUS)
      ELSE IF (NAME .EQ. 'RTURKU') THEN
          CALL RTURKU(STATUS)
      ELSE IF (NAME .EQ. 'RHATHSP') THEN
          CALL RHATHSP(STATUS)
      ELSE IF (NAME .EQ. 'SUBTRACT') THEN
          CALL SUBTRACT(STATUS)
      ELSE IF (NAME .EQ. 'CMULT') THEN
          CALL CMULT(STATUS)
      ELSE IF (NAME .EQ. 'BUILD3D') THEN
          CALL BUILD3D(STATUS)
      ELSE IF (NAME .EQ. 'DISPLAY') THEN
          CALL DISPLAY(STATUS)
      ELSE IF (NAME .EQ. 'RCCDTS') THEN
          CALL RCCDTS(STATUS)
      ELSE IF (NAME .EQ. 'SKYSUB') THEN
          CALL SKYSUB(STATUS)
      ELSE IF (NAME .EQ. 'CCDPHOT') THEN
          CALL CCDPHOT(STATUS)
      ELSE IF (NAME .EQ. 'CCDPOL') THEN
          CALL CCDPOL(STATUS)
      ELSE IF (NAME .EQ. 'TLIST') THEN
          CALL TLIST(STATUS)
      ELSE IF (NAME .EQ. 'TSETBAD') THEN
          CALL TSETBAD(STATUS)
      ELSE IF (NAME .EQ. 'RHATPOL') THEN
          CALL RHATPOL(STATUS)
      ELSE IF (NAME .EQ. 'LHATPOL') THEN
          CALL LHATPOL(STATUS)
      ELSE IF (NAME .EQ. 'EPLOT') THEN
          CALL EPLOT(STATUS)
      ELSE IF (NAME .EQ. 'CCD2POL') THEN
          CALL CCD2POL(STATUS)
      ELSE IF (NAME .EQ. 'LMERGE') THEN
          CALL LMERGE(STATUS)
      ELSE IF (NAME .EQ. 'CALFITPA') THEN
          CALL CALFITPA(STATUS)
      ELSE IF (NAME .EQ. 'CALPA') THEN
          CALL CALPA(STATUS)
      ELSE IF (NAME .EQ. 'FLCONV') THEN
          CALL FLCONV(STATUS)
      ELSE IF (NAME .EQ. 'EXTIN') THEN
          CALL EXTIN(STATUS)
      ELSE IF (NAME .EQ. 'RCGS2') THEN
          CALL RCGS2(STATUS)
      ELSE IF (NAME .EQ. 'ROTPA') THEN
          CALL ROTPA(STATUS)
      ELSE IF (NAME .EQ. 'IRFLUX') THEN
          CALL IRFLUX(STATUS)
      ELSE IF (NAME .EQ. 'DIVIDE') THEN
          CALL DIVIDE(STATUS)
      ELSE IF (NAME .EQ. 'TSPROFILE') THEN
          CALL TSPROFILE(STATUS)
      ELSE IF (NAME .EQ. 'TSEXTRACT') THEN
          CALL TSEXTRACT(STATUS)
      ELSE IF (NAME .EQ. 'TEXTIN') THEN
          CALL TEXTIN(STATUS)
      ELSE IF (NAME .EQ. 'IMOTION') THEN
          CALL IMOTION(STATUS)
      ELSE IF (NAME .EQ. 'SHIFTADD') THEN
          CALL SHIFTADD(STATUS)
      ELSE IF (NAME .EQ. 'DSTOKES') THEN
          CALL DSTOKES(STATUS)
      ELSE IF (NAME .EQ. 'IMPOL') THEN
          CALL IMPOL(STATUS)
      ELSE IF (NAME .EQ. 'SLIST') THEN
          CALL SLIST(STATUS)
      ELSE IF (NAME .EQ. 'IRISPOL') THEN
          CALL IRISPOL(STATUS)
      ELSE IF (NAME .EQ. 'IRISAP') THEN
          CALL IRISAP(STATUS)
      ELSE IF (NAME .EQ. 'CGS4POL') THEN
          CALL CGS4POL(STATUS)
      ELSE IF (NAME .EQ. 'IRISAPC') THEN
          CALL IRISAPC(STATUS)
      ELSE IF (NAME .EQ. 'IRISPOLC') THEN
          CALL IRISPOLC(STATUS)
      ENDIF
      CALL NDF_END(STATUS)
      END
