.TITLE       USER
.FACILITY    USER,350/PREFIX=USER__


.SEVERITY	INFORMATIONAL

.BASE		100
001	<application internal status value>
002	<application internal status value>
003	<application internal status value>
004	<application internal status value>
005	<application internal status value>
006	<application internal status value>
007	<application internal status value>
008	<application internal status value>
009	<application internal status value>
010	<application internal status value>
011	<application internal status value>
012	<application internal status value>
013	<application internal status value>
014	<application internal status value>
015	<application internal status value>
016	<application internal status value>
017	<application internal status value>
018	<application internal status value>
019	<application internal status value>
020	<application internal status value>
021	<application internal status value>
022	<application internal status value>
023	<application internal status value>
024	<application internal status value>
025	<application internal status value>
026	<application internal status value>
027	<application internal status value>
028	<application internal status value>
029	<application internal status value>
030	<application internal status value>
.END
