#!/bin/sh
#
#  - - - - -
#   H L I B
#  - - - - -
#
#  Translate one or more HELP libraries from source form to the
#  direct-access file used by the software.
#
#  Command:
#
#      hlib  helpfile1 helpfile2...
#
#  A HELP source file called "helpfile" is translated into
#  the file "helpfile.shl".
#
#  It is suggested that HELP source file names end with ".hlp".
#
#  Thus the command "hlib *.hlp" will translate all HELP libraries
#  in the current directory into the form required for use.
#
#  Latest revision:   13 January 1996
#
#  Copyright P.T.Wallace 1996.  All rights reserved.
#
for file in "$@"; do
   crehlp "$file" "${file%.*}.shl"
   if [[ $? != 0 ]]; then
     echo Error running crehlp
     if [[ -e "${file%.*}".shl ]]; then
       rm "${file%.*}".shl
     fi
     exit 1
   fi
done
