.TITLE       ERR
.FACILITY    ERR,102/PREFIX=ERR__


.SEVERITY	ERROR

.BASE		200
OPTER	<Error encountered during message output.>

.BASE		300
UNSET	<Status not set in call to ERR_REP (improper use of ERR_REP).>
BADOK	<Status set to SAI__OK in call to ERR_REP (improper use of ERR_REP).>
BDPAR	<Invalid tuning parameter name (improper use of ERR_TUNE).>
BTUNE	<Bad tuning value (improper use of ERR_TUNE).>
BDENV	<Bad ERR environment variable value.>
.END
