

F77_SUBROUTINE(msg_setr)( CHARACTER(TOKEN), REAL(RVALUE) TRAIL(TOKEN) );
F77_SUBROUTINE(msg_seti)( CHARACTER(TOKEN), INTEGER(IVALUE) TRAIL(TOKEN) );
F77_SUBROUTINE(msg_setd)( CHARACTER(TOKEN), DOUBLE(DVALUE) TRAIL(TOKEN) );
F77_SUBROUTINE(msg_setl)( CHARACTER(TOKEN), LOGICAL(LVALUE) TRAIL(TOKEN) );
F77_SUBROUTINE(msg_setc)( CHARACTER(TOKEN), CHARACTER(CVALUE)
                          TRAIL(TOKEN) TRAIL(CVALUE) );

F77_SUBROUTINE(err_annul)( INTEGER(STATUS) );
F77_SUBROUTINE(err_begin)( INTEGER(STATUS) );
F77_SUBROUTINE(err_end)( INTEGER(STATUS) );
