.TITLE       MSG
.FACILITY    MSG,103/PREFIX=MSG__


.SEVERITY	ERROR

.BASE		200
OPTER	<Error encountered during message output.>
SYNER	<Error encountered during message synchronisation.>
INVIF	<Invalid conditional message filter value.>
BDPAR	<Invalid tuning parameter name (improper use of MSG_TUNE).>
BTUNE	<Bad tuning value (improper use of MSG_TUNE).>
BDENV	<Bad MSG environment variable value.>
FATAL <Fatal internal error.>
.END
