#!/bin/sh
# $Id$

#+
#  Name:
#     mksumm
#
#  Purpose:
#     Generate all required summary files for SGML document crossreferencing.
#
#  Description:
#     This script does what is required to fill a directory with 
#     appropriate .summary files corresponding to the Starlink summary 
#     DTD, and a corresponding CATALOG.  It acts as a driver for other
#     scripts which actually do the work.
#
#     What it actually does is:
#        Invoke htx2summ.pl on all the Starlink documents which have 
#        associated .htx directories.
#
#        Invoke minsumm.pl to generate minimal summary files for all
#        the other starlink documents.
#
#     The effect of this is to leave a .summary file in the appropriate
#     place ($STARLINK_SGML_DIR/documents) for each Starlink document
#     present on the system.  Each summary file should conform to the 
#     Starlink summary DTD.  A CATALOG file is written in the same
#     directory containing a public identifier for each of the summary 
#     files.
#
#  Environment:
#     This script requires that the htx2summ.pl and minsumm.pl are in 
#     the PATH.  These perl scripts in turn require that the directory
#     containing their dependencies is in PERL5LIB.
#
#  Arguments:
#     None.
#
#  Options:
#     --docdir dirname
#          specify the source for the HTX files (default $STARLINK/docs).
#     --summdir dirname
#          specify the target directory for the summary files (default
#          $STARLINK_SGML_DIR/documents).
#
#  Authors:
#     MBT: Mark Taylor (IoA, Starlink)
#     NG: Norman Gray (Starlink, Glasgow)
#
#  History:
#     25-AUG-1999 (MBT):
#        Initial version.
#     15-Jun-2000 (NG):
#        Added --docdir and --summdir options.
#-

summdir=''
docdir=''

libdir=$STARLINK_SGML_DIR/lib
HTX2SUMM=$libdir/htx2summ.pl
MINSUMM="perl $libdir/minsumm.pl"
STARDECL=$STARLINK_SGML_DIR/dtd/starlink.decl
PERL5LIB=$libdir
export PERL5LIB

USAGE ()
{
      echo "Usage: $0 [--summdir summary-dir] [--docdir source-docs-dir]"
      echo '   --summdir default: $STARLINK_SGML_DIR/documents'
      echo '   --docdir  default: $STARLINK/docs'
      exit 1
}

#  Parse options
      while [ $# -gt 0 ]; do
         case $1 in
	    --summdir)
		if test $# -ge 2; then shift; else USAGE; fi
		summdir=$1
		shift
		;;
	    --docdir)
		if test $# -ge 2; then shift; else USAGE; fi
		docdir=$1
		shift
		;;
	    *) USAGE;;
	 esac
      done

#  Set up directory locations.
      if [ "$STARLINK_SGML_DIR" = "" ]
      then
         echo 1>&2 '$STARLINK_SGML_DIR is not set'
         exit 1
      fi
      if [ "$STARLINK" = "" ]
      then
         STARLINK=/star
         export STARLINK
      fi
      test -n "$summdir" || summdir=$STARLINK_SGML_DIR/documents
      test -n "$docdir"  || docdir=$STARLINK/docs
      warnfile=$summdir/mksumm.warnings


#  Clear out files.
      rm -f $summdir/*.summary $summdir/CATALOG $warnfile

#  Write summary files for all the documents which have been star2htmlized 
#  and thus have HTX directories.
      echo "Writing summary files in $summdir using $docdir/*.htx files:"
      for htxfile in $docdir/*.htx
      do
         name=`echo $htxfile | sed -e's%.*/%%' -e's%\.htx$%%'`
         echo "   $name"
         texfile=`echo $htxfile | sed -e's%\.htx$%.tex%'`
         summfile=$summdir/$name.summary
         if [ -f $texfile ] 
         then
            args="$htxfile $texfile"
         else
            args="$htxfile"
         fi
         if $HTX2SUMM $args >$summfile 2>>$warnfile
         then
            :
         else
            echo "Command failed:"
            echo "   $HTX2SUMM $args"
            echo "see $warnfile"
            exit 1
         fi
      done

#  The rest of the script executes within the summary directory.
      cd $summdir

#  Write summary files for those entries in docs_lis which weren't
#  covered by the previous procedure.
      echo "Writing minimal summary files in $summdir using $docdir/docs_lis"
      if $MINSUMM 2>>$warnfile
      then
         :
      else
         echo "Command failed:"
         echo "   $MINSUMM"
         echo "see $warnfile"
         exit 1
      fi

#  Write info to user and update the CATALOG file.
      echo "Summaries written - see $warnfile for warnings."
      echo " "
      echo "Writing $summdir/CATALOG file"
      for f in *.summary
      do
         id=`echo $f | sed -e's%.summary%%' -e's%[0-9]%/&%' | tr a-z A-Z` 
         echo "PUBLIC '-//Starlink//DOCUMENT Summary $id//EN' $f"
      done >CATALOG

#  Check that all summary files conform.
      echo "Checking conformance of summary files"
      for summ in *.summary
      do
         echo "   $summ"
         nsgmls -s $STARDECL $summ
      done 2>>$warnfile
      echo "Non-conforming summary files logged in $warnfile"

