	SUBROUTINE PLT2D_READFILEF( NAMEFILE, NUMVAL, DATARR)

* History
* 25-Jul-1994 Changed LIB$ and type Statements to FIO_ (SKL@JACH)
*

	IMPLICIT NONE

        INCLUDE 'SAE_PAR'
        INCLUDE 'FIO_ERR'

	INTEGER STATUS, ISTAT, NUMVAL, LUN

	INTEGER DATARR( NUMVAL)

	CHARACTER*( *) NAMEFILE

	CALL FIO_GUNIT( LUN, STATUS )

	OPEN( UNIT=LUN, FILE=NAMEFILE, STATUS='OLD', FORM='UNFORMATTED',
     :	      IOSTAT=ISTAT, ERR=999)

	READ( LUN) DATARR

	CLOSE( LUN)

	CALL FIO_PUNIT( LUN, STATUS )

	RETURN

  999	CALL FIO_REP( LUN, NAMEFILE, ISTAT,
     :      'Error opening file ^fname, status=^iostat', STATUS )

	CALL FIO_PUNIT( LUN, STATUS )

	END
