	SUBROUTINE PLT2D_READFILE( NUMFILE, NUMVAL, DATARR)

* History
* 25-Jul-1994 Changed lIB$ to FIO_ (SKL@JACH)
*

	IMPLICIT NONE

        INCLUDE 'SAE_PAR'
        INCLUDE 'FIO_ERR'

	INTEGER NUMFILE, NUMVAL, LUN
        INTEGER STATUS
	INTEGER DATARR( NUMVAL)

	CALL FIO_GUNIT( LUN, STATUS )

	IF( NUMFILE .EQ. 1) THEN
	  OPEN( UNIT=LUN, FILE='IMAGEDIR:QUICK1.DAT', STATUS='OLD',
     :	        FORM='UNFORMATTED',
     :	        ERR=999)
	ELSE IF( NUMFILE .EQ. 2) THEN
	  OPEN( UNIT=LUN, FILE='IMAGEDIR:QUICK2.DAT', STATUS='OLD',
     :	        FORM='UNFORMATTED',
     :	        ERR=999)
	ELSE IF( NUMFILE .EQ. 3) THEN
	  OPEN( UNIT=LUN, FILE='IMAGEDIR:QUICK3.DAT', STATUS='OLD',
     :	        FORM='UNFORMATTED',
     :	        ERR=999)
	ELSE IF( NUMFILE .EQ. 4) THEN
	  OPEN( UNIT=LUN, FILE='IMAGEDIR:QUICK4.DAT', STATUS='OLD',
     :	        FORM='UNFORMATTED',
     :	        ERR=999)
	END IF

	READ( LUN) DATARR

	CLOSE( LUN)

	CALL FIO_PUNIT( LUN, STATUS )

	RETURN

  999	CALL ERR_REP( 'ERR', 'Error, file not found', STATUS )
	CALL FIO_PUNIT( LUN, STATUS )

	END
