	SUBROUTINE RESET_DEVICE( STATUS)

* subroutine to RESET SGS/GKS under specified workstation

	IMPLICIT NONE

	INCLUDE 'ADAMDEFNS'
	INCLUDE 'ADAMERRS'

	INCLUDE 'DTDEFNS'
	INCLUDE 'DTERRS'

	INCLUDE 'PLT2DCOM'

	INTEGER ERROR
	INTEGER STATUS
	INTEGER WKTRUP

	REAL CWXQ
	REAL CWXP
	REAL CWYQ
	REAL CWYP
	REAL RWXQ
	REAL RWXP
	REAL RWYQ
	REAL RWYP
	REAL RWINDO( 4)
	REAL CWINDO( 4)
	REAL RVIEWP( 4)
	REAL CVIEWP( 4)

* ==============================================================================

* get the plotting coordinates on window

	CALL GQWKT( 1, ERROR, WKTRUP, RWINDO, CWINDO, RVIEWP, CVIEWP)

	RWXP = RWINDO( 1)
	RWYP = RWINDO( 3)
	RWXQ = RWINDO( 2)
	RWYQ = RWINDO( 4)

	CWXP = CWINDO( 1)
	CWYP = CWINDO( 3)
	CWXQ = CWINDO( 2)
	CWYQ = CWINDO( 4)

* set workstation viewport and window

	IF( DEVICE_NAME .EQ. 'VERSATEK' .OR. DEVICE_NAME .EQ. 'VER' .OR.
     :	    DEVICE_NAME .EQ. 'VERSATEC') THEN

	  CALL GSVP( 1, RWXP, RWYQ/RWXQ/0.75, RWYP, RWYQ)
	  CALL GSWN( 1, 0.0, MAX_Y/0.75, 0.0, FLOAT( MAX_Y))

	  MAX_X = IFIX( MAX_Y/0.75)

	ELSE IF( DEVICE_NAME .EQ. 'PRINTRONIX' .OR. DEVICE_NAME .EQ. 'LP')THEN

	  CALL GSVP( 1, RWXP, RWYQ/RWXQ/0.75, RWYP, RWYQ)
	  CALL GSWN( 1, 0.0, MAX_Y/0.75, 0.0, FLOAT( MAX_Y))

	  MAX_X = IFIX( MAX_X/0.75)

	ELSE IF( DEVICE_NAME .EQ. 'ZETA' )THEN

	  CALL GSVP( 1, RWXP, RWYQ/RWXQ/0.75, RWYP, RWYQ)
	  CALL GSWN( 1, 0.0, MAX_Y/0.75, 0.0, FLOAT( MAX_Y))

	  MAX_X = IFIX( MAX_X/0.75)

	ELSE

	  CALL GSVP( 1, RWXP, RWXQ, RWYP, RWYQ)
	  CALL GSWN( 1, 0.0, FLOAT( MAX_X), 0.0, FLOAT( MAX_Y))

	END IF

	END
