      SUBROUTINE CURSA (STATUS)

*    Top-level subroutine for monolith CURSA.
*    Created automatically on Thu Nov 30 13:59:41 GMT 2000.

      IMPLICIT NONE
      INTEGER STATUS

      INCLUDE 'SAE_PAR'
      CHARACTER ACTION*15

      CALL TASK_GET_NAME (ACTION, STATUS)

      IF (ACTION .EQ. 'CATCHART') THEN
         CALL CATCHART (STATUS)

      ELSE IF (ACTION .EQ. 'CATCHARTRN') THEN
         CALL CATCHARTRN (STATUS)

      ELSE IF (ACTION .EQ. 'CATCOORD') THEN
         CALL CATCOORD (STATUS)

      ELSE IF (ACTION .EQ. 'CATCOPY') THEN
         CALL CATCOPY (STATUS)

      ELSE IF (ACTION .EQ. 'CATGRID') THEN
         CALL CATGRID (STATUS)

      ELSE IF (ACTION .EQ. 'CATGSCIN') THEN
         CALL CATGSCIN (STATUS)

      ELSE IF (ACTION .EQ. 'CATHEADER') THEN
         CALL CATHEADER (STATUS)

      ELSE IF (ACTION .EQ. 'CATPAIR') THEN
         CALL CATPAIR (STATUS)

      ELSE IF (ACTION .EQ. 'CATPHOTOMFIT') THEN
         CALL CATPHOTOMFIT (STATUS)

      ELSE IF (ACTION .EQ. 'CATPHOTOMLST') THEN
         CALL CATPHOTOMLST (STATUS)

      ELSE IF (ACTION .EQ. 'CATPHOTOMTRN') THEN
         CALL CATPHOTOMTRN (STATUS)

      ELSE IF (ACTION .EQ. 'CATSELECT') THEN
         CALL CATSELECT (STATUS)

      ELSE IF (ACTION .EQ. 'CATSORT') THEN
         CALL CATSORT (STATUS)

      ELSE
         CALL MSG_SETC ('ACTION', ACTION)
         CALL MSG_OUT (' ', 'Unknown command: ^ACTION.', STATUS )
      END IF

      END
