*-----------------------------------------------------------------------
*        Doppler.inc
*        --- include file for doppler corrections etc
*-----------------------------------------------------------------------

      DOUBLE PRECISION OSCFREQ
      DOUBLE PRECISION DOPPFAC

      COMMON /DOPPLER/ OSCFREQ, DOPPFAC
      SAVE   /DOPPLER/

*-----------------------------------------------------------------------
