*-------------------------------------------------
*      SPECX_PARS.INC
*  Include file to define array sizes for SPECX
*-------------------------------------------------

      INTEGER    LHEAD        ! Length of scan header (I*4 words)
      PARAMETER (LHEAD=128)

      INTEGER    NQMAX        ! Maximum number of receivers (quadrants)
      PARAMETER (NQMAX=8)

      INTEGER    LSPMAX       ! Maximum number of data points in a spectrum
      PARAMETER (LSPMAX=4096)

