      SUBROUTINE CALCFX(N,X,F,IBUG)
      COMMON/DAT1/FL,W,WS,WV,NF
      COMMON/DAT2/A,B,P,S,FLX,INDX,IREL,LP,NL,IAB
      COMMON/DAT5/NDIM,NDI2,NPAR,NUMFIT,NCUR,MAXFC
      COMMON/DEBUG/NY
      DIMENSION FL(1000),W(1000),X(40),INDX(80),IREL(80),LP(20)
      DIMENSION B(80),A(80),P(10),FLX(20)
      NDI3=3*NDIM
      F=0.
      CALL ELFSET(X,NINV)
      DO 40 IF=1,NF
      FOB=0.
      IF(NPAR.EQ.0) GO TO 25
      XX=1.
      DO 20 I=1,NPAR
      FOB=FOB+XX*P(I)
   20 XX=XX*(W(IF)-WS)
   25 IF(NL.GT.0) THEN
       DO 30 J=1,NL
       FOB=FOB+B(NDI2+J)*ELFG(W(IF),B(J),B(NDIM+J),B(NDI3+J))
   30  CONTINUE
      ENDIF
      F=F+(FOB-FL(IF))**2
   40 CONTINUE
      IF(NY.GT.0) WRITE(6,102) F
  102 FORMAT('   Function value is',E15.5)
      RETURN
      END
