      SUBROUTINE CPAIR(XSTART,YSTART,XEND,YEND)
      REAL XSTART, XEND, YSTART, YEND
      INTEGER HITVAL
      LOGICAL FIRSTCURSOR
      COMMON /SETCURSOR/XCURSOR, YCURSOR
      COMMON /DIVFACTOR/ DIVX,DIVY
       FIRSTCURSOR=.TRUE.
       CALL SGSCURSE(HITVAL,XEND,YEND,FIRSTCURSOR)
       FIRSTCURSOR=.FALSE.
       CALL SGS_SETCU(XEND,YEND)
       XSTART=XEND
       YSTART=YEND
       CALL SGSCURSE(HITVAL,XEND,YEND,FIRSTCURSOR)
      END
