      SUBROUTINE DELA(BTS,PTS,HH,JV,JJ,IND)
      COMMON/DAT2/A,B,P,S,FLX,INDX,IREL,LP,NL,IAB
      COMMON/DAT5/NDIM,NDI2,NPAR,NUMFIT,NCUR,MAXFC
      DIMENSION A(80),B(80),P(10),FLX(20),INDX(80),IREL(80),LP(20),
     .          BTS(80),PTS(10)
      IF(JV.LE.NPAR) THEN
       HH=1.E-2*P(JV)*IND
       PTS(JV)=PTS(JV)+HH
      ELSE
       ND1=JJ/NDIM
       LN=JJ-ND1*NDIM
       IF(ND1.EQ.0) HH=1.E-3*B(NDIM+LN)*100/B(NDI2+LN)*IND
       IF(ND1.NE.0) HH=1.E-2*B(JJ)*IND
       BTS(JJ)=B(JJ)+HH
       CALL ELFDEP(BTS,JJ)
      ENDIF
      RETURN
      END
