       FUNCTION ELFPAREA(N)
       COMMON/DAT4/XV,FXV,ARP,WVF,CFLX,IXV,NXV,NPROF
       COMMON/DAT4A/ITXT
       COMMON/DEBUG/NY
       DIMENSION XV(5,1000),FXV(5,1000),ARP(5),IXV(5),NXV(5),ITXT(5)
       DIMENSION WVF(5),CFLX(5)
       CHARACTER*40 ITXT
       NP=NXV(N)
       XVMIN=XV(N,1)
       XVMAX=XV(N,NP)
       IF(NY.GT.0) WRITE(6,100) NP,XVMIN,XVMAX
  100 FORMAT(1X,'PAREA, NP,XVMIN,XVMAX',I5,2F10.4)
       NQ=3*NP-1
       H=(XVMAX-XVMIN)/NQ
       X=XVMIN
       S=ELFPNT(N,XVMIN,IFAIL)
       S=S+ELFPNT(N,XVMAX,IFAIL)
       NQ=NQ-1
       DO I=1,NQ
       X=X+H
       S=S+2*ELFPNT(N,X,IFAIL)
       ENDDO
       ELFPAREA=S*H/2
       RETURN
       END
