      SUBROUTINE ELFVAR(I1,I2,KARD,K1,IF)

C   IDENTIFIES A VARIABLE, STARTING IN COLUMN K1, TERMINATED BY A
C   BLANK, A . OR AN OPERATOR.
C   I1 IS VARIABLE CODE (1,2 OR 3)
C   I2 IS VARIABLE NUMBER.
C   THE MAXIMUM VALUE OF I2 IS 99

      INCLUDE 'KARS_COM'  ! Declares common block /KARS/ holding KAR

      DIMENSION KARD(80)
      I2=0
      IF=0
      CALL ELFKJ(KARD(K1),IT,IN,IK)
      IF(IT.NE.2) GO TO 10
      I1=(IN+1)/2
      K1=K1+1
      CALL ELFKJ(KARD(K1),IT,IN,IK)
      IF(IT.EQ.4) GO TO 15
      IF(IT.NE.3) GO TO 10
      I2=IN-1
   20 K1=K1+1
      CALL ELFKJ(KARD(K1),IT,IN,IK)
      IF(IT.EQ.4) GO TO 15
      IF(IT.NE.3) GO TO 10
      I2=10*I2+IN-1
      GO TO 20
   10 IF=1
   15 RETURN
      END
