      SUBROUTINE FLFIX(IL)
      COMMON/DAT2/A,B,P,S,FLX,INDX,IREL,LP,NL,IAB
      COMMON/DAT5/NDIM,NDI2,NPAR,NUMFIT,NCUR,MAXFC
      COMMON/DAT3/FLMAX
      DIMENSION A(80),B(80),P(10),FLX(20)
      DIMENSION INDX(80),IREL(80),LP(20)
      LOGICAL FIRSTCURSOR
      FIRSTCURSOR = .TRUE.
      NDI2=2*NDIM
      NDI3=3*NDIM
      CALL SGSCURSE(I,XC,YC, FIRSTCURSOR)
      FIRSTCURSOR = .FALSE.
      INDX(IL)=2
      A(IL)=XC
      INDX(IL+NDI2)=2
      A(IL+NDI2)=100*YC/FLMAX
      INDX(IL+NDI3)=2
      A(IL+NDI3)=1.
C
C  SECTION TO MARK LINE AND NUMBER IT
      R=IL
      XX=XC
      YY=YC
      HYT = 1.0
      YN=YY+6*HYT
      CALL POINTSYM(XX,YN,3)
      YN=YN-2*HYT
      CALL LINE(XX,YN,XX,YY)
      CALL SGSCURSE(I,XC1,YC1,FIRSTCURSOR)
      IF(XC1.NE.XC.OR.YC1.NE.YC) THEN
        XC=2*ABS(XC-XC1)
        INDX(NDIM+IL)=2
        A(NDIM+IL)=XC
      ENDIF
      CALL PLOTIT( 0, 0, 2 )
      CALL SGS_FLUSH
      RETURN
      END
