      BLOCK DATA IS_BLK

      LOGICAL OPTCAL
      LOGICAL OPTOK

      INTEGER BLEND
      INTEGER MODE
      INTEGER CONV
      INTEGER SAVE
      INTEGER VEL

      REAL COLUMN
      REAL QUART
      REAL SCALE
      REAL THE
      REAL V1
      REAL V2
      REAL C

      COMMON /DMISOPT/ OPTCAL, OPTOK, BLEND, COLUMN, QUART, SCALE,
     :                 MODE, CONV, THE, SAVE, VEL, V1, V2
      COMMON /MAD1  / DELTA, C, WAVE0, CONST, WAVE1, AK1, F1K

      DATA C/2.997925E+05/
      DATA OPTCAL, OPTOK/.FALSE., .TRUE./

      END
