       SUBROUTINE LBLRUN
     : (WORKSZ, STKSZE, MAXSTK, NONSTK, BSTSZE,
     : XSTACK, YSTACK,
     : BSTACK, BSTNPT,
     : POINTR, STKNPT,
     : BPOINT,
     : STITLE,
     : FVALS,
     : PARAMS,
     : DEVTYP,
     : SUBCHK)
!
!
!
       IMPLICIT NONE
       REAL XKSCANDW, XKSCANWV
!
!    IMPORTS
!
       INTEGER WORKSZ, STKSZE, MAXSTK, NONSTK, BSTSZE
       INTEGER BSTACK(BSTSZE)
       INTEGER BSTNPT(MAXSTK)
       INTEGER POINTR(MAXSTK)
       INTEGER STKNPT(MAXSTK)
       INTEGER BPOINT(MAXSTK)
       INTEGER DEVTYP, DEVNOW
!
       REAL XSTACK(STKSZE)
       REAL YSTACK(STKSZE)
!
       CHARACTER*(*) PARAMS
       CHARACTER*80  STITLE(MAXSTK)
!
       LOGICAL SUBCHK
!
!    LOCAL VARIABLES
!
       INTEGER MAXU, MAXV, FD
       PARAMETER (MAXU=55, MAXV=1200, FD=15)
!
       INTEGER I, J, K, L, M, N
       INTEGER LNUM
       INTEGER IPRMPT
       INTEGER IHX
       INTEGER NU, NV, STATUS
       INTEGER LLNGTH, MLNGTH
       INTEGER NTERMS
       INTEGER XLABLN, YLABLN, KEEPYN, KEEPXN
       INTEGER IPAL(2)
       INTEGER NSPEC
       INTEGER BCK1, BCK2
       INTEGER NSM, NSIG, NITER
       INTEGER SLEN
!
       REAL US(MAXU)
       REAL VS(MAXV)
       REAL FVALS(MAXU,WORKSZ/MAXU)
       REAL XV, YV, XVS(10), YVS(10), XTEMP, YTEMP
       REAL UU, UV, UFN
       REAL TEMP
       REAL RPAL(2)
       REAL SCANWV, SCANDW, W1, W2
       REAL VSUM(MAXU)
       INTEGER VQVALS(MAXU)
       REAL A(12)
       REAL SIGMAA(12,12)
       REAL TST1, TST2
       REAL YCALC(MAXU)
       REAL XBAR(4), LYA1, LYA2
!
       CHARACTER*60 XLAB, YLAB
       CHARACTER*80 TITLE
       CHARACTER*80 OBJECT
       CHARACTER*20
     : DLABEL, DUNITS,
     : ULABEL, UUNITS,
     : VLABEL, VUNITS
       CHARACTER*10 USERID
!
       INTEGER QVALS(MAXU,MAXV)
       BYTE QBYTE(MAXU,MAXV)
!
       LOGICAL OK
       LOGICAL SWP
!
!
!
!
!
!
       OK = .FALSE.

       WRITE (*,
     : '(''   LBLFIT not implemented in this version of DIPSO'',A)')7

       END
