      SUBROUTINE RANGE(DBMIN,AUTMIN,SETMIN,DBMAX,AUTMAX,SETMAX)
      LOGICAL AUTMIN, AUTMAX
      REAL DBMIN, DBMAX, SETMIN, SETMAX
      IF ( AUTMIN ) THEN
        IF ( AUTMAX ) THEN
          SETMIN=DBMIN
          SETMAX=DBMAX
        ELSE IF ( SETMAX.GE.DBMIN ) THEN
          SETMIN=DBMIN
        ELSE
          SETMIN=SETMAX
        END IF
      ELSE IF ( AUTMAX ) THEN
        IF ( SETMIN.LE.DBMAX ) THEN
          SETMAX=DBMAX
        ELSE
          SETMAX=SETMIN
        END IF
      END IF
      END
