      SUBROUTINE  SGSCURSE(HITVAL,X,Y,FIRSTCURSOR)
      INTEGER HITVAL
      LOGICAL FIRSTCURSOR
      COMMON /SETCURSOR/XCURSOR, YCURSOR
      COMMON /DIVFACTOR/DIVX,DIVY
      CALL SNX_TO('SGS')
      CALL SNX_AGCS
      CALL SGS_CUVIS(.TRUE.)
      IF(FIRSTCURSOR)CALL SGS_SETCU(XCURSOR,YCURSOR)
      CALL SGS_SELCH(0)
      CALL SGS_DEFCH('12 .')
      CALL SGS_REQCU(X,Y,HITVAL)
      X=SNX_AGGUX(X)*DIVX
      Y=SNX_AGGUY(Y)*DIVY
      CALL SNX_TO('NCAR')

      END
