#!/bin/sh 

#  Setup all the necessary softlinks to develop GAIA from library/.

(cd library;
ln -s ../bin/gaia_wish ./gaia_wish
ln -s ../bin/gaia_tcl ./gaia_tcl
ln -s ../bin/gaiaMon ./ardstat
ln -s ../bin/gaiaMon ./autocrop
ln -s ../bin/gaiaMon ./cat2tab
ln -s ../bin/gaiaMon ./tab2asc
ln -s ../bin/gaiaMon ./tab2cat
ln -s ../../demodata.tar ./demodata.tar
)
