#!/usr/local/bin/perl

# This is a reimplementation of the gsdprint command
# using Perl rather than C or Fortran.
# The C version forms part of the GSD C library distribution.
# This version is much more compact.

# History:
#  April 1996 (TIMJ)
#    Original version
#  2000 May 12 (TIMJ)
#    Use modern perl and the new OO interfacce
#  2000 May 15 (TIMJ)
#    Merge with GSDFORMAT
#  2000 May 16 (TIMJ)
#    Add PDL option

# Load in the GSD module
use GSD qw//;
use Term::ReadLine;
use Getopt::Long;
use Pod::Usage;

use strict;

# Globals required for FORMAT
use vars qw/ $JCMTNAME $JCMTCMT $NEWDATA $UNIT /;

# Version number
my $VERSION = '1.02';


# Read the options
my $man = 0;
my $help = 0;
my $version = 0;
my $printdata = 0;
my $noread = 0;
my $noarray = 0;
my $list = 0;
my $formatted = 0;
my $pdl = 0;

# Parse options
GetOptions('help|?' => \$help, man => \$man, noread => \$noread, 
	   'data' => \$printdata, 'version' => \$version,
	   'noarray' => \$noarray, 'list' => \$list,
	   'formatted' => \$formatted, 'pdl' => \$pdl ) 
  or pod2usage(2);

pod2usage(1) if $help;
pod2usage(-verbose => 2) if $man;


# Version
($version) && do {
  my $isfmt = ( $formatted ? 'formatted' : 'unformatted');
  print "JCMT GSD file lister [$isfmt] ($0) version $VERSION\n";
  print "Use the -h option for more information\n";
    exit;
};

# If we are using the PDL interface
my $gsdclass = 'GSD';
if ($pdl) {
  require GSD::PDL;
  $gsdclass = 'GSD::PDL';
}


# Check if we are called gsdformat
$formatted = 1 if $0 =~ /gsdformat/;

# Need to read in the formatting info if required
my (%jcmtname,%jcmtcomment);
rdgsdinfo(\%jcmtname, \%jcmtcomment) if ($formatted || $list);

# If -list is turned on we are instructed to simply print out
# the mapping of GSD NRAO item name to JCMT name
if ($list) {
  foreach my $key (sort keys %jcmtname) {
    $jcmtcomment{$key} = '' unless exists $jcmtcomment{$key};
    printf "%-15s %-20s %s\n", $key, $jcmtname{$key}, $jcmtcomment{$key};
  }
  exit;
}


# Read the argument if there is one

my $filename;
if (@ARGV) {
  $filename = shift;
} else {
  my $term = new Term::ReadLine 'gsdprint' unless ($noread);
  my $prompt = "Which GSD file to list : ";
  ($noread) && do {print $prompt; chomp($filename = <>)} ||
    ($filename = $term->readline($prompt));
}

# Explicitly test for the existence of the filename
# before trying to open it. This is not really necessary apart
# from allowing us to distinguish error states 

die "$!: $filename does not exist\n" 
  unless ((-e "$filename") ||
	  (-e "$filename.dat") ||
	  (-e "$filename.gsd") || 
	  (-e $ENV{'DATADIR'}."/$filename") ||
	  (-e $ENV{'DATADIR'}."/$filename.dat") ||
	  (-e $ENV{'DATADIR'}."/$filename.gsd"));


# Open the GSD file
my $gsd = new $gsdclass($filename);

die "Problem opening file. $filename may not be a GSD file\n"
  unless defined $gsd;


# Print an informative header
print "-"x78,"\n";
if ($formatted) {
  print " G S D    F O R M A T\n";
} else {
  print " G S D    P R I N T\n";
}
print "-"x78,"\n";
print "\n";
print  " Filename        : $filename\n";
printf " GSD version     : %5.3f\n", $gsd->version;
print  " Label           : ", $gsd->label, "\n";
print  " Number of items : ", $gsd->nitems, "\n";
print  "\n\n\n";
if ($formatted) {
  print " Name\t\t\t\t\t  Unit\t\tComment\n";
} else {
  print  "Name\t\tUnit\t\tType\tArr?\tValue\n";
}

print  "-"x78,"\n";

# Find the item number related to the C13DAT field
my $C13DATitemno = $gsd->Find( 'C13DAT' );

# Loop over each item
for my $i (1.. $gsd->nitems) {

  my ($name, $type, $array);
  ($name, $UNIT, $type, $array) = $gsd->Item($i);
  next if ($array && $noarray);

  # Get the translation to JCMT name
  $JCMTNAME = ( exists $jcmtname{$name} ? $jcmtname{$name} : $name);
  $JCMTCMT  = ( exists $jcmtcomment{$name} ? $jcmtcomment{$name} : '');

  
  print "-"x78,"\n" if ($array);    
  printf "%-16s%-16s$type\t$array\t", $name, $UNIT 
    unless $formatted;

  if ($array) {

    # Find out how big it is
    my ($dimnm, $dimunt, $dimvals, $size) = $gsd->InqSize($i);

    # If we are formatted use the WRITE, else just print the size
    $NEWDATA = "Array size= $size";
    if ($formatted) {
      write STDOUT;
    } else {
      print $NEWDATA,"\n";
    }
	
    # Now get the data
    my @values = $gsd->GetByNum($i);

    # Write the array definition - looping over each dimension
    for my $j (0..$#$dimvals) {
      printf("  > %s: %d\t%s\n", $dimnm->[$j], $dimvals->[$j], $dimunt->[$j]);
    }

    # Write the data - skipping if this is the last item
    # unless $printdata is true
    if (($i != $C13DATitemno) || $printdata)  {
      print "  Data:\n";

      # Print the data in blocks of 4 if we are not using PDL interface
      if ($pdl) {
	print $values[0],"\n";
      } else {
	for my $j (0..$#values) {
	  if ($type =~ /C/i) {
	    printf "%20s ",$values[$j];
	  } else {
	    printf "%15g",$values[$j];
	  }
	  print "\n" unless ((1+$j)%4);
	}
	print "\n" if (scalar(@values)%4);
      }
    }


    } else {

      $NEWDATA = $gsd->GetByNum($i);
      if ($formatted) {
	# Translate hours and minutes to sexagesimal
	if ($UNIT =~ /HOUR/i) {
	  $NEWDATA = todeg( $NEWDATA, 0);
	} elsif ($UNIT =~ /DEGREE/i) {
	  my $dohour = 0;
	  if ($JCMTNAME =~ /RA/i) {
	    $UNIT = 'HOUR';
	    $dohour = 1;
	  }
	  $NEWDATA = todeg($NEWDATA, $dohour);
	}
	write STDOUT;
      } else {
	print "$NEWDATA\n";	
      }

    }

}

print "-"x78,"\n";

exit;

# Routine to read the standard storage task include file
# and translate NRAO GSD item name to JCMT item names

# Parse the include file each time for compatibility with
# changes to the actual storage task.

# Expect two hash refs as arguments

sub rdgsdinfo ($$) {

  my ($jcmtname, $jcmtcomment) = @_;

  # Read information from the DATA filehandle
  my $key;
  while (<DATA>) {
        /NRAO_NAME/ && do {
            /'(.+)'/ && do {
                $key = uc($1);
                $key =~ s/\s+$//g;
            };
	    next;
        };
        /JCMT_NAME/ && do {
            /'(.+)'/ && do {
                my $jcmt = uc($1);
                $jcmt =~ s/\s+$//g;
                $jcmtname{$key} = $jcmt;
            };
	    next;
        };
        /JCMT_COMMENT/ && do {
            /'(.+)'/ && do {
                my $cmt = $1;
                $cmt =~ s/\s+$//g;
                $jcmtcomment{$key} = $cmt;
            };
        };
    }

}

# convert decimal degrees to dms

sub todeg {
    my ($decimal,$hr) = @_;
    $decimal /= 15 if $hr;

    my $minus = ( $decimal < 0 ? 1 : 0);
    my $degree = abs(int($decimal));
    my $minute = (abs($decimal)-$degree)*60;
    my $second = ($minute - int($minute))*60;
    $minute = int($minute);
    $degree *= -1 if $minus;

    return(sprintf("%3g %2g %5.2f",$degree,$minute,$second));
}


# Scalar format since we would rather Perl did the word wrapping for us

format STDOUT = 
 @<<<<<<<<<<<<<<<<< @>>>>>>>>>>>>>>>>>>>  @<<<<<<<<<<< ^<<<<<<<<<<<<<<<<<<<<<<<
$JCMTNAME, $NEWDATA, $UNIT,                            $JCMTCMT
~~                                                     ^<<<<<<<<<<<<<<<<<<<<<<<
                                                       $JCMTCMT
.


__END__

=head1 NAME

gsdprint/gsdformat - Print the contents of a GSD file to standard output

=head1 SYNOPSIS

  gsdprint obs_das_0141.dat
  gsdprint -data obs_das_0141
  gsdprint -formatted test.gsd

  gsdformat -list
  gsdformat test.gsd

  gsdprint

  gsdprint -v
  gsdprint -man

=head1 DESCRIPTION

This command prints the contents of the GSD file to the screen
with some formatting. By default the data component C<C13DAT>
is not printed since this can be very large (the B<-data> option
will print the data as well as the header). A formatted output
can be requested with the C<-formatted> flag. This behaviour is
the default if the program is invoked by the name C<gsdformat>.

A prompt will be issued if no filename is given.

=head1 OPTIONS

=over 4

=item B<-help>

Print a brief help message and exits.

=item B<-man>

Prints the manual page and exits.

=item B<-data>

Print the C<C13DAT> field as well as the header fields. 
By default the C<C13DAT> field is omitted since it can be
very long and is usually of little interest.

=item B<-noarray>

Only list scalar items.

=item B<-noread>

Turn off readline support. Sometimes this is necessary 
if the command is run from a script or web page. Readline
support is only required when the user is prompted for input
(ie no filename supplied at the command-line). 

=item B<-list>

Print out the list of known GSD item names along with the 
translation to JCMT name and a short description of the
item. Program exits immediately afterwards.

=item B<-pdl>

Use the PDL interface to print the data values. This will
allow the dimensionality of the data to be retained when
printing but will generate badly formatted output for extremely
large arrays.

=item B<-formatted>

Print out a formatted list of items where the JCMT name
and a short description of the item are displayed. By default
the actual GSD item name is displayed along with the item data 
type. This option is invoked automatically if the program is
called C<gsdformat>.

=back

=head1 AUTHOR

Tim Jenness E<lt>t.jenness@jach.hawaii.eduE<gt>

Copyright (C) 1996-2000 Tim Jenness and the UK Particle Physics and
Astronomy Research Council. All Rights Reserved.

=cut

# We append the include file used by the JCMT ADAM storage task
# This provides the definitive translation from GSD item name
# to JCMT name

__DATA__
*     STORAGE_TRANSLATE_FULL   5.3

      INTEGER MAX__TRANSLATE
      PARAMETER (MAX__TRANSLATE =287)
      CHARACTER*15 NRAO_NAME(MAX__TRANSLATE)
      CHARACTER*15 JCMT_NAME(MAX__TRANSLATE)
      CHARACTER*80 JCMT_COMMENT(MAX__TRANSLATE)
      CHARACTER*8 FITS_TYPE(MAX__TRANSLATE)
      CHARACTER*8 FITS_NAME(MAX__TRANSLATE)
*
      DATA NRAO_NAME   (  1)/'C1TEL          '/
      DATA JCMT_NAME   (  1)/'TEL_NAME       '/
      DATA JCMT_COMMENT(  1)/'Telescope name                                                                  '/
      DATA FITS_TYPE   (  1)/'GENERAL '/
      DATA FITS_NAME   (  1)/'TELESCOP'/
*
      DATA NRAO_NAME   (  2)/'C1PID          '/
      DATA JCMT_NAME   (  2)/'PROJECT        '/
      DATA JCMT_COMMENT(  2)/'Identifies the observing program                                                '/
      DATA FITS_TYPE   (  2)/'GENERAL '/
      DATA FITS_NAME   (  2)/'PROJID  '/
*
      DATA NRAO_NAME   (  3)/'C1OBS          '/
      DATA JCMT_NAME   (  3)/'PROJECT_OBS_1  '/
      DATA JCMT_COMMENT(  3)/'Name of the primary observer                                                    '/
      DATA FITS_TYPE   (  3)/'GENERAL '/
      DATA FITS_NAME   (  3)/'OBSID   '/
*
      DATA NRAO_NAME   (  4)/'C1ONA1         '/
      DATA JCMT_NAME   (  4)/'PROJECT_OBS_2  '/
      DATA JCMT_COMMENT(  4)/'Name of the support scientist                                                   '/
      DATA FITS_TYPE   (  4)/'GENERAL '/
      DATA FITS_NAME   (  4)/'OBSERVER'/
*
      DATA NRAO_NAME   (  5)/'C1ONA2         '/
      DATA JCMT_NAME   (  5)/'PROJECT_OBS_3  '/
      DATA JCMT_COMMENT(  5)/'Name of the telescope operator                                                  '/
      DATA FITS_TYPE   (  5)/'JCMT    '/
      DATA FITS_NAME   (  5)/'OPERATOR'/
*
      DATA NRAO_NAME   (  6)/'C1SNA1         '/
      DATA JCMT_NAME   (  6)/'CENTRE_NAME_1  '/
      DATA JCMT_COMMENT(  6)/'Source name part 1                                                              '/
      DATA FITS_TYPE   (  6)/'GENERAL '/
      DATA FITS_NAME   (  6)/'OBJECT  '/
*
      DATA NRAO_NAME   (  7)/'C1SNA2         '/
      DATA JCMT_NAME   (  7)/'CENTRE_NAME_2  '/
      DATA JCMT_COMMENT(  7)/'Source name part 2 or altern. name                                              '/
      DATA FITS_TYPE   (  7)/'JCMT    '/
      DATA FITS_NAME   (  7)/'OBJECT2 '/
*
      DATA NRAO_NAME   (  8)/'C4CSC          '/
      DATA JCMT_NAME   (  8)/'CENTRE_COORDS  '/
      DATA JCMT_COMMENT(  8)/'Character code of commanded centre or source coordinate system                  '/
      DATA FITS_TYPE   (  8)/'GENERAL '/
      DATA FITS_NAME   (  8)/'COORDCD '/
*
      DATA NRAO_NAME   (  9)/'c4ceco         '/
      DATA JCMT_NAME   (  9)/'CENTRE_CODE    '/
      DATA JCMT_COMMENT(  9)/'centre coords. AZ= 1;EQ=3;RD=4;RB=6;RJ=7;GA=8                                   '/
      DATA FITS_TYPE   (  9)/'JCMT    '/
      DATA FITS_NAME   (  9)/'COORDCD2'/
*
      DATA NRAO_NAME   ( 10)/'c4ept          '/
      DATA JCMT_NAME   ( 10)/'EPOCH_TYPE     '/
      DATA JCMT_COMMENT( 10)/'Type of epoch, JULIAN, BESSELIAN or APPARENT                                    '/
      DATA FITS_TYPE   ( 10)/'JCMT    '/
      DATA FITS_NAME   ( 10)/'EPOCHTYP'/
*
      DATA NRAO_NAME   ( 11)/'c4mcf          '/
      DATA JCMT_NAME   ( 11)/'CENTRE_MOVING  '/
      DATA JCMT_COMMENT( 11)/'Centre moving flag (solar system object)                                        '/
      DATA FITS_TYPE   ( 11)/'JCMT    '/
      DATA FITS_NAME   ( 11)/'CENMOVE '/
*
      DATA NRAO_NAME   ( 12)/'C4EPH          '/
      DATA JCMT_NAME   ( 12)/'CENTRE_EPOCH   '/
      DATA JCMT_COMMENT( 12)/'Date of the RA/DEC coordinates (1950)                                           '/
      DATA FITS_TYPE   ( 12)/'GENERAL '/
      DATA FITS_NAME   ( 12)/'EPOCH   '/
*
      DATA NRAO_NAME   ( 13)/'C4ERA          '/
      DATA JCMT_NAME   ( 13)/'CENTRE_RA1950  '/
      DATA JCMT_COMMENT( 13)/'Right ascension of source for EPOCH                                             '/
      DATA FITS_TYPE   ( 13)/'GENERAL '/
      DATA FITS_NAME   ( 13)/'EPOCRA  '/
*
      DATA NRAO_NAME   ( 14)/'C4EDEC         '/
      DATA JCMT_NAME   ( 14)/'CENTRE_DEC1950 '/
      DATA JCMT_COMMENT( 14)/'Declination of source for EPOCH                                                 '/
      DATA FITS_TYPE   ( 14)/'GENERAL '/
      DATA FITS_NAME   ( 14)/'EPOCDEC '/
*
      DATA NRAO_NAME   ( 15)/'c4radate       '/
      DATA JCMT_NAME   ( 15)/'CENTRE_RA      '/
      DATA JCMT_COMMENT( 15)/'Right Ascension of date                                                         '/
      DATA FITS_TYPE   ( 15)/'JCMT    '/
      DATA FITS_NAME   ( 15)/'RADATE  '/
*
      DATA NRAO_NAME   ( 16)/'c4decdate      '/
      DATA JCMT_NAME   ( 16)/'CENTRE_DEC     '/
      DATA JCMT_COMMENT( 16)/'Declination of date                                                             '/
      DATA FITS_TYPE   ( 16)/'JCMT    '/
      DATA FITS_NAME   ( 16)/'DECDATE '/
*
      DATA NRAO_NAME   ( 17)/'c4ra2000       '/
      DATA JCMT_NAME   ( 17)/'CENTRE_RA2000  '/
      DATA JCMT_COMMENT( 17)/'Right ascension J2000                                                           '/
      DATA FITS_TYPE   ( 17)/'JCMT    '/
      DATA FITS_NAME   ( 17)/'RAJ2000 '/
*
      DATA NRAO_NAME   ( 18)/'c4edec2000     '/
      DATA JCMT_NAME   ( 18)/'CENTRE_DEC2000 '/
      DATA JCMT_COMMENT( 18)/'Declination J2000                                                               '/
      DATA FITS_TYPE   ( 18)/'JCMT    '/
      DATA FITS_NAME   ( 18)/'DECJ2000'/
*
      DATA NRAO_NAME   ( 19)/'C4GL           '/
      DATA JCMT_NAME   ( 19)/'CENTRE_GL      '/
      DATA JCMT_COMMENT( 19)/'Galactic longitude                                                              '/
      DATA FITS_TYPE   ( 19)/'GENERAL '/
      DATA FITS_NAME   ( 19)/'GALLONG '/
*
      DATA NRAO_NAME   ( 20)/'C4GB           '/
      DATA JCMT_NAME   ( 20)/'CENTRE_GB      '/
      DATA JCMT_COMMENT( 20)/'Galactic latitude                                                               '/
      DATA FITS_TYPE   ( 20)/'GENERAL '/
      DATA FITS_NAME   ( 20)/'GALLAT  '/
*
      DATA NRAO_NAME   ( 21)/'C4AZ           '/
      DATA JCMT_NAME   ( 21)/'CENTRE_AZ      '/
      DATA JCMT_COMMENT( 21)/'Azimuth at observation date                                                     '/
      DATA FITS_TYPE   ( 21)/'GENERAL '/
      DATA FITS_NAME   ( 21)/'AZ      '/
*
      DATA NRAO_NAME   ( 22)/'C4EL           '/
      DATA JCMT_NAME   ( 22)/'CENTRE_EL      '/
      DATA JCMT_COMMENT( 22)/'Elevation at observation date                                                   '/
      DATA FITS_TYPE   ( 22)/'GENERAL '/
      DATA FITS_NAME   ( 22)/'EL      '/
*
      DATA NRAO_NAME   ( 23)/'c4lsc          '/
      DATA JCMT_NAME   ( 23)/'CELL_COORDS    '/
      DATA JCMT_COMMENT( 23)/'Char. code for local x-y coord.system                                           '/
      DATA FITS_TYPE   ( 23)/'GENERAL '/
      DATA FITS_NAME   ( 23)/'FRAME   '/
*
      DATA NRAO_NAME   ( 24)/'C6FC           '/
      DATA JCMT_NAME   ( 24)/'CELL_CODE      '/
      DATA JCMT_COMMENT( 24)/'Local x-y AZ= 1;EQ=3;RD=4;RB=6;RJ=7;GA=8                                        '/
      DATA FITS_TYPE   ( 24)/'JCMT    '/
      DATA FITS_NAME   ( 24)/'FRAME2  '/
*
      DATA NRAO_NAME   ( 25)/'c4odco         '/
      DATA JCMT_NAME   ( 25)/'CELL_UNIT      '/
      DATA JCMT_COMMENT( 25)/'Units of cell and mapping coordinates;offset definition code                    '/
      DATA FITS_TYPE   ( 25)/'JCMT    '/
      DATA FITS_NAME   ( 25)/'MAPUNIT '/
*
      DATA NRAO_NAME   ( 26)/'C6DX           '/
      DATA JCMT_NAME   ( 26)/'CELL_X         '/
      DATA JCMT_COMMENT( 26)/'Cell x dim,; descriptive origin item 1                                          '/
      DATA FITS_TYPE   ( 26)/'GENERAL '/
      DATA FITS_NAME   ( 26)/'DELTAX  '/
*
      DATA NRAO_NAME   ( 27)/'C6DY           '/
      DATA JCMT_NAME   ( 27)/'CELL_Y         '/
      DATA JCMT_COMMENT( 27)/'Cell y dimension; descriptive origin item 2                                     '/
      DATA FITS_TYPE   ( 27)/'GENERAL '/
      DATA FITS_NAME   ( 27)/'DELTAY  '/
*
      DATA NRAO_NAME   ( 28)/'C6MSA          '/
      DATA JCMT_NAME   ( 28)/'CELL_V2X       '/
      DATA JCMT_COMMENT( 28)/'Scanning angle - angle from local vertical to x axis measured CW                '/
      DATA FITS_TYPE   ( 28)/'GENERAL '/
      DATA FITS_NAME   ( 28)/'SCANANG '/
*
      DATA NRAO_NAME   ( 29)/'CELL_V2Y       '/
      DATA JCMT_NAME   ( 29)/'CELL_V2Y       '/
      DATA JCMT_COMMENT( 29)/'Position angle of cell y axis (CCW)                                             '/
      DATA FITS_TYPE   ( 29)/'JCMT    '/
      DATA FITS_NAME   ( 29)/'YPOSANG '/
*
      DATA NRAO_NAME   ( 30)/'c4axy          '/
      DATA JCMT_NAME   ( 30)/'CELL_X2Y       '/
      DATA JCMT_COMMENT( 30)/'Angle between cell y axis and x-axis (CCW)                                      '/
      DATA FITS_TYPE   ( 30)/'JCMT    '/
      DATA FITS_NAME   ( 30)/'XYANGLE '/
*
      DATA NRAO_NAME   ( 31)/'C4SX           '/
      DATA JCMT_NAME   ( 31)/'CENTRE_OFFSET_X'/
      DATA JCMT_COMMENT( 31)/'Commanded x centre position (JCMT cells wrt to centre; NRAO abs. degrees)       '/
      DATA FITS_TYPE   ( 31)/'JCMT    '/
      DATA FITS_NAME   ( 31)/'XSOURCE '/
*
      DATA NRAO_NAME   ( 32)/'C4SY           '/
      DATA JCMT_NAME   ( 32)/'CENTRE_OFFSET_Y'/
      DATA JCMT_COMMENT( 32)/'Commanded y centre position (JCMT cells wrt to centre; NRAO abs. degrees)       '/
      DATA FITS_TYPE   ( 32)/'JCMT    '/
      DATA FITS_NAME   ( 32)/'YSOURCE '/
*
      DATA NRAO_NAME   ( 33)/'C4RX           '/
      DATA JCMT_NAME   ( 33)/'REFERENCE_X    '/
      DATA JCMT_COMMENT( 33)/'Reference x position (JCMT cells wrt to centre; NRAO abs. degrees)              '/
      DATA FITS_TYPE   ( 33)/'JCMT    '/
      DATA FITS_NAME   ( 33)/'XREF    '/
*
      DATA NRAO_NAME   ( 34)/'C4RY           '/
      DATA JCMT_NAME   ( 34)/'REFERENCE_Y    '/
      DATA JCMT_COMMENT( 34)/'Reference y position (JCMT cells wrt to centre; NRAO abs. degrees)              '/
      DATA FITS_TYPE   ( 34)/'JCMT    '/
      DATA FITS_NAME   ( 34)/'YREF    '/
*
      DATA NRAO_NAME   ( 35)/'c1hgt          '/
      DATA JCMT_NAME   ( 35)/'TEL_HEIGHT     '/
      DATA JCMT_COMMENT( 35)/'Height of telescope above sea level                                             '/
      DATA FITS_TYPE   ( 35)/'JCMT    '/
      DATA FITS_NAME   ( 35)/'HEIGHT  '/
*
      DATA NRAO_NAME   ( 36)/'c1long         '/
      DATA JCMT_NAME   ( 36)/'TEL_LONGITUDE  '/
      DATA JCMT_COMMENT( 36)/'Geographical longitude of telescope (West +ve)                                  '/
      DATA FITS_TYPE   ( 36)/'JCMT    '/
      DATA FITS_NAME   ( 36)/'LONGITUD'/
*
      DATA NRAO_NAME   ( 37)/'c1lat          '/
      DATA JCMT_NAME   ( 37)/'TEL_LATITUDE   '/
      DATA JCMT_COMMENT( 37)/'Geodetic latitude of telescope (North +ve)                                      '/
      DATA FITS_TYPE   ( 37)/'JCMT    '/
      DATA FITS_NAME   ( 37)/'LATITUDE'/
*
      DATA NRAO_NAME   ( 38)/'C1SNO          '/
      DATA JCMT_NAME   ( 38)/'NOBS           '/
      DATA JCMT_COMMENT( 38)/'Observation number                                                              '/
      DATA FITS_TYPE   ( 38)/'GENERAL '/
      DATA FITS_NAME   ( 38)/'SCAN    '/
*
      DATA NRAO_NAME   ( 39)/'c6st           '/
      DATA JCMT_NAME   ( 39)/'OBS_TYPE       '/
      DATA JCMT_COMMENT( 39)/'Type of observation                                                             '/
      DATA FITS_TYPE   ( 39)/'GENERAL '/
      DATA FITS_NAME   ( 39)/'OBSMODE '/
*
      DATA NRAO_NAME   ( 40)/'C1RCV          '/
      DATA JCMT_NAME   ( 40)/'FRONTEND       '/
      DATA JCMT_COMMENT( 40)/'Name of the frontend                                                            '/
      DATA FITS_TYPE   ( 40)/'GENERAL '/
      DATA FITS_NAME   ( 40)/'FRONTEND'/
*
      DATA NRAO_NAME   ( 41)/'c1ftyp         '/
      DATA JCMT_NAME   ( 41)/'FE_TYPE        '/
      DATA JCMT_COMMENT( 41)/'Type of frontend                                                                '/
      DATA FITS_TYPE   ( 41)/'JCMT    '/
      DATA FITS_NAME   ( 41)/'FRONTYPE'/
*
      DATA NRAO_NAME   ( 42)/'C1BKE          '/
      DATA JCMT_NAME   ( 42)/'BACKEND        '/
      DATA JCMT_COMMENT( 42)/'Name of the backend                                                             '/
      DATA FITS_TYPE   ( 42)/'GENERAL '/
      DATA FITS_NAME   ( 42)/'BACKEND '/
*
      DATA NRAO_NAME   ( 43)/'c1btyp         '/
      DATA JCMT_NAME   ( 43)/'BE_TYPE        '/
      DATA JCMT_COMMENT( 43)/'Type of backend                                                                 '/
      DATA FITS_TYPE   ( 43)/'JCMT    '/
      DATA FITS_NAME   ( 43)/'BACKTYPE'/
*
      DATA NRAO_NAME   ( 44)/'C3DAT          '/
      DATA JCMT_NAME   ( 44)/'OBS_UT1D       '/
      DATA JCMT_COMMENT( 44)/'UT1 date of observation                                                         '/
      DATA FITS_TYPE   ( 44)/'GENERAL '/
      DATA FITS_NAME   ( 44)/'UTDATE  '/
*
      DATA NRAO_NAME   ( 45)/'C3UT           '/
      DATA JCMT_NAME   ( 45)/'OBS_UT1H       '/
      DATA JCMT_COMMENT( 45)/'UT1 hour of observation                                                         '/
      DATA FITS_TYPE   ( 45)/'GENERAL '/
      DATA FITS_NAME   ( 45)/'UT      '/
*
      DATA NRAO_NAME   ( 46)/'c3ut1c         '/
      DATA JCMT_NAME   ( 46)/'OBS_UT1C       '/
      DATA JCMT_COMMENT( 46)/'UT1-UTC correction interpolated from time service telex (in days)               '/
      DATA FITS_TYPE   ( 46)/'JCMT    '/
      DATA FITS_NAME   ( 46)/'UT1C    '/
*
      DATA NRAO_NAME   ( 47)/'C3LST          '/
      DATA JCMT_NAME   ( 47)/'OBS_LST        '/
      DATA JCMT_COMMENT( 47)/'Local sidereal time at the start of the observation                             '/
      DATA FITS_TYPE   ( 47)/'GENERAL '/
      DATA FITS_NAME   ( 47)/'LST     '/
*
      DATA NRAO_NAME   ( 48)/'c3cal          '/
      DATA JCMT_NAME   ( 48)/'OBS_CALIBRATION'/
      DATA JCMT_COMMENT( 48)/'Calibration observation?                                                        '/
      DATA FITS_TYPE   ( 48)/'JCMT    '/
      DATA FITS_NAME   ( 48)/'OBSCAL  '/
*
      DATA NRAO_NAME   ( 49)/'c3cen          '/
      DATA JCMT_NAME   ( 49)/'OBS_CENTRE     '/
      DATA JCMT_COMMENT( 49)/'Centre moves between scans?                                                     '/
      DATA FITS_TYPE   ( 49)/'JCMT    '/
      DATA FITS_NAME   ( 49)/'OBSCEN  '/
*
      DATA NRAO_NAME   ( 50)/'c3fly          '/
      DATA JCMT_NAME   ( 50)/'OBS_CONTINUOUS '/
      DATA JCMT_COMMENT( 50)/'Data taken on the fly or in discrete mode?                                      '/
      DATA FITS_TYPE   ( 50)/'JCMT    '/
      DATA FITS_NAME   ( 50)/'OBSFLY  '/
*
      DATA NRAO_NAME   ( 51)/'c3focus        '/
      DATA JCMT_NAME   ( 51)/'OBS_FOCUS      '/
      DATA JCMT_COMMENT( 51)/'Focus observation?                                                              '/
      DATA FITS_TYPE   ( 51)/'JCMT    '/
      DATA FITS_NAME   ( 51)/'OBSFOCUS'/
*
      DATA NRAO_NAME   ( 52)/'c3map          '/
      DATA JCMT_NAME   ( 52)/'OBS_MAP        '/
      DATA JCMT_COMMENT( 52)/'Map observation?                                                                '/
      DATA FITS_TYPE   ( 52)/'JCMT    '/
      DATA FITS_NAME   ( 52)/'OBSMAP  '/
*
      DATA NRAO_NAME   ( 53)/'c3npp          '/
      DATA JCMT_NAME   ( 53)/'NO_MAP_DIMS    '/
      DATA JCMT_COMMENT( 53)/'Number of dimension in the map table                                            '/
      DATA FITS_TYPE   ( 53)/'JCMT    '/
      DATA FITS_NAME   ( 53)/'NOMAPDIM'/
*
      DATA NRAO_NAME   ( 54)/'c3nmap         '/
      DATA JCMT_NAME   ( 54)/'NO_MAP_PNTS    '/
      DATA JCMT_COMMENT( 54)/'Number of map points                                                            '/
      DATA FITS_TYPE   ( 54)/'GENERAL '/
      DATA FITS_NAME   ( 54)/'NOPTS   '/
*
      DATA NRAO_NAME   ( 55)/'C6XNP          '/
      DATA JCMT_NAME   ( 55)/'NO_X_MAP_PNTS  '/
      DATA JCMT_COMMENT( 55)/'X map dimension; number of points in the x-direction                            '/
      DATA FITS_TYPE   ( 55)/'GENERAL '/
      DATA FITS_NAME   ( 55)/'NOXPTS  '/
*
      DATA NRAO_NAME   ( 56)/'C6YNP          '/
      DATA JCMT_NAME   ( 56)/'NO_Y_MAP_PNTS  '/
      DATA JCMT_COMMENT( 56)/'Y map dimension; number of points in the y-direction                            '/
      DATA FITS_TYPE   ( 56)/'GENERAL '/
      DATA FITS_NAME   ( 56)/'NOYPTS  '/
*
      DATA NRAO_NAME   ( 57)/'C6XGC          '/
      DATA JCMT_NAME   ( 57)/'X_MAP_START    '/
      DATA JCMT_COMMENT( 57)/'X coordinate of the first map point                                             '/
      DATA FITS_TYPE   ( 57)/'GENERAL '/
      DATA FITS_NAME   ( 57)/'XCELL0  '/
*
      DATA NRAO_NAME   ( 58)/'C6YGC          '/
      DATA JCMT_NAME   ( 58)/'Y_MAP_START    '/
      DATA JCMT_COMMENT( 58)/'Y coordinate of the first map point                                             '/
      DATA FITS_TYPE   ( 58)/'GENERAL '/
      DATA FITS_NAME   ( 58)/'YCELL0  '/
*
      DATA NRAO_NAME   ( 59)/'c6rev          '/
      DATA JCMT_NAME   ( 59)/'SCAN_REVERSAL  '/
      DATA JCMT_COMMENT( 59)/'Map rows scanned in alternate directions?                                       '/
      DATA FITS_TYPE   ( 59)/'JCMT    '/
      DATA FITS_NAME   ( 59)/'REVERSAL'/
*
      DATA NRAO_NAME   ( 60)/'c6sd           '/
      DATA JCMT_NAME   ( 60)/'MAP_DIRECTION  '/
      DATA JCMT_COMMENT( 60)/'Map rows are in X (horizontal) or Y(vertical) direction                         '/
      DATA FITS_TYPE   ( 60)/'JCMT    '/
      DATA FITS_NAME   ( 60)/'DIRECTN '/
*
      DATA NRAO_NAME   ( 61)/'c6xpos         '/
      DATA JCMT_NAME   ( 61)/'X_MAP_POSITIVE '/
      DATA JCMT_COMMENT( 61)/'In first row x increases (TRUE) or decreases (FALSE)                            '/
      DATA FITS_TYPE   ( 61)/'JCMT    '/
      DATA FITS_NAME   ( 61)/'XSIGN   '/
*
      DATA NRAO_NAME   ( 62)/'c6ypos         '/
      DATA JCMT_NAME   ( 62)/'Y_MAP_POSITIVE '/
      DATA JCMT_COMMENT( 62)/'In first row y increases (TRUE) or decreases (FALSE)                            '/
      DATA FITS_TYPE   ( 62)/'JCMT    '/
      DATA FITS_NAME   ( 62)/'YSIGN   '/
*
      DATA NRAO_NAME   ( 63)/'c3nis          '/
      DATA JCMT_NAME   ( 63)/'NO_SCANS       '/
      DATA JCMT_COMMENT( 63)/'Number of scans                                                                 '/
      DATA FITS_TYPE   ( 63)/'JCMT    '/
      DATA FITS_NAME   ( 63)/'NOSCANS '/
*
      DATA NRAO_NAME   ( 64)/'c3nsample      '/
      DATA JCMT_NAME   ( 64)/'NSCAN          '/
      DATA JCMT_COMMENT( 64)/'Number of scans done                                                            '/
      DATA FITS_TYPE   ( 64)/'JCMT    '/
      DATA FITS_NAME   ( 64)/'NSCAN   '/
*
      DATA NRAO_NAME   ( 65)/'c3no_scan_vars1'/
      DATA JCMT_NAME   ( 65)/'NO_SCAN_VARS1  '/
      DATA JCMT_COMMENT( 65)/'Number of scan table 1 variables                                                '/
      DATA FITS_TYPE   ( 65)/'JCMT    '/
      DATA FITS_NAME   ( 65)/'NOSCNVR1'/
*
      DATA NRAO_NAME   ( 66)/'c3no_scan_vars2'/
      DATA JCMT_NAME   ( 66)/'NO_SCAN_VARS2  '/
      DATA JCMT_COMMENT( 66)/'Number of scan table 2 variables                                                '/
      DATA FITS_TYPE   ( 66)/'JCMT    '/
      DATA FITS_NAME   ( 66)/'NOSCNVR2'/
*
      DATA NRAO_NAME   ( 67)/'C3SRT          '/
      DATA JCMT_NAME   ( 67)/'SCAN_TIME      '/
      DATA JCMT_COMMENT( 67)/'Total time of scan (=total integration time if OBS_CONTINUOUS = .FALSE.)        '/
      DATA FITS_TYPE   ( 67)/'GENERAL '/
      DATA FITS_NAME   ( 67)/'SAMPRAT '/
*
      DATA NRAO_NAME   ( 68)/'c3mxp          '/
      DATA JCMT_NAME   ( 68)/'NO_SCAN_PNTS   '/
      DATA JCMT_COMMENT( 68)/'Maximum number of map points done in a phase                                    '/
      DATA FITS_TYPE   ( 68)/'JCMT    '/
      DATA FITS_NAME   ( 68)/'NOSCNPTS'/
*
      DATA NRAO_NAME   ( 69)/'c3nci          '/
      DATA JCMT_NAME   ( 69)/'NO_CYCLES      '/
      DATA JCMT_COMMENT( 69)/'Maximum number of cycles in the scan                                            '/
      DATA FITS_TYPE   ( 69)/'JCMT    '/
      DATA FITS_NAME   ( 69)/'NOCYCLES'/
*
      DATA NRAO_NAME   ( 70)/'c3ncycle       '/
      DATA JCMT_NAME   ( 70)/'NCYCLE         '/
      DATA JCMT_COMMENT( 70)/'Number of cycles done in the scan                                               '/
      DATA FITS_TYPE   ( 70)/'JCMT    '/
      DATA FITS_NAME   ( 70)/'NCYCLE  '/
*
      DATA NRAO_NAME   ( 71)/'C3CL           '/
      DATA JCMT_NAME   ( 71)/'CYCLE_TIME     '/
      DATA JCMT_COMMENT( 71)/'Duration of each cycle                                                          '/
      DATA FITS_TYPE   ( 71)/'GENERAL '/
      DATA FITS_NAME   ( 71)/'CYCLLEN '/
*
      DATA NRAO_NAME   ( 72)/'c3ncp          '/
      DATA JCMT_NAME   ( 72)/'NO_CYCLE_PNTS  '/
      DATA JCMT_COMMENT( 72)/'Total number of xy positions observed during a cycle                            '/
      DATA FITS_TYPE   ( 72)/'JCMT    '/
      DATA FITS_NAME   ( 72)/'NOCYCPTS'/
*
      DATA NRAO_NAME   ( 73)/'C6NP           '/
      DATA JCMT_NAME   ( 73)/'NCYCLE_PNTS    '/
      DATA JCMT_COMMENT( 73)/'Number of sky points completed in the observation                               '/
      DATA FITS_TYPE   ( 73)/'JCMT    '/
      DATA FITS_NAME   ( 73)/'NCYCPTS '/
*
      DATA NRAO_NAME   ( 74)/'C3NSV          '/
      DATA JCMT_NAME   ( 74)/'NO_PHASE_VARS  '/
      DATA JCMT_COMMENT( 74)/'Number of phase table variables                                                 '/
      DATA FITS_TYPE   ( 74)/'GENERAL '/
      DATA FITS_NAME   ( 74)/'NOSWVAR '/
*
      DATA NRAO_NAME   ( 75)/'C3PPC          '/
      DATA JCMT_NAME   ( 75)/'NO_PHASES      '/
      DATA JCMT_COMMENT( 75)/'Number of phases per cycle                                                      '/
      DATA FITS_TYPE   ( 75)/'GENERAL '/
      DATA FITS_NAME   ( 75)/'NOPHASE '/
*
      DATA NRAO_NAME   ( 76)/'C5AT           '/
      DATA JCMT_NAME   ( 76)/'TAMB           '/
      DATA JCMT_COMMENT( 76)/'Ambient temperature                                                             '/
      DATA FITS_TYPE   ( 76)/'GENERAL '/
      DATA FITS_NAME   ( 76)/'TAMB    '/
*
      DATA NRAO_NAME   ( 77)/'C5PRS          '/
      DATA JCMT_NAME   ( 77)/'PAMB           '/
      DATA JCMT_COMMENT( 77)/'Mean atmospheric pressure                                                       '/
      DATA FITS_TYPE   ( 77)/'GENERAL '/
      DATA FITS_NAME   ( 77)/'PRESSURE'/
*
      DATA NRAO_NAME   ( 78)/'C5RH           '/
      DATA JCMT_NAME   ( 78)/'HAMB           '/
      DATA JCMT_COMMENT( 78)/'Mean atmospheric relative humidity                                              '/
      DATA FITS_TYPE   ( 78)/'GENERAL '/
      DATA FITS_NAME   ( 78)/'HUMIDITY'/
*
      DATA NRAO_NAME   ( 79)/'c4azerr        '/
      DATA JCMT_NAME   ( 79)/'SDIS(7)        '/
      DATA JCMT_COMMENT( 79)/'DAZ:Net Az offset at start (inc.tracker ball setting and user correction)       '/
      DATA FITS_TYPE   ( 79)/'GENERAL '/
      DATA FITS_NAME   ( 79)/'XPOINT  '/
*
      DATA NRAO_NAME   ( 80)/'c4elerr        '/
      DATA JCMT_NAME   ( 80)/'SDIS(8)        '/
      DATA JCMT_COMMENT( 80)/'DEL:Net El offset at start (inc.tracker ball setting and user correction)       '/
      DATA FITS_TYPE   ( 80)/'GENERAL '/
      DATA FITS_NAME   ( 80)/'YPOINT  '/
*
      DATA NRAO_NAME   ( 81)/'UAZ            '/
      DATA JCMT_NAME   ( 81)/'SDIS(36)       '/
      DATA JCMT_COMMENT( 81)/'User az correction                                                              '/
      DATA FITS_TYPE   ( 81)/'GENERAL '/
      DATA FITS_NAME   ( 81)/'UXPNT   '/
*
      DATA NRAO_NAME   ( 82)/'UEL            '/
      DATA JCMT_NAME   ( 82)/'SDIS(37)       '/
      DATA JCMT_COMMENT( 82)/'User el correction                                                              '/
      DATA FITS_TYPE   ( 82)/'GENERAL '/
      DATA FITS_NAME   ( 82)/'UYPNT   '/
*
      DATA NRAO_NAME   ( 83)/'C7SZVRAD       '/
      DATA JCMT_NAME   ( 83)/'SZVRAD         '/
      DATA JCMT_COMMENT( 83)/'Number of elements of vradial array                                             '/
      DATA FITS_TYPE   ( 83)/'GENERAL '/
      DATA FITS_NAME   ( 83)/'SZVRAD  '/
*
      DATA NRAO_NAME   ( 84)/'C8AAE          '/
      DATA JCMT_NAME   ( 84)/'APERTURE_EFF   '/
      DATA JCMT_COMMENT( 84)/'Ratio total power observed/incident on the telescope                            '/
      DATA FITS_TYPE   ( 84)/'GENERAL '/
      DATA FITS_NAME   ( 84)/'APPEFF  '/
*
      DATA NRAO_NAME   ( 85)/'C8ABE          '/
      DATA JCMT_NAME   ( 85)/'BEAM_EFF       '/
      DATA JCMT_COMMENT( 85)/'Fraction of beam in diffraction limited main beam                               '/
      DATA FITS_TYPE   ( 85)/'GENERAL '/
      DATA FITS_NAME   ( 85)/'BEAMEFF '/
*
      DATA NRAO_NAME   ( 86)/'C8GN           '/
      DATA JCMT_NAME   ( 86)/'ANTENNA_GAIN   '/
      DATA JCMT_COMMENT( 86)/'Antenna gain                                                                    '/
      DATA FITS_TYPE   ( 86)/'GENERAL '/
      DATA FITS_NAME   ( 86)/'ANTGAIN '/
*
      DATA NRAO_NAME   ( 87)/'C8EL           '/
      DATA JCMT_NAME   ( 87)/'ETAL           '/
      DATA JCMT_COMMENT( 87)/'Rear spillover and scattering efficiency                                        '/
      DATA FITS_TYPE   ( 87)/'GENERAL '/
      DATA FITS_NAME   ( 87)/'ETAL    '/
*
      DATA NRAO_NAME   ( 88)/'C8EF           '/
      DATA JCMT_NAME   ( 88)/'ETAFSS         '/
      DATA JCMT_COMMENT( 88)/'Forward spillover and scattering efficiency                                     '/
      DATA FITS_TYPE   ( 88)/'GENERAL '/
      DATA FITS_NAME   ( 88)/'ETAFSS  '/
*
      DATA NRAO_NAME   ( 89)/'c4sm           '/
      DATA JCMT_NAME   ( 89)/'CHOPPING       '/
      DATA JCMT_COMMENT( 89)/'Secondary mirror is chopping                                                    '/
      DATA FITS_TYPE   ( 89)/'JCMT    '/
      DATA FITS_NAME   ( 89)/'CHOPPING'/
*
      DATA NRAO_NAME   ( 90)/'c4fun          '/
      DATA JCMT_NAME   ( 90)/'WAVEFORM       '/
      DATA JCMT_COMMENT( 90)/'Secondary mirror chopping waveform                                              '/
      DATA FITS_TYPE   ( 90)/'JCMT    '/
      DATA FITS_NAME   ( 90)/'WAVEFORM'/
*
      DATA NRAO_NAME   ( 91)/'c4frq          '/
      DATA JCMT_NAME   ( 91)/'FREQUENCY      '/
      DATA JCMT_COMMENT( 91)/'Secondary mirror chopping period                                                '/
      DATA FITS_TYPE   ( 91)/'JCMT    '/
      DATA FITS_NAME   ( 91)/'CHOPFREQ'/
*
      DATA NRAO_NAME   ( 92)/'c4smco         '/
      DATA JCMT_NAME   ( 92)/'COORDS         '/
      DATA JCMT_COMMENT( 92)/'Secondary mirror chopping coordinate system                                     '/
      DATA FITS_TYPE   ( 92)/'JCMT    '/
      DATA FITS_NAME   ( 92)/'CHOPCOOR'/
*
      DATA NRAO_NAME   ( 93)/'c4throw        '/
      DATA JCMT_NAME   ( 93)/'THROW          '/
      DATA JCMT_COMMENT( 93)/'Secondary mirror chop throw                                                     '/
      DATA FITS_TYPE   ( 93)/'JCMT    '/
      DATA FITS_NAME   ( 93)/'CHOPTHRW'/
*
      DATA NRAO_NAME   ( 94)/'c4posang       '/
      DATA JCMT_NAME   ( 94)/'POSANG         '/
      DATA JCMT_COMMENT( 94)/'Secondary mirror chop position angle                                            '/
      DATA FITS_TYPE   ( 94)/'JCMT    '/
      DATA FITS_NAME   ( 94)/'CHOPDIRN'/
*
      DATA NRAO_NAME   ( 95)/'c4offs_ew      '/
      DATA JCMT_NAME   ( 95)/'OFFS_EW        '/
      DATA JCMT_COMMENT( 95)/'Secondary mirror offset parallel to lower axis (East-West Tilt)                 '/
      DATA FITS_TYPE   ( 95)/'JCMT    '/
      DATA FITS_NAME   ( 95)/'EWTILT  '/
*
      DATA NRAO_NAME   ( 96)/'c4offs_ns      '/
      DATA JCMT_NAME   ( 96)/'OFFS_NS        '/
      DATA JCMT_COMMENT( 96)/'Secondary mirror offset parallel to upper axis (North-South Tilt)               '/
      DATA FITS_TYPE   ( 96)/'JCMT    '/
      DATA FITS_NAME   ( 96)/'NSTILT  '/
*
      DATA NRAO_NAME   ( 97)/'c4X            '/
      DATA JCMT_NAME   ( 97)/'X              '/
      DATA JCMT_COMMENT( 97)/'Secondary mirror absolute X position at observation start                       '/
      DATA FITS_TYPE   ( 97)/'JCMT    '/
      DATA FITS_NAME   ( 97)/'AFOCUSV '/
*
      DATA NRAO_NAME   ( 98)/'c4Y            '/
      DATA JCMT_NAME   ( 98)/'Y              '/
      DATA JCMT_COMMENT( 98)/'Secondary mirror absolute Y position at observation start                       '/
      DATA FITS_TYPE   ( 98)/'JCMT    '/
      DATA FITS_NAME   ( 98)/'AFOCUSH '/
*
      DATA NRAO_NAME   ( 99)/'c4Z            '/
      DATA JCMT_NAME   ( 99)/'Z              '/
      DATA JCMT_COMMENT( 99)/'Secondary mirror absolute Z position at observation start                       '/
      DATA FITS_TYPE   ( 99)/'JCMT    '/
      DATA FITS_NAME   ( 99)/'AFOCUSR '/
*
      DATA NRAO_NAME   (100)/'c4ew_scale     '/
      DATA JCMT_NAME   (100)/'EW_AMPL_SCALE  '/
      DATA JCMT_COMMENT(100)/'Secondary mirror ew chop scale                                                  '/
      DATA FITS_TYPE   (100)/'JCMT    '/
      DATA FITS_NAME   (100)/'EW_SCALE'/
*
      DATA NRAO_NAME   (101)/'c4ns_scale     '/
      DATA JCMT_NAME   (101)/'NS_AMPL_SCALE  '/
      DATA JCMT_COMMENT(101)/'Secondary mirror ns chop scale                                                  '/
      DATA FITS_TYPE   (101)/'JCMT    '/
      DATA FITS_NAME   (101)/'NS_SCALE'/
*
      DATA NRAO_NAME   (102)/'c4ew_encoder   '/
      DATA JCMT_NAME   (102)/'AMPL_E_SET     '/
      DATA JCMT_COMMENT(102)/'Secondary mirror ew encoder value                                               '/
      DATA FITS_TYPE   (102)/'JCMT    '/
      DATA FITS_NAME   (102)/'EW_ENCOD'/
*
      DATA NRAO_NAME   (103)/'c4ns_encoder   '/
      DATA JCMT_NAME   (103)/'AMPL_N_SET     '/
      DATA JCMT_COMMENT(103)/'Secondary mirror ns encoder value                                               '/
      DATA FITS_TYPE   (103)/'JCMT    '/
      DATA FITS_NAME   (103)/'NS_ENCOD'/
*
      DATA NRAO_NAME   (104)/'C2FV           '/
      DATA JCMT_NAME   (104)/'DX             '/
      DATA JCMT_COMMENT(104)/'Secondary mirror x displacement from nominal at observation start               '/
      DATA FITS_TYPE   (104)/'GENERAL '/
      DATA FITS_NAME   (104)/'FOCUSV  '/
*
      DATA NRAO_NAME   (105)/'C2FL           '/
      DATA JCMT_NAME   (105)/'DY             '/
      DATA JCMT_COMMENT(105)/'Secondary mirror y displacement from nominal at observation start               '/
      DATA FITS_TYPE   (105)/'GENERAL '/
      DATA FITS_NAME   (105)/'FOCUSL  '/
*
      DATA NRAO_NAME   (106)/'C2FR           '/
      DATA JCMT_NAME   (106)/'DZ             '/
      DATA JCMT_COMMENT(106)/'Secondary mirror z displacement from nominal at observation start               '/
      DATA FITS_TYPE   (106)/'GENERAL '/
      DATA FITS_NAME   (106)/'FOCUSR  '/
*
      DATA NRAO_NAME   (107)/'c4moco         '/
      DATA JCMT_NAME   (107)/'TEL_COORDS     '/
      DATA JCMT_COMMENT(107)/'Mounting of telescope; defined as LOWER/UPPER axes, e.g; AZ/ALT                 '/
      DATA FITS_TYPE   (107)/'JCMT    '/
      DATA FITS_NAME   (107)/'MOUNTING'/
*
      DATA NRAO_NAME   (108)/'c3nfoc         '/
      DATA JCMT_NAME   (108)/'NO_FE_O_CH     '/
      DATA JCMT_COMMENT(108)/'NO_FE_O_CH:No. of frontend output channels                                      '/
      DATA FITS_TYPE   (108)/'JCMT    '/
      DATA FITS_NAME   (108)/'NOFCHAN '/
*
      DATA NRAO_NAME   (109)/'c7vr           '/
      DATA JCMT_NAME   (109)/'VELOCITY       '/
      DATA JCMT_COMMENT(109)/'Radial velocity of the source                                                   '/
      DATA FITS_TYPE   (109)/'GENERAL '/
      DATA FITS_NAME   (109)/'VELOCITY'/
*
      DATA NRAO_NAME   (110)/'c12Tcold       '/
      DATA JCMT_NAME   (110)/'T_COLD         '/
      DATA JCMT_COMMENT(110)/'Cold load temperature                                                           '/
      DATA FITS_TYPE   (110)/'JCMT    '/
      DATA FITS_NAME   (110)/'TCOLD   '/
*
      DATA NRAO_NAME   (111)/'c12Tamb        '/
      DATA JCMT_NAME   (111)/'T_HOT          '/
      DATA JCMT_COMMENT(111)/'Ambient load temperature                                                        '/
      DATA FITS_TYPE   (111)/'JCMT    '/
      DATA FITS_NAME   (111)/'THOT    '/
*
      DATA NRAO_NAME   (112)/'c12vdef        '/
      DATA JCMT_NAME   (112)/'VEL_DEFN       '/
      DATA JCMT_COMMENT(112)/'Velocity definition code - radio, optical, or relativistic                      '/
      DATA FITS_TYPE   (112)/'        '/
      DATA FITS_NAME   (112)/'        '/
*
      DATA NRAO_NAME   (113)/'c12vref        '/
      DATA JCMT_NAME   (113)/'VEL_REF        '/
      DATA JCMT_COMMENT(113)/'Velocity frame of reference - LSR, Bary-, Helio-, or Geo- centric               '/
      DATA FITS_TYPE   (113)/'        '/
      DATA FITS_NAME   (113)/'        '/
*
      DATA NRAO_NAME   (114)/'C3NRC          '/
      DATA JCMT_NAME   (114)/'NO_BE_I_CH     '/
      DATA JCMT_COMMENT(114)/'Number of backend input channels                                                '/
      DATA FITS_TYPE   (114)/'JCMT    '/
      DATA FITS_NAME   (114)/'NORCHAN '/
*
      DATA NRAO_NAME   (115)/'C3NCH          '/
      DATA JCMT_NAME   (115)/'NO_BE_O_CH     '/
      DATA JCMT_COMMENT(115)/'Number of backend output channels                                               '/
      DATA FITS_TYPE   (115)/'JCMT    '/
      DATA FITS_NAME   (115)/'NOBCHAN '/
*
      DATA NRAO_NAME   (116)/'C3NRS          '/
      DATA JCMT_NAME   (116)/'NO_BES         '/
      DATA JCMT_COMMENT(116)/'Number of backend sections                                                      '/
      DATA FITS_TYPE   (116)/'JCMT    '/
      DATA FITS_NAME   (116)/'NORSECT '/
*
      DATA NRAO_NAME   (117)/'C7BCV          '/
      DATA JCMT_NAME   (117)/'BAD_CHANNEL    '/
      DATA JCMT_COMMENT(117)/'Bad channel value                                                               '/
      DATA FITS_TYPE   (117)/'GENERAL '/
      DATA FITS_NAME   (117)/'BADCHV  '/
*
      DATA NRAO_NAME   (118)/'C12CAL         '/
      DATA JCMT_NAME   (118)/'DATA_UNITS     '/
      DATA JCMT_COMMENT(118)/'Units of spectrum data                                                          '/
      DATA FITS_TYPE   (118)/'JCMT    '/
      DATA FITS_NAME   (118)/'DATAUNIT'/
*
      DATA NRAO_NAME   (119)/'C6MODE         '/
      DATA JCMT_NAME   (119)/'SWITCH_MODE    '/
      DATA JCMT_COMMENT(119)/'Observation mode                                                                '/
      DATA FITS_TYPE   (119)/'JCMT    '/
      DATA FITS_NAME   (119)/'SWMODE '/
*
      DATA NRAO_NAME   (120)/'C12CALTASK     '/
      DATA JCMT_NAME   (120)/'BE_CAL_TASK    '/
      DATA JCMT_COMMENT(120)/'Calibration instrument used (FE, BE, or USER)                                   '/
      DATA FITS_TYPE   (120)/'JCMT    '/
      DATA FITS_NAME   (120)/'CALTASK '/
*
      DATA NRAO_NAME   (121)/'C12CALTYPE     '/
      DATA JCMT_NAME   (121)/'BE_CAL_TYPE    '/
      DATA JCMT_COMMENT(121)/'Type of calibration (THREELOADS or TWOLOADS)                                    '/
      DATA FITS_TYPE   (121)/'JCMT    '/
      DATA FITS_NAME   (121)/'CALTYPE '/
*
      DATA NRAO_NAME   (122)/'C12REDMODE     '/
      DATA JCMT_NAME   (122)/'BE_RED_MODE    '/
      DATA JCMT_COMMENT(122)/'Way of calibrating the data (RATIO or DIFFERENCE)                               '/
      DATA FITS_TYPE   (122)/'JCMT    '/
      DATA FITS_NAME   (122)/'REDMODE '/
*
      DATA NRAO_NAME   (123)/'C3NOIFPBES     '/
      DATA JCMT_NAME   (123)/'NO_IF_PER_BES  '/
      DATA JCMT_COMMENT(123)/'Number of IF inputs to each section (2 for correlator, 1 for AOS)               '/
      DATA FITS_TYPE   (123)/'JCMT    '/
      DATA FITS_NAME   (123)/'NOIFPBES'/
*
      DATA NRAO_NAME   (124)/'C3CONFIGNR     '/
      DATA JCMT_NAME   (124)/'DAS_CONF_NR    '/
      DATA JCMT_COMMENT(124)/'Backend configuration                                                           '/
      DATA FITS_TYPE   (124)/'JCMT    '/
      DATA FITS_NAME   (124)/'CONFIG  '/
*
      DATA NRAO_NAME   (125)/'C3DASOUTPUT    '/
      DATA JCMT_NAME   (125)/'DAS_OUTPUT     '/
      DATA JCMT_COMMENT(125)/'Description of output in DAS DATA (SPECTRUM, T_REC, T_SYS, etc.)                '/
      DATA FITS_TYPE   (125)/'JCMT    '/
      DATA FITS_NAME   (125)/'OUTPUT  '/
*
      DATA NRAO_NAME   (126)/'C3DASCALSRC    '/
      DATA JCMT_NAME   (126)/'DAS_CAL_SOURCE '/
      DATA JCMT_COMMENT(126)/'DAS calibration source for backend calibration (POWER or DATA)                  '/
      DATA FITS_TYPE   (126)/'JCMT    '/
      DATA FITS_NAME   (126)/'CALSRC  '/
*
      DATA NRAO_NAME   (127)/'C3DASSHFTFRAC  '/
      DATA JCMT_NAME   (127)/'DAS_SHIFT_FRAC '/
      DATA JCMT_COMMENT(127)/'DAS calibration source for backend calibration (POWER or DATA)                  '/
      DATA FITS_TYPE   (127)/'JCMT    '/
      DATA FITS_NAME   (127)/'SHFTFRAC'/
*
      DATA NRAO_NAME   (128)/'c7tau225       '/
      DATA JCMT_NAME   (128)/'CSO_TAU        '/
      DATA JCMT_COMMENT(128)/'CSO tau at 225GHz                                                               '/
      DATA FITS_TYPE   (128)/'JCMT    '/
      DATA FITS_NAME   (128)/'TAU225  '/
*
      DATA NRAO_NAME   (129)/'c7taurms       '/
      DATA JCMT_NAME   (129)/'CSO_TAU_RMS    '/
      DATA JCMT_COMMENT(129)/'CSO tau rms                                                                     '/
      DATA FITS_TYPE   (129)/'JCMT    '/
      DATA FITS_NAME   (129)/'TAURMS  '/
*
      DATA NRAO_NAME   (130)/'c7tautime      '/
      DATA JCMT_NAME   (130)/'CSO_YYMMDDHHMM '/
      DATA JCMT_COMMENT(130)/'CSO tau time (YYMMDDHHMM)                                                       '/
      DATA FITS_TYPE   (130)/'JCMT    '/
      DATA FITS_NAME   (130)/'TAUTIME '/
*
      DATA NRAO_NAME   (131)/'c7seeing       '/
      DATA JCMT_NAME   (131)/'SAO_SEEING     '/
      DATA JCMT_COMMENT(131)/'Seeing at JCMT                                                                  '/
      DATA FITS_TYPE   (131)/'JCMT    '/
      DATA FITS_NAME   (131)/'SEEING  '/
*
      DATA NRAO_NAME   (132)/'c7seetime      '/
      DATA JCMT_NAME   (132)/'SAO_YYMMDDHHMM '/
      DATA JCMT_COMMENT(132)/'SAO seeing time (YYMMDDHHMM)                                                    '/
      DATA FITS_TYPE   (132)/'JCMT    '/
      DATA FITS_NAME   (132)/'SEETIME '/
*
      DATA NRAO_NAME   (133)/'C3NRC          '/
      DATA JCMT_NAME   (133)/'NO_FE_O_CH     '/
      DATA JCMT_COMMENT(133)/'NO_FE_O_CH:No. frontend output channels                                         '/
      DATA FITS_TYPE   (133)/'GENERAL '/
      DATA FITS_NAME   (133)/'NORCHAN '/
*
      DATA NRAO_NAME   (134)/'c3nch          '/
      DATA JCMT_NAME   (134)/'NO_BE_I_CH     '/
      DATA JCMT_COMMENT(134)/'NO_BE_I_CH:No. backend output channels                                          '/
      DATA FITS_TYPE   (134)/'JCMT    '/
      DATA FITS_NAME   (134)/'NOBEOCH '/
*
      DATA NRAO_NAME   (135)/'C7BCV          '/
      DATA JCMT_NAME   (135)/'BAD_CHANNEL    '/
      DATA JCMT_COMMENT(135)/'Bad channel value                                                               '/
      DATA FITS_TYPE   (135)/'GENERAL '/
      DATA FITS_NAME   (135)/'BADCHV  '/
*
      DATA NRAO_NAME   (136)/'C3NRC          '/
      DATA JCMT_NAME   (136)/'NRC            '/
      DATA JCMT_COMMENT(136)/'NO_BE_I_CH:No.backend input channels                                            '/
      DATA FITS_TYPE   (136)/'GENERAL '/
      DATA FITS_NAME   (136)/'NORCHAN '/
*
      DATA NRAO_NAME   (137)/'c3nch          '/
      DATA JCMT_NAME   (137)/'NO_BE_O_CH     '/
      DATA JCMT_COMMENT(137)/'No.backend output channels                                                      '/
      DATA FITS_TYPE   (137)/'JCMT    '/
      DATA FITS_NAME   (137)/'NOBEOCH '/
*
      DATA NRAO_NAME   (138)/'C7BCV          '/
      DATA JCMT_NAME   (138)/'BAD_CHANNEL    '/
      DATA JCMT_COMMENT(138)/'Bad channel value                                                               '/
      DATA FITS_TYPE   (138)/'GENERAL '/
      DATA FITS_NAME   (138)/'BADCHV  '/
*
      DATA NRAO_NAME   (139)/'c7fil          '/
      DATA JCMT_NAME   (139)/'FILTER         '/
      DATA JCMT_COMMENT(139)/'Filter                                                                          '/
      DATA FITS_TYPE   (139)/'JCMT    '/
      DATA FITS_NAME   (139)/'FILTER  '/
*
      DATA NRAO_NAME   (140)/'c7ap           '/
      DATA JCMT_NAME   (140)/'APERTURE       '/
      DATA JCMT_COMMENT(140)/'Aperture                                                                        '/
      DATA FITS_TYPE   (140)/'JCMT    '/
      DATA FITS_NAME   (140)/'APERTURE'/
*
      DATA NRAO_NAME   (141)/'C6CYCLREV      '/
      DATA JCMT_NAME   (141)/'CYCLE_REVERSAL '/
      DATA JCMT_COMMENT(141)/'cycle reversal flag                                                             '/
      DATA FITS_TYPE   (141)/'JCMT    '/
      DATA FITS_NAME   (141)/'CYCLREV '/
*
      DATA NRAO_NAME   (142)/'c7tau225       '/
      DATA JCMT_NAME   (142)/'CSO_TAU        '/
      DATA JCMT_COMMENT(142)/'CSO tau at 225GHz                                                               '/
      DATA FITS_TYPE   (142)/'JCMT    '/
      DATA FITS_NAME   (142)/'TAU225  '/
*
      DATA NRAO_NAME   (143)/'c7taurms       '/
      DATA JCMT_NAME   (143)/'CSO_TAU_RMS    '/
      DATA JCMT_COMMENT(143)/'CSO tau rms                                                                     '/
      DATA FITS_TYPE   (143)/'JCMT    '/
      DATA FITS_NAME   (143)/'TAURMS  '/
*
      DATA NRAO_NAME   (144)/'c7tautime      '/
      DATA JCMT_NAME   (144)/'CSO_YYMMDDHHMM '/
      DATA JCMT_COMMENT(144)/'CSO tau time (YYMMDDHHMM)                                                       '/
      DATA FITS_TYPE   (144)/'JCMT    '/
      DATA FITS_NAME   (144)/'TAUTIME '/
*
      DATA NRAO_NAME   (145)/'c7seeing       '/
      DATA JCMT_NAME   (145)/'SAO_SEEING     '/
      DATA JCMT_COMMENT(145)/'Seeing at JCMT                                                                  '/
      DATA FITS_TYPE   (145)/'JCMT    '/
      DATA FITS_NAME   (145)/'SEEING  '/
*
      DATA NRAO_NAME   (146)/'c7seetime      '/
      DATA JCMT_NAME   (146)/'SAO_YYMMDDHHMM '/
      DATA JCMT_COMMENT(146)/'SAO seeing time (YYMMDDHHMM)                                                    '/
      DATA FITS_TYPE   (146)/'JCMT    '/
      DATA FITS_NAME   (146)/'SEETIME '/
*
      DATA NRAO_NAME   (147)/'C6CYCLREV      '/
      DATA JCMT_NAME   (147)/'CYCLE_REVERSAL '/
      DATA JCMT_COMMENT(147)/'Cycle reversal flag                                                             '/
      DATA FITS_TYPE   (147)/'JCMT    '/
      DATA FITS_NAME   (147)/'CYCLREV '/
*
      DATA NRAO_NAME   (148)/'c7fil          '/
      DATA JCMT_NAME   (148)/'FILTER         '/
      DATA JCMT_COMMENT(148)/'Filter                                                                          '/
      DATA FITS_TYPE   (148)/'JCMT    '/
      DATA FITS_NAME   (148)/'FILTER  '/
*
      DATA NRAO_NAME   (149)/'c7ap           '/
      DATA JCMT_NAME   (149)/'APERTURE       '/
      DATA JCMT_COMMENT(149)/'Aperture                                                                        '/
      DATA FITS_TYPE   (149)/'JCMT    '/
      DATA FITS_NAME   (149)/'APERTURE'/
*
      DATA NRAO_NAME   (150)/'c7sntvtyrg     '/
      DATA JCMT_NAME   (150)/'RANGE          '/
      DATA JCMT_COMMENT(150)/'Sensitivity range of lockin                                                     '/
      DATA FITS_TYPE   (150)/'JCMT    '/
      DATA FITS_NAME   (150)/'SNTVTYRG'/
*
      DATA NRAO_NAME   (151)/'c7snstvty      '/
      DATA JCMT_NAME   (151)/'SENSITIVITY    '/
      DATA JCMT_COMMENT(151)/'Lockin sensitivity in scale range units                                         '/
      DATA FITS_TYPE   (151)/'JCMT    '/
      DATA FITS_NAME   (151)/'SNSTVTY '/
*
      DATA NRAO_NAME   (152)/'c7timecnst     '/
      DATA JCMT_NAME   (152)/'TIME_CONSTANT  '/
      DATA JCMT_COMMENT(152)/'Lockin time constant                                                            '/
      DATA FITS_TYPE   (152)/'JCMT    '/
      DATA FITS_NAME   (152)/'TIMECNST'/
*
      DATA NRAO_NAME   (153)/'c7phase        '/
      DATA JCMT_NAME   (153)/'PHASE          '/
      DATA JCMT_COMMENT(153)/'Lockin phase                                                                    '/
      DATA FITS_TYPE   (153)/'JCMT    '/
      DATA FITS_NAME   (153)/'PHASE   '/
*
      DATA NRAO_NAME   (154)/'c7tau225       '/
      DATA JCMT_NAME   (154)/'CSO_TAU        '/
      DATA JCMT_COMMENT(154)/'CSO tau at 225GHz                                                               '/
      DATA FITS_TYPE   (154)/'JCMT    '/
      DATA FITS_NAME   (154)/'TAU225  '/
*
      DATA NRAO_NAME   (155)/'c7taurms       '/
      DATA JCMT_NAME   (155)/'CSO_TAU_RMS    '/
      DATA JCMT_COMMENT(155)/'CSO tau rms                                                                     '/
      DATA FITS_TYPE   (155)/'JCMT    '/
      DATA FITS_NAME   (155)/'TAURMS  '/
*
      DATA NRAO_NAME   (156)/'c7tautime      '/
      DATA JCMT_NAME   (156)/'CSO_YYMMDDHHMM '/
      DATA JCMT_COMMENT(156)/'CSO tau time (YYMMDDHHMM)                                                       '/
      DATA FITS_TYPE   (156)/'JCMT    '/
      DATA FITS_NAME   (156)/'TAUTIME '/
*
      DATA NRAO_NAME   (157)/'c7seeing       '/
      DATA JCMT_NAME   (157)/'SAO_SEEING     '/
      DATA JCMT_COMMENT(157)/'Seeing at JCMT                                                                  '/
      DATA FITS_TYPE   (157)/'JCMT    '/
      DATA FITS_NAME   (157)/'SEEING  '/
*
      DATA NRAO_NAME   (158)/'c7seetime      '/
      DATA JCMT_NAME   (158)/'SAO_YYMMDDHHMM '/
      DATA JCMT_COMMENT(158)/'SAO seeing time (YYMMDDHHMM)                                                    '/
      DATA FITS_TYPE   (158)/'JCMT    '/
      DATA FITS_NAME   (158)/'SEETIME '/
*
      DATA NRAO_NAME   (159)/'c7nif          '/
      DATA JCMT_NAME   (159)/'NO_IF_CH       '/
      DATA JCMT_COMMENT(159)/'                                                                                '/
      DATA FITS_TYPE   (159)/'JCMT    '/
      DATA FITS_NAME   (159)/'NIF     '/
*
      DATA NRAO_NAME   (160)/'C1ONA          '/
      DATA JCMT_NAME   (160)/'PROJECT_OBS_1  '/
      DATA JCMT_COMMENT(160)/'Name of the primary observer                                                    '/
      DATA FITS_TYPE   (160)/'GENERAL '/
      DATA FITS_NAME   (160)/'OBSERVER'/
*
      DATA NRAO_NAME   (161)/'C2XPC          '/
      DATA JCMT_NAME   (161)/'TEL_PC_LAZ     '/
      DATA JCMT_COMMENT(161)/'Azimuth/RA enc.zero; enc.reading = az + pc_laz                                  '/
      DATA FITS_TYPE   (161)/'GENERAL '/
      DATA FITS_NAME   (161)/'AXPOINT '/
*
      DATA NRAO_NAME   (162)/'C2YPC          '/
      DATA JCMT_NAME   (162)/'TEL_PC_UAZ     '/
      DATA JCMT_COMMENT(162)/'Altitude/DEC enc.zero; enc.reading = az + pc_uaz                                '/
      DATA FITS_TYPE   (162)/'GENERAL '/
      DATA FITS_NAME   (162)/'AYPOINT '/
*
      DATA NRAO_NAME   (163)/'C2PC1          '/
      DATA JCMT_NAME   (163)/'TEL_PC_LAN     '/
      DATA JCMT_COMMENT(163)/'Angle by which lower axis is north of ideal                                     '/
      DATA FITS_TYPE   (163)/'GENERAL '/
      DATA FITS_NAME   (163)/'PTCON1  '/
*
      DATA NRAO_NAME   (164)/'C2PC2          '/
      DATA JCMT_NAME   (164)/'TEL_PC_LAE     '/
      DATA JCMT_COMMENT(164)/'Angle by which lower axis is east of ideal                                      '/
      DATA FITS_TYPE   (164)/'GENERAL '/
      DATA FITS_NAME   (164)/'PTCON2  '/
*
      DATA NRAO_NAME   (165)/'C2PC3          '/
      DATA JCMT_NAME   (165)/'TEL_PC_UANP    '/
      DATA JCMT_COMMENT(165)/'Angle by which upper axis is not perpendicular to lower                         '/
      DATA FITS_TYPE   (165)/'GENERAL '/
      DATA FITS_NAME   (165)/'PTCON3  '/
*
      DATA NRAO_NAME   (166)/'C2PC4          '/
      DATA JCMT_NAME   (166)/'TEL_PC_BNP     '/
      DATA JCMT_COMMENT(166)/'Angle by which beam is not perpendicular to upper axis                          '/
      DATA FITS_TYPE   (166)/'GENERAL '/
      DATA FITS_NAME   (166)/'PTCON4  '/
*
      DATA NRAO_NAME   (167)/'c5ir1          '/
      DATA JCMT_NAME   (167)/'TEL_REFR_A     '/
      DATA JCMT_COMMENT(167)/'Refraction constant A (see MTIN026)                                             '/
      DATA FITS_TYPE   (167)/'GENERAL '/
      DATA FITS_NAME   (167)/'REFRAC1 '/
*
      DATA NRAO_NAME   (168)/'c5ir2          '/
      DATA JCMT_NAME   (168)/'TEL_REFR_B     '/
      DATA JCMT_COMMENT(168)/'Refraction constant B (see MTIN026)                                             '/
      DATA FITS_TYPE   (168)/'GENERAL '/
      DATA FITS_NAME   (168)/'REFRAC2 '/
*
      DATA NRAO_NAME   (169)/'c5ir3          '/
      DATA JCMT_NAME   (169)/'TEL_REFR_C     '/
      DATA JCMT_COMMENT(169)/'Refraction constant C (see MTIN026)                                             '/
      DATA FITS_TYPE   (169)/'GENERAL '/
      DATA FITS_NAME   (169)/'REFRAC3 '/
*
      DATA NRAO_NAME   (170)/'C9OT           '/
      DATA JCMT_NAME   (170)/'TEL_TOLERANCE  '/
      DATA JCMT_COMMENT(170)/'Observing tolerance                                                             '/
      DATA FITS_TYPE   (170)/'GENERAL '/
      DATA FITS_NAME   (170)/'OBSTOL  '/
*
      DATA NRAO_NAME   (171)/'C90T           '/
      DATA JCMT_NAME   (171)/'TEL_TOLERANCE  '/
      DATA JCMT_COMMENT(171)/'Observing tolerance                                                             '/
      DATA FITS_TYPE   (171)/'GENERAL '/
      DATA FITS_NAME   (171)/'OBSTOL  '/
*
      DATA NRAO_NAME   (172)/'C4EDC          '/
      DATA JCMT_NAME   (172)/'CENTRE_DEC     '/
      DATA JCMT_COMMENT(172)/'Declination of date                                                             '/
      DATA FITS_TYPE   (172)/'GENERAL '/
      DATA FITS_NAME   (172)/'EPOCDEC '/
*
      DATA NRAO_NAME   (173)/'C4DO1          '/
      DATA JCMT_NAME   (173)/'CELL_X         '/
      DATA JCMT_COMMENT(173)/'Cell x dimension; descriptive origin item 1                                     '/
      DATA FITS_TYPE   (173)/'GENERAL '/
      DATA FITS_NAME   (173)/'DESORG1 '/
*
      DATA NRAO_NAME   (174)/'C4DO2          '/
      DATA JCMT_NAME   (174)/'CELL_Y         '/
      DATA JCMT_COMMENT(174)/'Cell y dimension; descriptive origin item 2                                     '/
      DATA FITS_TYPE   (174)/'GENERAL '/
      DATA FITS_NAME   (174)/'DESORG2 '/
*
      DATA NRAO_NAME   (175)/'C4DO3          '/
      DATA JCMT_NAME   (175)/'CELL_V2X       '/
      DATA JCMT_COMMENT(175)/'Angle by which the cell x axis is oriented with respect to local vertical       '/
      DATA FITS_TYPE   (175)/'GENERAL '/
      DATA FITS_NAME   (175)/'DESORG3 '/
*
      DATA NRAO_NAME   (176)/'c4per          '/
      DATA JCMT_NAME   (176)/'PERIOD         '/
      DATA JCMT_COMMENT(176)/'Secondary mirror chopping period                                                '/
      DATA FITS_TYPE   (176)/'GENERAL '/
      DATA FITS_NAME   (176)/'CHOPTIME'/
*
      DATA NRAO_NAME   (177)/'c4ampl_ew      '/
      DATA JCMT_NAME   (177)/'AMPL_EW        '/
      DATA JCMT_COMMENT(177)/'Secondary mirror chopping amplitude parallel to lower axis                      '/
      DATA FITS_TYPE   (177)/'GENERAL '/
      DATA FITS_NAME   (177)/'CHOPAZ  '/
*
      DATA NRAO_NAME   (178)/'c4ampl_ns      '/
      DATA JCMT_NAME   (178)/'AMPL_NS        '/
      DATA JCMT_COMMENT(178)/'Secondary mirror chopping amplitude parallel to upper axis                      '/
      DATA FITS_TYPE   (178)/'GENERAL '/
      DATA FITS_NAME   (178)/'CHOPEL  '/
*
      DATA NRAO_NAME   (179)/'c4daz          '/
      DATA JCMT_NAME   (179)/'DAZ_SM         '/
      DATA JCMT_COMMENT(179)/'Telescope lower axis correction for secondary mirror XYZ                        '/
      DATA FITS_TYPE   (179)/'GENERAL '/
      DATA FITS_NAME   (179)/'XPOINT  '/
*
      DATA NRAO_NAME   (180)/'c4del          '/
      DATA JCMT_NAME   (180)/'DEL_SM         '/
      DATA JCMT_COMMENT(180)/'Telescope upper axis correction for secondary mirror XYZ                        '/
      DATA FITS_TYPE   (180)/'GENERAL '/
      DATA FITS_NAME   (180)/'YPOINT  '/
*
      DATA NRAO_NAME   (181)/'C2ORI          '/
      DATA JCMT_NAME   (181)/'SECONDARY_ORI  '/
      DATA JCMT_COMMENT(181)/'Rotation or polarization angle orientation of the frontend/reflector            '/
      DATA FITS_TYPE   (181)/'GENERAL '/
      DATA FITS_NAME   (181)/'ORIENT  '/
*
      DATA NRAO_NAME   (182)/'C5IR           '/
      DATA JCMT_NAME   (182)/'REF_INDEX      '/
      DATA JCMT_COMMENT(182)/'Mean atmospheric refractive index (alternative)                                 '/
      DATA FITS_TYPE   (182)/'GENERAL '/
      DATA FITS_NAME   (182)/'REFRAC  '/
*
      DATA NRAO_NAME   (183)/'C5DP           '/
      DATA JCMT_NAME   (183)/'DEW_POINT      '/
      DATA JCMT_COMMENT(183)/'Mean atmospheric dew point                                                      '/
      DATA FITS_TYPE   (183)/'GENERAL '/
      DATA FITS_NAME   (183)/'DEW_PT  '/
*
      DATA NRAO_NAME   (184)/'C5MM           '/
      DATA JCMT_NAME   (184)/'VAP_PRESSURE   '/
      DATA JCMT_COMMENT(184)/'Mean atmospheric vapour pressure                                                '/
      DATA FITS_TYPE   (184)/'GENERAL '/
      DATA FITS_NAME   (184)/'MMH2O   '/
*
      DATA NRAO_NAME   (185)/'c1ifs          '/
      DATA JCMT_NAME   (185)/'IF_DEVICE      '/
      DATA JCMT_COMMENT(185)/'Name of the IF device                                                           '/
      DATA FITS_TYPE   (185)/'GENERAL '/
      DATA FITS_NAME   (185)/'IFDEVICE'/
*
      DATA NRAO_NAME   (186)/'C1DP           '/
      DATA JCMT_NAME   (186)/'DATA_PRECISION '/
      DATA JCMT_COMMENT(186)/'Precision of the data from the backend                                          '/
      DATA FITS_TYPE   (186)/'GENERAL '/
      DATA FITS_NAME   (186)/'PRECIS  '/
*
      DATA NRAO_NAME   (187)/'C7OSN          '/
      DATA JCMT_NAME   (187)/'OBS_REF_SCAN   '/
      DATA JCMT_COMMENT(187)/'Calibration observation number (in which a standard was observed)               '/
      DATA FITS_TYPE   (187)/'GENERAL '/
      DATA FITS_NAME   (187)/'OFFSCAN '/
*
      DATA NRAO_NAME   (188)/'c1stc          '/
      DATA JCMT_NAME   (188)/'OBS_TYPE       '/
      DATA JCMT_COMMENT(188)/'Type of observation                                                             '/
      DATA FITS_TYPE   (188)/'GENERAL '/
      DATA FITS_NAME   (188)/'OBSTYPE '/
*
      DATA NRAO_NAME   (189)/'c6sd           '/
      DATA JCMT_NAME   (189)/'OBS_DIRECTION  '/
      DATA JCMT_COMMENT(189)/'Map rows are in X (horizontal) or Y(vertical) direction                         '/
      DATA FITS_TYPE   (189)/'GENERAL '/
      DATA FITS_NAME   (189)/'DIRECTN '/
*
      DATA NRAO_NAME   (190)/'c3nloops       '/
      DATA JCMT_NAME   (190)/'NO_SCANS       '/
      DATA JCMT_COMMENT(190)/'Number of scans per observation commanded at observation start                  '/
      DATA FITS_TYPE   (190)/'GENERAL '/
      DATA FITS_NAME   (190)/'NSCANS  '/
*
      DATA NRAO_NAME   (191)/'C7VC           '/
      DATA JCMT_NAME   (191)/'VEL_COR        '/
      DATA JCMT_COMMENT(191)/'Velocity correction                                                             '/
      DATA FITS_TYPE   (191)/'GENERAL '/
      DATA FITS_NAME   (191)/'RVSYS   '/
*
      DATA NRAO_NAME   (192)/'C7VRD          '/
      DATA JCMT_NAME   (192)/'VEL_DEF        '/
      DATA JCMT_COMMENT(192)/'Velocity definition code; method of computing the velocity                      '/
      DATA FITS_TYPE   (192)/'GENERAL '/
      DATA FITS_NAME   (192)/'VELDEF  '/
*
      DATA NRAO_NAME   (193)/'c7vref         '/
      DATA JCMT_NAME   (193)/'VEL_REF        '/
      DATA JCMT_COMMENT(193)/'Velocity reference code; reference point for telescope & source velocity        '/
      DATA FITS_TYPE   (193)/'GENERAL '/
      DATA FITS_NAME   (193)/'VELREF  '/
*
      DATA NRAO_NAME   (194)/'c7nif          '/
      DATA JCMT_NAME   (194)/'NO_IF_CH       '/
      DATA JCMT_COMMENT(194)/'Number of IF channels                                                           '/
      DATA FITS_TYPE   (194)/'GENERAL '/
      DATA FITS_NAME   (194)/'NOIFCHAN'/
*
      DATA NRAO_NAME   (195)/'c12gnorm       '/
      DATA JCMT_NAME   (195)/'G_NORM         '/
      DATA JCMT_COMMENT(195)/'Data normalisation factor                                                       '/
      DATA FITS_TYPE   (195)/'GENERAL '/
      DATA FITS_NAME   (195)/'GNORM   '/
*
      DATA NRAO_NAME   (196)/'c7cal          '/
      DATA JCMT_NAME   (196)/'CAL_TYPE       '/
      DATA JCMT_COMMENT(196)/'Calibration type (standard or direct, chopperwheel)                             '/
      DATA FITS_TYPE   (196)/'GENERAL '/
      DATA FITS_NAME   (196)/'TYPECAL '/
*
      DATA NRAO_NAME   (197)/'c12scan_vars1  '/
      DATA JCMT_NAME   (197)/'SCAN_VARS1     '/
      DATA JCMT_COMMENT(197)/'Names of the cols. of scan table1                                               '/
      DATA FITS_TYPE   (197)/'JCMT    '/
      DATA FITS_NAME   (197)/'SCANVRS1'/
*
      DATA NRAO_NAME   (198)/'c12scan_vars2  '/
      DATA JCMT_NAME   (198)/'SCAN_VARS2     '/
      DATA JCMT_COMMENT(198)/'Names of the cols. of scan table2                                               '/
      DATA FITS_TYPE   (198)/'JCMT    '/
      DATA FITS_NAME   (198)/'SCANVRS2'/
*
      DATA NRAO_NAME   (199)/'c12scan_table_1'/
      DATA JCMT_NAME   (199)/'SCAN_TABLE1    '/
      DATA JCMT_COMMENT(199)/'Begin scan table                                                                '/
      DATA FITS_TYPE   (199)/'JCMT    '/
      DATA FITS_NAME   (199)/'SCANTAB1'/
*
      DATA NRAO_NAME   (200)/'c12scan_table_2'/
      DATA JCMT_NAME   (200)/'SCAN_TABLE2    '/
      DATA JCMT_COMMENT(200)/'End scan table                                                                  '/
      DATA FITS_TYPE   (200)/'JCMT    '/
      DATA FITS_NAME   (200)/'SCANTAB2'/
*
      DATA NRAO_NAME   (201)/'c14phist       '/
      DATA JCMT_NAME   (201)/'MAP_TABLE      '/
      DATA JCMT_COMMENT(201)/'List of xy offsets for each scan                                                '/
      DATA FITS_TYPE   (201)/'JCMT    '/
      DATA FITS_NAME   (201)/'MAPTABLE'/
*
      DATA NRAO_NAME   (202)/'C11VD          '/
      DATA JCMT_NAME   (202)/'PHASE_VARS     '/
      DATA JCMT_COMMENT(202)/'Names of the cols. of phase table                                               '/
      DATA FITS_TYPE   (202)/'JCMT    '/
      DATA FITS_NAME   (202)/'VARDES  '/
*
      DATA NRAO_NAME   (203)/'c11pha         '/
      DATA JCMT_NAME   (203)/'PHASE_TABLE    '/
      DATA JCMT_COMMENT(203)/'Phase table: switching scheme dependent                                         '/
      DATA FITS_TYPE   (203)/'JCMT    '/
      DATA FITS_NAME   (203)/'PHASTB  '/
*
      DATA NRAO_NAME   (204)/'C3BESCONN      '/
      DATA JCMT_NAME   (204)/'BES_CONN       '/
      DATA JCMT_COMMENT(204)/'BE input channels connected to this section                                     '/
      DATA FITS_TYPE   (204)/'JCMT    '/
      DATA FITS_NAME   (204)/'BESCON  '/
*
      DATA NRAO_NAME   (205)/'C3BEINCON      '/
      DATA JCMT_NAME   (205)/'BE_IN_CONN     '/
      DATA JCMT_COMMENT(205)/'IF output channels connected to BE input channels                               '/
      DATA FITS_TYPE   (205)/'JCMT    '/
      DATA FITS_NAME   (205)/'BEINCON '/
*
      DATA NRAO_NAME   (206)/'C3LSPC         '/
      DATA JCMT_NAME   (206)/'NO_BES_O_CH    '/
      DATA JCMT_COMMENT(206)/'Number of channels per backend section                                          '/
      DATA FITS_TYPE   (206)/'JCMT    '/
      DATA FITS_NAME   (206)/'NOBESDCH'/
*
      DATA NRAO_NAME   (207)/'C3BESSPEC      '/
      DATA JCMT_NAME   (207)/'BES_SPECTRUM   '/
      DATA JCMT_COMMENT(207)/'Subsystem nr to which each backend section belongs.                             '/
      DATA FITS_TYPE   (207)/'JCMT    '/
      DATA FITS_NAME   (207)/'BESSPEC '/
*
      DATA NRAO_NAME   (208)/'C12CF          '/
      DATA JCMT_NAME   (208)/'BES_NUOBS      '/
      DATA JCMT_COMMENT(208)/'Centre frequencies (rest frame of source) [GHz]                                 '/
      DATA FITS_TYPE   (208)/'GENERAL '/
      DATA FITS_NAME   (208)/'OBSFREQ '/
*
      DATA NRAO_NAME   (209)/'C12RF          '/
      DATA JCMT_NAME   (209)/'BES_NUREST     '/
      DATA JCMT_COMMENT(209)/'Rest frequency [GHz]                                                            '/
      DATA FITS_TYPE   (209)/'GENERAL '/
      DATA FITS_NAME   (209)/'RESTFREQ'/
*
      DATA NRAO_NAME   (210)/'C3BEFENULO     '/
      DATA JCMT_NAME   (210)/'BES_FE_NULO    '/
      DATA JCMT_COMMENT(210)/'Copy of frontend LO frequency per backend section                               '/
      DATA FITS_TYPE   (210)/'JCMT    '/
      DATA FITS_NAME   (210)/'BEFENULO'/
*
      DATA NRAO_NAME   (211)/'C3BETOTIF      '/
      DATA JCMT_NAME   (211)/'BES_TOT_IF     '/
      DATA JCMT_COMMENT(211)/'Total IF per backend section                                                    '/
      DATA FITS_TYPE   (211)/'JCMT    '/
      DATA FITS_NAME   (211)/'BETOTIF '/
*
      DATA NRAO_NAME   (212)/'C3BEFESB       '/
      DATA JCMT_NAME   (212)/'BES_FE_SB_SIGN '/
      DATA JCMT_COMMENT(212)/'Copy of frontend sideband sign per backend section                              '/
      DATA FITS_TYPE   (212)/'JCMT    '/
      DATA FITS_NAME   (212)/'BEFESB  '/
*
      DATA NRAO_NAME   (213)/'C12INFREQ      '/
      DATA JCMT_NAME   (213)/'BE_NUIN        '/
      DATA JCMT_COMMENT(213)/'BE input frequencies [GHz]                                                      '/
      DATA FITS_TYPE   (213)/'JCMT    '/
      DATA FITS_NAME   (213)/'INFREQ  '/
*
      DATA NRAO_NAME   (214)/'C12FR          '/
      DATA JCMT_NAME   (214)/'BES_DELTANU    '/
      DATA JCMT_COMMENT(214)/'Frequency resolution [MHz]                                                      '/
      DATA FITS_TYPE   (214)/'GENERAL '/
      DATA FITS_NAME   (214)/'FREQRES '/
*
      DATA NRAO_NAME   (215)/'C12BW          '/
      DATA JCMT_NAME   (215)/'BES_BANDWIDTH  '/
      DATA JCMT_COMMENT(215)/'Bandwidth [MHz]                                                                 '/
      DATA FITS_TYPE   (215)/'GENERAL '/
      DATA FITS_NAME   (215)/'BW      '/
*
      DATA NRAO_NAME   (216)/'C12RT          '/
      DATA JCMT_NAME   (216)/'BES_T_REC      '/
      DATA JCMT_COMMENT(216)/'Receiver temperature                                                            '/
      DATA FITS_TYPE   (216)/'GENERAL '/
      DATA FITS_NAME   (216)/'TRX     '/
*
      DATA NRAO_NAME   (217)/'C12SST         '/
      DATA JCMT_NAME   (217)/'BES_T_SYS      '/
      DATA JCMT_COMMENT(217)/'System temperature                                                              '/
      DATA FITS_TYPE   (217)/'GENERAL '/
      DATA FITS_NAME   (217)/'STSYS   '/
*
      DATA NRAO_NAME   (218)/'C12TSKY        '/
      DATA JCMT_NAME   (218)/'BES_T_SKY      '/
      DATA JCMT_COMMENT(218)/'Sky temperature at last calibration                                             '/
      DATA FITS_TYPE   (218)/'JCMT    '/
      DATA FITS_NAME   (218)/'TSKY    '/
*
      DATA NRAO_NAME   (219)/'C12TTEL        '/
      DATA JCMT_NAME   (219)/'BES_T_TEL      '/
      DATA JCMT_COMMENT(219)/'Telescope temp. from last skydip                                                '/
      DATA FITS_TYPE   (219)/'JCMT    '/
      DATA FITS_NAME   (219)/'TTEL    '/
*
      DATA NRAO_NAME   (220)/'C12GAINS       '/
      DATA JCMT_NAME   (220)/'BES_GAIN       '/
      DATA JCMT_COMMENT(220)/'Gain value (kelvins per volt or equivalent)                                     '/
      DATA FITS_TYPE   (220)/'JCMT    '/
      DATA FITS_NAME   (220)/'GAINS   '/
*
      DATA NRAO_NAME   (221)/'C12CT          '/
      DATA JCMT_NAME   (221)/'BES_T_TEL      '/
      DATA JCMT_COMMENT(221)/'Calibration temperature                                                         '/
      DATA FITS_TYPE   (221)/'GENERAL '/
      DATA FITS_NAME   (221)/'TCAL    '/
*
      DATA NRAO_NAME   (222)/'C12WO          '/
      DATA JCMT_NAME   (222)/'BES_T_TEL      '/
      DATA JCMT_COMMENT(222)/'Water opacity                                                                   '/
      DATA FITS_TYPE   (222)/'GENERAL '/
      DATA FITS_NAME   (222)/'TAUH2O  '/
*
      DATA NRAO_NAME   (223)/'C12ETASKY      '/
      DATA JCMT_NAME   (223)/'BES_ETA_SKY    '/
      DATA JCMT_COMMENT(223)/'Sky transmission from last calibration                                          '/
      DATA FITS_TYPE   (223)/'JCMT    '/
      DATA FITS_NAME   (223)/'ETA_SKY '/
*
      DATA NRAO_NAME   (224)/'C12ALPHA       '/
      DATA JCMT_NAME   (224)/'BES_ALPHA      '/
      DATA JCMT_COMMENT(224)/'Ratio of signal sideband to image sideband sky transmission                     '/
      DATA FITS_TYPE   (224)/'JCMT    '/
      DATA FITS_NAME   (224)/'ALPHA   '/
*
      DATA NRAO_NAME   (225)/'C12GS          '/
      DATA JCMT_NAME   (225)/'BES_G_S        '/
      DATA JCMT_COMMENT(225)/'Normalizes signal sideband gain                                                 '/
      DATA FITS_TYPE   (225)/'JCMT    '/
      DATA FITS_NAME   (225)/'G_S     '/
*
      DATA NRAO_NAME   (226)/'C12ETATEL      '/
      DATA JCMT_NAME   (226)/'BES_ETA_TEL    '/
      DATA JCMT_COMMENT(226)/'Telescope transmission                                                          '/
      DATA FITS_TYPE   (226)/'JCMT    '/
      DATA FITS_NAME   (226)/'ETA_TEL '/
*
      DATA NRAO_NAME   (227)/'C12TSKYIM      '/
      DATA JCMT_NAME   (227)/'BES_T_SKY_IM   '/
      DATA JCMT_COMMENT(227)/'Frontend-derived Tsky, image sideband                                           '/
      DATA FITS_TYPE   (227)/'JCMT    '/
      DATA FITS_NAME   (227)/'T_SKY_IM'/
*
      DATA NRAO_NAME   (228)/'C12ETASKYIM    '/
      DATA JCMT_NAME   (228)/'BES_ETA_SKY_IM '/
      DATA JCMT_COMMENT(228)/'Frontend-derived sky transmission                                               '/
      DATA FITS_TYPE   (228)/'JCMT    '/
      DATA FITS_NAME   (228)/'ETA_SKY_'/
*
      DATA NRAO_NAME   (229)/'C12TSYSIM      '/
      DATA JCMT_NAME   (229)/'BES_T_SYS_IM   '/
      DATA JCMT_COMMENT(229)/'Frontend-derived Tsys, image sideband                                           '/
      DATA FITS_TYPE   (229)/'JCMT    '/
      DATA FITS_NAME   (229)/'T_SYS_IM'/
*
      DATA NRAO_NAME   (230)/'C12TASKY       '/
      DATA JCMT_NAME   (230)/'BES_TA_SKY     '/
      DATA JCMT_COMMENT(230)/'Ratio of signal sideband to image sideband sky transmission                     '/
      DATA FITS_TYPE   (230)/'JCMT    '/
      DATA FITS_NAME   (230)/'TA_SKY  '/
*
      DATA NRAO_NAME   (231)/'C3INTT         '/
      DATA JCMT_NAME   (231)/'INTGRN_TIME    '/
      DATA JCMT_COMMENT(231)/'Scan integration time                                                           '/
      DATA FITS_TYPE   (231)/'JCMT    '/
      DATA FITS_NAME   (231)/'INTGR   '/
*
      DATA NRAO_NAME   (232)/'C13DAT         '/
      DATA JCMT_NAME   (232)/'DATA           '/
      DATA JCMT_COMMENT(232)/'Spectrum data                                                                   '/
      DATA FITS_TYPE   (232)/'GENERAL '/
      DATA FITS_NAME   (232)/'SPECT   '/
*
      DATA NRAO_NAME   (233)/'C12CM          '/
      DATA JCMT_NAME   (233)/'BES_CORR_MODE  '/
      DATA JCMT_COMMENT(233)/'Correlation function mode                                                       '/
      DATA FITS_TYPE   (233)/'GENERAL '/
      DATA FITS_NAME   (233)/'CM      '/
*
      DATA NRAO_NAME   (234)/'C12BM          '/
      DATA JCMT_NAME   (234)/'BES_BITMODE    '/
      DATA JCMT_COMMENT(234)/'Correlation bit mode                                                            '/
      DATA FITS_TYPE   (234)/'GENERAL '/
      DATA FITS_NAME   (234)/'BM      '/
*
      DATA NRAO_NAME   (235)/'C3OVERLAP      '/
      DATA JCMT_NAME   (235)/'BES_OVERLAP    '/
      DATA JCMT_COMMENT(235)/'Subband overlap                                                                 '/
      DATA FITS_TYPE   (235)/'JCMT    '/
      DATA FITS_NAME   (235)/'OVERLAP '/
*
      DATA NRAO_NAME   (236)/'C12CF          '/
      DATA JCMT_NAME   (236)/'FE_NUOBS       '/
      DATA JCMT_COMMENT(236)/'Centre frequency                                                                '/
      DATA FITS_TYPE   (236)/'GENERAL '/
      DATA FITS_NAME   (236)/'OBSFREQ '/
*
      DATA NRAO_NAME   (237)/'C12RF          '/
      DATA JCMT_NAME   (237)/'FE_NUREST      '/
      DATA JCMT_COMMENT(237)/'Rest frequency                                                                  '/
      DATA FITS_TYPE   (237)/'GENERAL '/
      DATA FITS_NAME   (237)/'RESTFREQ'/
*
      DATA NRAO_NAME   (238)/'C12BW          '/
      DATA JCMT_NAME   (238)/'BANDWIDTH      '/
      DATA JCMT_COMMENT(238)/'Bandwidth                                                                       '/
      DATA FITS_TYPE   (238)/'GENERAL '/
      DATA FITS_NAME   (238)/'BW      '/
*
      DATA NRAO_NAME   (239)/'C12RT          '/
      DATA JCMT_NAME   (239)/'TREC_TRANS     '/
      DATA JCMT_COMMENT(239)/'Receiver temperature                                                            '/
      DATA FITS_TYPE   (239)/'GENERAL '/
      DATA FITS_NAME   (239)/'TRX     '/
*
      DATA NRAO_NAME   (240)/'C12SST         '/
      DATA JCMT_NAME   (240)/'TSYS_ON        '/
      DATA JCMT_COMMENT(240)/'Source system temperature                                                       '/
      DATA FITS_TYPE   (240)/'GENERAL '/
      DATA FITS_NAME   (240)/'STSYS   '/
*
      DATA NRAO_NAME   (241)/'C12RST         '/
      DATA JCMT_NAME   (241)/'TSYS_OFF       '/
      DATA JCMT_COMMENT(241)/'Reference system temperature                                                    '/
      DATA FITS_TYPE   (241)/'GENERAL '/
      DATA FITS_NAME   (241)/'RTSYS   '/
*
      DATA NRAO_NAME   (242)/'c12noi         '/
      DATA JCMT_NAME   (242)/'THERMAL_NOISE  '/
      DATA JCMT_COMMENT(242)/'Noise value                                                                     '/
      DATA FITS_TYPE   (242)/'JCMT    '/
      DATA FITS_NAME   (242)/'NOISE   '/
*
      DATA NRAO_NAME   (243)/'c12tsky        '/
      DATA JCMT_NAME   (243)/'TSKY_TRANS     '/
      DATA JCMT_COMMENT(243)/'Sky temperature at last calibration                                             '/
      DATA FITS_TYPE   (243)/'JCMT    '/
      DATA FITS_NAME   (243)/'TSKY    '/
*
      DATA NRAO_NAME   (244)/'c12ttel        '/
      DATA JCMT_NAME   (244)/'TTEL_TRANS     '/
      DATA JCMT_COMMENT(244)/'Telescope temp. from last skydip                                                '/
      DATA FITS_TYPE   (244)/'JCMT    '/
      DATA FITS_NAME   (244)/'TTEL    '/
*
      DATA NRAO_NAME   (245)/'c12sbrat       '/
      DATA JCMT_NAME   (245)/'FE_SB_RATIO    '/
      DATA JCMT_COMMENT(245)/'Sideband ratio                                                                  '/
      DATA FITS_TYPE   (245)/'JCMT    '/
      DATA FITS_NAME   (245)/'SBRATIO '/
*
      DATA NRAO_NAME   (246)/'c12gains       '/
      DATA JCMT_NAME   (246)/'GAIN_TRANS     '/
      DATA JCMT_COMMENT(246)/'Gains                                                                           '/
      DATA FITS_TYPE   (246)/'JCMT    '/
      DATA FITS_NAME   (246)/'GAINS   '/
*
      DATA NRAO_NAME   (247)/'C12CT          '/
      DATA JCMT_NAME   (247)/'TCAL_TRANS     '/
      DATA JCMT_COMMENT(247)/'Calibration temperature                                                         '/
      DATA FITS_TYPE   (247)/'GENERAL '/
      DATA FITS_NAME   (247)/'TCAL    '/
*
      DATA NRAO_NAME   (248)/'C12WO          '/
      DATA JCMT_NAME   (248)/'H2O_OPACITY    '/
      DATA JCMT_COMMENT(248)/'Water opacity                                                                   '/
      DATA FITS_TYPE   (248)/'GENERAL '/
      DATA FITS_NAME   (248)/'TAUH2O  '/
*
      DATA NRAO_NAME   (249)/'C13SPV         '/
      DATA JCMT_NAME   (249)/'SAMPLES        '/
      DATA JCMT_COMMENT(249)/'Raw data                                                                        '/
      DATA FITS_TYPE   (249)/'JCMT    '/
      DATA FITS_NAME   (249)/'RAWSPECT'/
*
      DATA NRAO_NAME   (250)/'c13dat         '/
      DATA JCMT_NAME   (250)/'DATA           '/
      DATA JCMT_COMMENT(250)/'Reduced data                                                                    '/
      DATA FITS_TYPE   (250)/'GENERAL '/
      DATA FITS_NAME   (250)/'SPECT   '/
*
      DATA NRAO_NAME   (251)/'C12CF          '/
      DATA JCMT_NAME   (251)/'NUOBS          '/
      DATA JCMT_COMMENT(251)/'Observing frequency; FITS: [Hz]; GSD: [GHz]                                     '/
      DATA FITS_TYPE   (251)/'GENERAL '/
      DATA FITS_NAME   (251)/'OBSFREQ '/
*
      DATA NRAO_NAME   (252)/'C12RF          '/
      DATA JCMT_NAME   (252)/'NUREST         '/
      DATA JCMT_COMMENT(252)/'Rest frequency; FITS: [Hz]; GSD: [GHz]                                          '/
      DATA FITS_TYPE   (252)/'GENERAL '/
      DATA FITS_NAME   (252)/'RSTFREQ '/
*
      DATA NRAO_NAME   (253)/'C12FR          '/
      DATA JCMT_NAME   (253)/'SPC_FACTOR     '/
      DATA JCMT_COMMENT(253)/'Frequency resolution; FITS: [Hz]; GSD: [MHz]                                    '/
      DATA FITS_TYPE   (253)/'GENERAL '/
      DATA FITS_NAME   (253)/'FREQRES '/
*
      DATA NRAO_NAME   (254)/'C12BW          '/
      DATA JCMT_NAME   (254)/'BANDWI         '/
      DATA JCMT_COMMENT(254)/'Bandwidth; FITS: [Hz]; GSD: [MHz]                                               '/
      DATA FITS_TYPE   (254)/'GENERAL '/
      DATA FITS_NAME   (254)/'BW      '/
*
      DATA NRAO_NAME   (255)/'C12CT          '/
      DATA JCMT_NAME   (255)/'TCAL           '/
      DATA JCMT_COMMENT(255)/'Calibration temperature                                                         '/
      DATA FITS_TYPE   (255)/'GENERAL '/
      DATA FITS_NAME   (255)/'TCAL    '/
*
      DATA NRAO_NAME   (256)/'C12WO          '/
      DATA JCMT_NAME   (256)/'H2O            '/
      DATA JCMT_COMMENT(256)/'Water opacity                                                                   '/
      DATA FITS_TYPE   (256)/'GENERAL '/
      DATA FITS_NAME   (256)/'TAUH2O  '/
*
      DATA NRAO_NAME   (257)/'C13SPV         '/
      DATA JCMT_NAME   (257)/'SAMPLES        '/
      DATA JCMT_COMMENT(257)/'Individual beam integrations                                                    '/
      DATA FITS_TYPE   (257)/'JCMT    '/
      DATA FITS_NAME   (257)/'RAWSPECT'/
*
      DATA NRAO_NAME   (258)/'c13raw_error   '/
      DATA JCMT_NAME   (258)/'RAW_ERROR      '/
      DATA JCMT_COMMENT(258)/'Raw error is accumulated over the scan, so store at end scan                    '/
      DATA FITS_TYPE   (258)/'JCMT    '/
      DATA FITS_NAME   (258)/'RAWERROR'/
*
      DATA NRAO_NAME   (259)/'C13SPV_OP      '/
      DATA JCMT_NAME   (259)/'SAMPLES_OP     '/
      DATA JCMT_COMMENT(259)/'Raw out of phase data samples in each phase                                     '/
      DATA FITS_TYPE   (259)/'JCMT    '/
      DATA FITS_NAME   (259)/'RAWSPECT'/
*
      DATA NRAO_NAME   (260)/'c13raw_error_op'/
      DATA JCMT_NAME   (260)/'RAW_ERROR_OP   '/
      DATA JCMT_COMMENT(260)/'Raw (out of phase) error also to be stored at end scan                          '/
      DATA FITS_TYPE   (260)/'JCMT    '/
      DATA FITS_NAME   (260)/'RAWERROR'/
*
      DATA NRAO_NAME   (261)/'c13dat         '/
      DATA JCMT_NAME   (261)/'DATA           '/
      DATA JCMT_COMMENT(261)/'Reduced photometric value                                                       '/
      DATA FITS_TYPE   (261)/'GENERAL '/
      DATA FITS_NAME   (261)/'SPECT   '/
*
      DATA NRAO_NAME   (262)/'c13resp        '/
      DATA JCMT_NAME   (262)/'RESP           '/
      DATA JCMT_COMMENT(262)/'array of responsivities                                                         '/
      DATA FITS_TYPE   (262)/'JCMT    '/
      DATA FITS_NAME   (262)/'RESP    '/
*
      DATA NRAO_NAME   (263)/'c13std         '/
      DATA JCMT_NAME   (263)/'STDEV          '/
      DATA JCMT_COMMENT(263)/'Phase data standard deviation                                                   '/
      DATA FITS_TYPE   (263)/'JCMT    '/
      DATA FITS_NAME   (263)/'STDSPECT'/
*
      DATA NRAO_NAME   (264)/'c13err         '/
      DATA JCMT_NAME   (264)/'ERROR          '/
      DATA JCMT_COMMENT(264)/'Standard error                                                                  '/
      DATA FITS_TYPE   (264)/'GENERAL '/
      DATA FITS_NAME   (264)/'TRMS    '/
*
      DATA NRAO_NAME   (265)/'C12CF          '/
      DATA JCMT_NAME   (265)/'FE_NUOBS       '/
      DATA JCMT_COMMENT(265)/'Centre frequency                                                                '/
      DATA FITS_TYPE   (265)/'GENERAL '/
      DATA FITS_NAME   (265)/'OBSFREQ '/
*
      DATA NRAO_NAME   (266)/'C12RF          '/
      DATA JCMT_NAME   (266)/'FE_NUREST      '/
      DATA JCMT_COMMENT(266)/'Rest frequency                                                                  '/
      DATA FITS_TYPE   (266)/'GENERAL '/
      DATA FITS_NAME   (266)/'RESTFREQ'/
*
      DATA NRAO_NAME   (267)/'C12FR          '/
      DATA JCMT_NAME   (267)/'DELTANU        '/
      DATA JCMT_COMMENT(267)/'Frequency resolution [MHz]                                                      '/
      DATA FITS_TYPE   (267)/'GENERAL '/
      DATA FITS_NAME   (267)/'FREQRES '/
*
      DATA NRAO_NAME   (268)/'C12BW          '/
      DATA JCMT_NAME   (268)/'BANDWIDTH      '/
      DATA JCMT_COMMENT(268)/'Bandwidth                                                                       '/
      DATA FITS_TYPE   (268)/'GENERAL '/
      DATA FITS_NAME   (268)/'BW      '/
*
      DATA NRAO_NAME   (269)/'C12RT          '/
      DATA JCMT_NAME   (269)/'TREC           '/
      DATA JCMT_COMMENT(269)/'Receiver temperature                                                            '/
      DATA FITS_TYPE   (269)/'GENERAL '/
      DATA FITS_NAME   (269)/'TRX     '/
*
      DATA NRAO_NAME   (270)/'C12SST         '/
      DATA JCMT_NAME   (270)/'TSYS_ON        '/
      DATA JCMT_COMMENT(270)/'Source system temperature                                                       '/
      DATA FITS_TYPE   (270)/'GENERAL '/
      DATA FITS_NAME   (270)/'STSYS   '/
*
      DATA NRAO_NAME   (271)/'C12RST         '/
      DATA JCMT_NAME   (271)/'TSYS_OFF       '/
      DATA JCMT_COMMENT(271)/'Reference system temperature                                                    '/
      DATA FITS_TYPE   (271)/'GENERAL '/
      DATA FITS_NAME   (271)/'RTSYS   '/
*
      DATA NRAO_NAME   (272)/'c12noi         '/
      DATA JCMT_NAME   (272)/'NOISE          '/
      DATA JCMT_COMMENT(272)/'Noise value                                                                     '/
      DATA FITS_TYPE   (272)/'JCMT    '/
      DATA FITS_NAME   (272)/'NOISE   '/
*
      DATA NRAO_NAME   (273)/'c12tsky        '/
      DATA JCMT_NAME   (273)/'TSKY           '/
      DATA JCMT_COMMENT(273)/'Sky temperature at last calibration                                             '/
      DATA FITS_TYPE   (273)/'JCMT    '/
      DATA FITS_NAME   (273)/'TSKY    '/
*
      DATA NRAO_NAME   (274)/'c12ttel        '/
      DATA JCMT_NAME   (274)/'TTEL           '/
      DATA JCMT_COMMENT(274)/'Telescope temp. from last skydip                                                '/
      DATA FITS_TYPE   (274)/'JCMT    '/
      DATA FITS_NAME   (274)/'TTEL    '/
*
      DATA NRAO_NAME   (275)/'c12sbrat       '/
      DATA JCMT_NAME   (275)/'BE_SB_RATIO    '/
      DATA JCMT_COMMENT(275)/'Sideband ratio                                                                  '/
      DATA FITS_TYPE   (275)/'JCMT    '/
      DATA FITS_NAME   (275)/'SBRATIO '/
*
      DATA NRAO_NAME   (276)/'c12gains       '/
      DATA JCMT_NAME   (276)/'GAIN           '/
      DATA JCMT_COMMENT(276)/'Gains                                                                           '/
      DATA FITS_TYPE   (276)/'JCMT    '/
      DATA FITS_NAME   (276)/'GAINS   '/
*
      DATA NRAO_NAME   (277)/'C12CT          '/
      DATA JCMT_NAME   (277)/'TCAL           '/
      DATA JCMT_COMMENT(277)/'Calibration temperature                                                         '/
      DATA FITS_TYPE   (277)/'GENERAL '/
      DATA FITS_NAME   (277)/'TCAL    '/
*
      DATA NRAO_NAME   (278)/'C12WO          '/
      DATA JCMT_NAME   (278)/'H2O_OPACITY    '/
      DATA JCMT_COMMENT(278)/'Water opacity                                                                   '/
      DATA FITS_TYPE   (278)/'GENERAL '/
      DATA FITS_NAME   (278)/'TAUH2O  '/
*
      DATA NRAO_NAME   (279)/'C13SPV         '/
      DATA JCMT_NAME   (279)/'SAMPLES        '/
      DATA JCMT_COMMENT(279)/'Raw data                                                                        '/
      DATA FITS_TYPE   (279)/'JCMT    '/
      DATA FITS_NAME   (279)/'RAWSPECT'/
*
      DATA NRAO_NAME   (280)/'c13dat         '/
      DATA JCMT_NAME   (280)/'DATA           '/
      DATA JCMT_COMMENT(280)/'Reduced data                                                                    '/
      DATA FITS_TYPE   (280)/'GENERAL '/
      DATA FITS_NAME   (280)/'SPECT   '/
*
      DATA NRAO_NAME   (281)/'C7HP           '/
      DATA JCMT_NAME   (281)/'FWHM           '/
      DATA JCMT_COMMENT(281)/'FWHM of the beam profile (mean)                                                 '/
      DATA FITS_TYPE   (281)/'        '/
      DATA FITS_NAME   (281)/'        '/
*
      DATA NRAO_NAME   (282)/'c12grec        '/
      DATA JCMT_NAME   (282)/'GREC           '/
      DATA JCMT_COMMENT(282)/'Raw data units per Kelvin                                                       '/
      DATA FITS_TYPE   (282)/'        '/
      DATA FITS_NAME   (282)/'        '/
*
      DATA NRAO_NAME   (283)/'C12VHOT        '/
      DATA JCMT_NAME   (283)/'IF_V_HOT       '/
      DATA JCMT_COMMENT(283)/'                                                                                '/
      DATA FITS_TYPE   (283)/'JCMT    '/
      DATA FITS_NAME   (283)/'VHOT    '/
*
      DATA NRAO_NAME   (284)/'C12VSKY        '/
      DATA JCMT_NAME   (284)/'IF_V_SKY       '/
      DATA JCMT_COMMENT(284)/'                                                                                '/
      DATA FITS_TYPE   (284)/'JCMT    '/
      DATA FITS_NAME   (284)/'VSKY    '/
*
      DATA NRAO_NAME   (285)/'C12VCOLD       '/
      DATA JCMT_NAME   (285)/'IF_V_COLD      '/
      DATA JCMT_COMMENT(285)/'                                                                                '/
      DATA FITS_TYPE   (285)/'JCMT    '/
      DATA FITS_NAME   (285)/'VCOLD   '/
*
      DATA NRAO_NAME   (286)/'C13SPV         '/
      DATA JCMT_NAME   (286)/'SAMPLES        '/
      DATA JCMT_COMMENT(286)/'                                                                                '/
      DATA FITS_TYPE   (286)/'JCMT    '/
      DATA FITS_NAME   (286)/'RAWSPECT'/
*
      DATA NRAO_NAME   (287)/'c13raw_error   '/
      DATA JCMT_NAME   (287)/'DATA_ERROR     '/
      DATA JCMT_COMMENT(287)/'                                                                                '/
      DATA FITS_TYPE   (287)/'JCMT    '/
      DATA FITS_NAME   (287)/'RAWERROR'/
