.TITLE		ANT		ADAM network system
.FACILITY	ANT,111/PREFIX=ANT__
.IDENT		'Version 2.00'
!author		REVAD:BDK 24Mar8 (B.D.Kelly)

.SEVERITY	INFORMATIONAL
.BASE 100

TOOMANY		<attempt to open too many network links>
NETSHUT		<ADAM network process closing down>
CONTEND		<two tasks opening a network link simultaneously>
REJECT		<attempt to open a network link rejected>
REMESNUM	<transaction list full in remote ADAMNET>
NOPATH		<nonexistent network path>
UNKUNIT		<system error - attempt to close unknown NET unit>
IVNETIN		<invalid NET_IN type received>
IVMESSOUT	<invalid MESS_OUT message type>
IVNETACK	<invalid NETACK message received>
IVCOMP		<invalid ack to net connection request received>
IVPATH		<invalid network path number>
IVMSG		<invalid REM_MSG_OUT received>
IVEND		<invalid REM GSOC_END received>
IVDEINIT	<invalid REM_DEINIT_OUT received>
IVSTART		<invalid REM_GSOC_START_OUT received>


.END
