.TITLE       FIO
.FACILITY    FIO,361/PREFIX=FIO__


.SEVERITY	INFORMATIONAL

.BASE		100
TOOFD	<No more available file descriptors>
ILLFD	<Illegal file descriptor>
TOMNY	<Too many open files>
ILLAC	<Illegal access mode>
ILLOP	<Illegal open request>
ILLCL	<Illegal close request>
NTOPN	<File not open>
NOTFD	<File not found>
OPNER	<File open error>
NAMER	<File name error>
CLSER	<File close error>
DUPFL	<Duplicate file>
CRTER	<File create error>
DLTER	<File delete error>
RDER	<File read error>
WRTER	<File write error>
IVACM	<Invalid access mode>
EOF	<End of file>
REDON	<File is readonly>
RECTL	<Record too long>
ALOPN	<File already open>
NOUNT	<No more unit numbers available>
IVUNT	<Invalid unit number>
OLORG	<Illegal origin>
OUTFL	<Outside file>
ERROR	<Error>
NTSUP	<Option not supported yet>
SYNAM	<Syntax error in NAMELIST input>
TOOMV	<Too many values for NAMELIST variable>
INVRV	<Invalid reference to variable>
REWER	<REWIND error>
BACER	<BACKSPACE error>
OPREQ	<OPEN or DEFINE FILE required>
TOORC	<Too many records in I/O statement>
FILNF	<File not found>
MIXFL	<Mixed file access modes>
ENDFL	<ENDFILE error>
SEGRC	<Segmented record format error>
INCRC	<Inconsistent record length>
RECIO	<Recursive I/O operation>
INSVR	<Insufficient virtual memory>
NODEV	<No such device>
INCRT	<Inconsistent record type>
KEYVL	<Keyword value error in OPEN statement>
INCOC	<Inconsistent OPEN/CLOSE parameters>
INVRG	<Invalid argument to FORTRAN Run-Time Library>
INVKY	<Invalid key specification>
INCKC	<Inconsistent key change or duplicate key>
INCRG	<Inconsistent file organization>
SPLOC	<Specified record locked>
NOCRC	<No current record>
REWRT	<REWRITE error>
UNLER	<UNLOCK error>
FINER	<FIND error>
LISYN	<List-directed I/O syntax error>
INFOR	<Infinite format loop>
FORVR	<Format/variable-type mismatch>
SYNER	<Syntax error in format>
OUTCN	<Output conversion error>
INPCN	<Input conversion error>
OUTOV	<Output statement overflows record>
INREQ	<Input statement requires too much data>
VFVAL	<Variable format expression value error>
UNKPA	<Parameter is not a file parameter>
TOOFP	<File parameter table full>
ISACT	<File parameter is active>
EREXH	<Error establishing exit handler for FIO>
INVMK	<Invalid key match specifier>
PTAFD	<Permission to access file denied>
COEXI	<Cannot overwrite existing file>
IVFMT	<Invalid FORMAT option>
FDNFP	<File descriptor does not have an associated file parameter descriptor>
INVRL	<Invalid record length>
OSERR	<General operating system error code>

.BASE		176
ERFMT	<Error in format>
ILLUN	<Illegal unit number>
FIONA	<Formatted I/O not allowed>
UIONA	<Unformatted I/O not allowed>
DIONA	<Direct I/O not allowed>
SIONA	<Sequential I/O not allowed>
CNTBF	<Cannot backspace file>
OFBOR	<Off beginning of record>
CNTSF	<Can't stat file>
NAARC	<No * after repeat count>
OFEOR	<Off end of record>
TRUNF	<Truncation failed>
ILSTI	<Incomprehensible list input>
OOFSP	<Out of free space>
UNTNC	<Unit not connected>
RUNCH	<Read unexpected character>
BLINP	<Blank logical input field>
NFEXI	<'NEW' file exists>
CFOLF	<Cannot find 'OLD' file>
UNKNO	<Unknown system error>
REQSA	<Requires seek ability>
ILARG	<Illegal argument>
NEGRC	<Negative repeat count>
ILOPU	<Illegal operaton for unit>
TOOMF	<Too many file open - no free descriptors>
UNTNO	<Attempted operation on unit that is not open>
IINAM	<Illegal input for namelist>
FILEO	<Error in FILEOPT parameter>
PERMD	<Permission denied>
FTOOL	<File too large>
NSLOD	<No space left on device>
FNTL	<File name too long>
DQEXC	<Disk quota exceeded>
ILINP	<Illegal logical input field>
INSPE	<Incompatible specifiers in open>
.END
