/*
 *+
 *  Name:
 *    make-errno-par

 *  Type of module:
 *     C source

 *  Purpose:
 *     Generate internal Fortran errno header file

 *  Description:
 *     Generate a fortran-compatible include file containing
 *     the errno codes relevant to the FIO package. This is only
 *     relevant on systems that use errno codes to report file
 *     error conditions. The resulting output file is called ERRNO_PAR

 *  Usage:
 *
 *       ./make-errno-par

 *  Authors:
 *     TIMJ: Tim Jenness (JAC, Hawaii)
 *     {enter_new_authors_here}

 *  History:
 *     21-Jul-2004 (TIMJ):
 *        Original version

 *-
 */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include <stdio.h>

#if HAVE_ERRNO_H
# include <errno.h>
#endif

#if HAVE_TIME_H
# include <time.h>
#endif

#define INCLUDE_FILE  "ERRNO_PAR"

/* internal declarations */
const char* todaysdate(void);


int main (int argc, char ** argv) {
  char * progname = argv[0];
  FILE * OutputFile;

  /* Open the output file */
  OutputFile = fopen(INCLUDE_FILE,"w");
  if (!OutputFile) {
    fprintf(stderr,"%: can't open file %s for output\n",
	    progname, INCLUDE_FILE);
    exit(1);
  }
    
  /* Start writing the include file. Begin with the header */
        fprintf(OutputFile,
"*+\n"
"*  Name:\n"
"*     ERRNO_PAR\n"
"\n"
"*  Type of Module:\n"
"*     Fortran include file.\n"
"\n"
"*  Purpose:\n"
"*     Define private C ERRNO constants for the Fortran FIO system.\n"
"\n"
"*  Description:\n"
"*     This file defines private C ERRNO constants for the\n"
"*     FIO system. Required by fio1_serr.f in some cases (eg linux).\n"
"\n"
"*  Authors:\n"
"*     TIMJ: Tim Jenness (JAC, Hawaii)\n"
"*     %s program\n"
"\n"
"*  History:\n"
"*     22-JUL-2004 (TIMJ):\n"
"*        Original version of C program (via auto-generation).\n"
"*     %s (%s):\n"
"*        Generated\n"
"*     No further changes -- do not edit this file\n"
"\n"
"*-\n"
"\n",
		progname, todaysdate(), progname);

	


}

/* Insert code for a specific errno constant */
void add_line( FILE * file, char * string, int constant) {


} 


/* Stolen from make-prm-par.c */
const char *todaysdate(void)
{
#if HAVE_TIME_H
    static char s[12];
    time_t t = time(0);

    strftime(s, sizeof(s), "%d-%b-%Y", localtime(&t));
    return s;
#else
    return "TODAY";
#endif
}
