.TITLE       SGS
.FACILITY    SGS,250/PREFIX=SGS__


.SEVERITY	INFORMATIONAL

.BASE		100
TOOZD	<No more available zone descriptors>
ILLZD	<Unused error code>
TOMNY	<Unused error code>
ILLAC	<Illegal access mode>
UNKPA	<Parameter not found>
NTACT	<Unused error code>
ISACT	<Parameter currently active>
EXCPA	<Unused error code>
ERACT	<Unused error code>
EREXH	<Unused error code>
BADWK	<Bad Workstation name>
ZNOUT	<New zone not inside current zone>
WRKEX	<Too many Workstations>
GKSER	<GKS error>
ZNZEX	<Too many zones>
UNOPN	<Workstation could not be opened>
ZONTB	<Requested zone bigger than current zone>
INVZN	<Invalid zone id>
ZONNF	<Specified zone does not exist>
ZEREX	<Zero extent>
ZONNB	<Specified zone is not a base zone>
SVCRP	<Save data is corrupt>
UNRES	<Unused error code>
LCERR	<Unused error code>
CRERR	<Unused error code>
CNERR	<Unused error code>
WRERR	<Unused error code>
RDERR	<Unused error code>
DVERR	<Unused error code>
BADWT	<Bad Workstation type>
INQER	<Error returned by GKS inquiry routine>
GNSER	<Error returned by GNS routine>
PENER	<SGS pen does not exist>
SURFN	<Display surface is not empty>
SGSER	<Unspecified SGS Error>
OZEWK	<Other zone on workstation>
FLSWN	<Failed to set window>
UCRNZ	<Unable to create new zone>
.END
