      SUBROUTINE CCD1_CRGR( WEIGHT, NW, NNODES, GRAPH, NEDGES, STATUS )
*+
*  Name:
*     CCD1_CRGR

*  Purpose:
*     Creates a graph of edges for CCDOFF intercomparisons.

*  Language:
*     Starlink FORTRAN 77

*  Invocation:
*     CALL CCD1_CRGR( WEIGHT, NW, NNODES, GRAPH, NEDGES, STATUS )

*  Description:
*     This routine generates a graph expressed as a series of edges and
*     weights, from the information generated by intercomparing
*     positions lists.

*  Arguments:
*     WEIGHT( NW ) = INTEGER (Given)
*        The weights associated  with the edges of the graph. These are
*        the numbers of point-pairs successfully matched between the
*        position lists (nodes). A null weight is indicated by a value
*        of zero.
*     NW = INTEGER (Given)
*        The number of weights given
*     NNODES = INTEGER (Given)
*        The number of nodes whose positions were intercompared to
*        generate the weighting data. The intercomaprison loop is
*        assumed to be of the form.
*             do i = 1, nnodes - 1
*                do j = i + 1, nnodes
*                enddo
*             enddo
*        This is essential if the node numbers in the graph edges are
*        to be correct.
*     GRAPH( 4, * ) = INTEGER (Returned)
*        The graph with the nodes numbers (positions (1,*) and (2,*) )
*        of the edge, (3,*) the associated weights, and (4,*) the index
*        into any associated data created during the intercomparison.
*     NEDGE = INTEGER (Returned)
*        The number of valid edges entered into the graph.
*     STATUS = INTEGER (Given and Returned)
*        The global status.

*  Copyright:
*     Copyright (C) 1992 Science & Engineering Research Council. All
*     Rights Reserved.

*  Licence:
*     This program is free software; you can redistribute it and/or
*     modify it under the terms of the GNU General Public License as
*     published by the Free Software Foundation; either version 2 of
*     the License, or (at your option) any later version.
*
*     This program is distributed in the hope that it will be
*     useful, but WITHOUT ANY WARRANTY; without even the implied
*     warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
*     PURPOSE. See the GNU General Public License for more details.
*
*     You should have received a copy of the GNU General Public License
*     along with this program; if not, write to the Free Software
*     Foundation, Inc., 51 Franklin Street,Fifth Floor, Boston, MA
*     02110-1301, USA

*  Authors:
*     PDRAPER: Peter Draper (STARLINK)
*     {enter_new_authors_here}

*  History:
*     10-DEC-1992 (PDRAPER):
*        Original version.
*     {enter_changes_here}

*  Bugs:
*     {note_any_bugs_here}

*-

*  Type Definitions:
      IMPLICIT NONE              ! No implicit typing

*  Global Constants:
      INCLUDE 'SAE_PAR'          ! Standard SAE constants

*  Arguments Given:
      INTEGER NW
      INTEGER WEIGHT( NW )
      INTEGER NNODES

*  Arguments Returned:
      INTEGER GRAPH( 4, * )
      INTEGER NEDGES

*  Status:
      INTEGER STATUS             ! Global status

*  Local Variables:
      INTEGER I, J               ! Loop variables
      INTEGER COUNT              ! Absolute count into intercomparison
                                 ! loop

*.

*  Check inherited global status.
      IF ( STATUS .NE. SAI__OK ) RETURN

*  Create the graph of position intercomparisons. The nodes are the
*  index of the positions lists and the weighting the number of
*  positions successfully matched between the lists.
      NEDGES = 0
      COUNT = 0
      DO 1 I = 1, NNODES - 1
         DO 2 J = I + 1, NNODES
            COUNT = COUNT + 1
            IF ( WEIGHT( COUNT ) .GT. 0 ) THEN
               NEDGES = NEDGES + 1
               GRAPH( 1, NEDGES ) = I
               GRAPH( 2, NEDGES ) = J
               GRAPH( 3, NEDGES ) = WEIGHT( COUNT )
               GRAPH( 4, NEDGES ) = COUNT
            END IF
 2       CONTINUE
 1    CONTINUE
      END
* $Id$
