.TITLE       MAG
.FACILITY    MAG,330/PREFIX=MAG__


.SEVERITY	INFORMATIONAL

.BASE		100
TOOTD	<No more available tape descriptors>
ILLTD	<Illegal tape descriptor>
TOMNY	<Too many open tapes>
ILLAC	<Illegal access mode>
UNKPA	<Parameter not found>
NTACT	<Parameter not currently active>
ISACT	<Parameter currently active>
ERACT	<Error activating MAG>
EREXH	<Error establishing exit handler for MAG>
IVACM	<Invalid access mode>
BUFTB	<Invalid buffer size>
UNKDV	<Unable to locate device in DEVDATASET>
NOASS	<No channel assigned to tape drive>
NOFIL	<No tape file specified>
NOPOS	<Tape position not known>
NOEOV	<End of volume not found>
EXCDV	<Too many tape devices>
ISOPN	<Tape device already open>
NTOPN	<Tape not open>
LCERR	<Unable to open DEVDATASET>
CRERR	<Unable to create Magnetic Tape dataset>
CNERR	<Unable to cancel Magnetic Tape dataset>
WRERR	<Error Writing to Magnetic Tape dataset>
RDERR	<Error Reading from Magnetic Tape dataset>
IVRSZ	<Invalid record size>
IVBSZ	<Invalid block size>
NTMUL	<Block size not a multiple of record size>
IVBUF	<Invalid buffer size>
ICBSZ	<Inconsistent block size>
NOREC	<Unknown record size>
ERROR	<Error>
NTSUP	<Option not supported>
DVALL	<Tape drive allocated to another user>
DVNAL	<Tape drive not allocated>
NSHDV	<No such tape drive>
DVASS	<Tape drive already assigned>
ACVIO	<Access violation>
BUFOV	<Buffer overflow>
DVMNT	<Tape drive already mounted>
REMOT	<Tape drive on remote node>
NOPRV	<No privilege for attempted operation>
INVCH	<Invalid channel>
EXQUO	<Quota exceeded>
EXCCH	<No channel available>
INVDV	<Illegal device name>
INVLG	<Illegal logical name>
CTLER	<Tape drive controller error>
DTCHK	<Tape write error>
DRVER	<Tape drive error>
EOF	<End of file on tape>
EOT	<End of tape>
EOV	<End of volume (2 tape marks)>
MDOFL	<Tape drive offline>
PARIT	<Parity error on tape>
UNSAF	<Tape drive unsafe>
VLINV	<Tape not mounted>
WTLCK	<Tape drive write locked>
DATOV	<Tape data block exceeds buffer size>
DVNMT	<Tape not mounted>
UNKSS	<Unknown System Service code>
BADSS	<VMS System Service Failed>
.END
