.TITLE       MIO
.FACILITY    MIO,340/PREFIX=MIO__


.SEVERITY	INFORMATIONAL

.BASE		100
TOOTD	<No more available tape descriptors>
ILLTD	<Illegal tape descriptor>
ILLAC	<Illegal access mode>
NTOPN	<Tape not open>
IVACM	<Invalid access mode>
BUFTB	<Invalid buffer size>
IVRSZ	<Invalid record size>
IVBSZ	<Invalid block size>
NTMUL	<Block size not a multiple of record size>
IVBUF	<Invalid buffer size>
ICBSZ	<Inconsistent block size>
NOREC	<Unknown record size>
ERROR	<Error>
NTSUP	<Option not supported>
DVALL	<Tape drive already allocated>
DVNAL	<Tape drive not allocated>
NSHDV	<No such tape drive>
DVASS	<Tape drive already assigned>
ACVIO	<Access violation>
BUFOV	<Buffer overflow>
DVMNT	<Tape drive already mounted>
REMOT	<Tape drive on remote node>
NOPRV	<No privilege for attempted operation>
INVCH	<Invalid channel>
EXQUO	<Quota exceeded>
EXCCH	<No channel available>
INVDV	<Illegal device name>
INVLG	<Illegal logical name>
CTLER	<Tape drive controller error>
DTCHK	<Tape write error>
DRVER	<Tape drive error>
EOF	<End of file on tape>
EOT	<End of tape>
EOV	<End of volume (2 tape marks)>
MDOFL	<Tape drive offline>
PARIT	<Parity error on tape>
UNSAF	<Tape drive unsafe>
VLINV	<Tape not mounted>
WTLCK	<Tape drive write locked>
DATOV	<Tape data block exceeds buffer size>
DVNMT	<Tape not mounted>
UNKSS	<Unknown System Service code>
BADSS	<VMS System Service Failed>
.END
