#!/bin/sh
#
#  To invoke the rv utility, type:
#
#     rv [input]  [report]
#
#  Either or both parameters may be defaulted, by omission
#  or by use of the notation "", to stdin and rv.lis respectively.
#
#  Common invocations:
#
#    rv                   interactive or batch
#
#    rv input             input from a file
#
#    rv input report      files for input & report
#
#  P.T.Wallace   Starlink   8 December 1993
#

#  String to indicate defaulted terminal I/O arguments
      _tty=.

#  Name of null device
      _null=/dev/null

#  Copy arguments
      _input="$1"
      _report="$2"

#  Prompts/help/errors to terminal
      _prompts="$_tty"

#  Echo to terminal if input file specified
      if [[ -n "$_input" ]]; then
         _echo="$_tty"
      else
         _echo="$_null"
      fi

#  Resolve defaults
      if [[ -z "$_input" ]]; then
         _input="$_tty"
      fi
      if [[ -z "$_report" ]]; then
         _report=rv.lis
      fi

#  Run the job
      rv.x "$_tty" "$_report" "$_input" "$_prompts" "$_echo"

#  Report the output filename if appropriate
      if [[ "$_report" != "$_tty" ]]; then
         echo "Report is in $_report"
      fi
