.TITLE       GRP
.FACILITY    GRP,1516/PREFIX=GRP__
.SEVERITY    ERROR

BADME       <Bad modification element given>
NULNM       <Blank name given>
DEEP        <Max. depth of indirection exceeded>
FREE        <Group to be made free is already free>
INVID       <Invalid Group Identifier given>
NOLUN       <No free Logical unit no.s available>
NOMOR       <GRP common arrays full>
OUTBN       <Array index out of bounds>
OWNED       <Group to be enslaved is already owned>
SLAVE       <Attempt to make a group a slave of its own slave>
SZINC       <Attempt made to increase the size of a group using GRP_SETSZ>
FIOER       <A Fortran I/O error has occurred>
INTER       <Internal GRP error>
BADCC       <Bad control character name given>
EMPTY       <The specified group is empty>
BADIT       <Bad item of information requested>
SHORT       <Supplied character variable is too short>
OWNER       <Group already owns another group>
INVEL       <Invalid element syntax given>
NOMEM       <Unable to allocate sufficient memory>
BDCHN       <Invalid chain specification>

.END
