.TITLE       ARY
.FACILITY    ARY,1503/PREFIX=ARY__


.SEVERITY	ERROR

.BASE		300
ACCIN	<access type specification invalid>
ACDEN	<access denied>
CFLAC	<conflicting array access>
DIMIN	<dimensions invalid>
EXSLT	<exceeded number of allocated slots>
FATIN	<fatal internal error>
FTPIN	<full data type specification invalid>
IDINV	<array identifier invalid>
ISMAP	<array currently mapped for access>
MMDIN	<mapping mode specification invalid>
NDMIN	<number of dimensions invalid>
NSDCN	<non-standard data component name>
NTMAP	<array not mapped for access>
PLINV	<array placeholder invalid>
ROGUE	<rogue component in array structure>
SFTIN	<pixel-shift specification invalid>
TRUNC	<character string truncated>
TYPIN	<data type invalid>
UNDEF	<array data values undefined>
USFRM	<unsupported array storage form>
VARIN	<variant value invalid>
XSDIM	<too many array dimensions>
FRMCV	<storage form conversion error>
NOTSP	<facility not yet supported>
.END
