.TITLE       ACT
.FACILITY    ACT,320/PREFIX=ACT__


.SEVERITY	INFORMATIONAL

.BASE		100
STAGE	<this message should never be reported!!>
WAIT	<this message should never be reported!!>
CANCEL	<this message should never be reported!!>
END	<this message should never be reported!!>
UNIMP	<this message should never be reported!!>
ASTINT	<this message should never be reported!!>
INFORM	<this message should never be reported!!>
EXIT	<this message should never be reported!!>
MESSAGE	<this message should never be reported!!>
.END
