.TITLE       AGI
.FACILITY    AGI,1501/PREFIX=AGI__


.SEVERITY	ERROR

.BASE		300
BADWO	<World coordinates are improper>
DIFDV	<Different devices>
DINER	<Database integrity error>
GKERR	<GKS error>
GRPNA	<Graphics package not active>
GRPON	<Graphics package in use>
IDERR	<IDI error>
IMPIC	<Picture number is improper>
IMPID	<Picture identifier is improper>
LABNF	<Label not found>
LOCIN	<Locator invalid>
MEMIN	<IDI memory invalid>
MEMTS	<IDI memory too small>
MORNF	<More structure not found>
NAMNR	<Device name not recognised>
NOCUP	<No current picture>
NONAM	<No picture of that name>
NOPIC	<No pictures in workstation>
NOPID	<No more available picture identifiers>
PICNF	<Picture not found>
PICOB	<Picture out of bounds>
REFEX	<Reference already exists>
REFNF	<Reference object not found>
TRANF	<Transformation not found>
TRINV	<Transformation invalid>
TRNEX	<Transformation already exists>
TRNIN	<Invalid number of transformation points>
WKNOP	<Problem opening workstation>
WKSNF	<Workstation not found>
ZONTS	<SGS zone too small>

BDNST	<Unbalanced nesting of AST_BEGIN/AST_END calls>
.END
