.TITLE       IDI
.FACILITY    IDI,275/PREFIX=IDI__


.SEVERITY	ERROR

.BASE		301
COOVF	<No more room in common block storage>
DEVNM	<Problem translating or obtaining device name>
ERROR	<Undefined error>
INCID	<Cursor number invalid>
INCON	<Configuration number invalid>
INDID	<Display identifier invalid>
INITT	<Intensity transformation table number invalid>
INLUT	<Look-up table number invalid>
INMID	<Memory identifier invalid>
INRID	<ROI identifier invalid>
IOERR	<Error writing to, or reading from device>
NOCAP	<No capability of that number>
NOEVA	<No such evaluator>
NOINT	<No such interactor>
NOOBJ	<No such object>
NOREC	<Error recovering characteristics>
NOROI	<No ROI available>
NOTIM	<Not implemented>
RANGE	<Parameter outside permissible range>
TWOVF	<Transfer window overflow>
WDTER	<Problem with workstation description file>
DISWNDERR	<Virtual Device Manager error>
NOAVAILDEV	<No virtual device available>
DEVNOTOP	<Device not opened>
NODYNCONF	<Device not dynamically configurable>
DEVNAMERR	<Device name error>
DEVCAPTRUNC	<Device capability truncated>
MAXCONFN	<Too many configurations>
EXTBMNOTFND	<External bitmap not found>
MEMALLERR	<Memory allocation error>
DCTFILERR	<Error in DCT file>
DYNCONFEN	<Dynamic configuration already enabled>
DYNCONFNOTEN	<Dynamic configuration not enabled>
ILLCONFID	<Illegal configuraton id>
MEMNOTFREE	<Memory not free>
ILLMEMID	<Illegal memory id>
MEMNOTALL	<Memory not allocated>
MAXMEM	<Out of memory locators>
TWTOOBIG	<Transfer window too big>
IMGTOOBIG	<Image too big>
LUTIDERR	<Lookup table identifier invalid>
LUTLENERR	<Lookup table length error>
LUTNOTDEF	<Lookup table not defined>
ITTIDERR	<ITT identifier invalid>
ITTLENERR	<ITT length invalid>
CURNOTDEF	<Cursor not defined>
ROINOTDEF	<ROI not defined>
MAXROI	<Too many ROIs>
ILLCURID	<Illegal cursor id>
ILLTRIGGER	<Illegal trigger id>
ILLINTTYPE	<Illegal interaction type>
ILLINTOBJ	<Illegal interaction object>
ILLINTOPER	<Illegal interaction operation>
IDINOSUPP	<IDI not supported>
DCTFILWARN	<Missing keyword in DCT file>
DEPTHERR	<Memory depth value>
MEMTYPERR	<Memory type error>
MAXMEMLST	<Internal memory exhausted>
LUTNOTFREE	<Current LUT not free>
CURNOTFREE	<Cursor not free>
CURNOTVIS	<Cursor not visible>
ROINOTVIS	<ROI not visible>
INTNOTALL	<Interaction invalid>
MAXNOINT	<Too many interactions>
INTNOEN	<Interaction not enabled>
FONTNOTDEF	<Text font not defined>
VD_MAXWIND	<Max number of interactions>
VD_KWTYPERR	<Display window type error>
VD_FILKWNOTCR	<Display window file not created>
VD_WINOTOPN	<Requested display window not created>
VD_FILKWERR	<Display window file read/update error>
VD_NULLDEV	<Environment device name not defined>
VD_SAVNOTALL	<SAVE operation not allowed for A>
VD_XCONNERR	<Error connecting to X-server>
VD_UNSUPVT	<Window visual type not supported>
.END
