.TITLE		IDI		Image Display Interface
.FACILITY	IDI,275/PREFIX=IDI__
.IDENT		'Version 1.0'
!author		DUVAD::NE ( Nick Eaton )

.SEVERITY	INFORMATIONAL
.BASE 100


.SEVERITY	WARNING
.BASE 200


.SEVERITY	ERROR
.BASE 300

OK              <Normal status>
COOVF           <No more room in common block storage>
DEVNM           <Problem translating or obtaining device name>
ERROR           <Undefined error>
INCID           <Cursor number invalid>
INCON           <Configuration number invalid>
INDID           <Display identifier invalid>
INITT           <Intensity transformation table number invalid>
INLUT           <Look-up table number invalid>
INMID           <Memory identifier invalid>
INRID           <ROI identifier invalid>
IOERR           <Error writing to, or reading from device>
NOCAP           <No capability of that number>
NOEVA           <No such evaluator>
NOINT           <No such interactor>
NOOBJ           <No such object>
NOREC           <Error recovering characteristics>
NOROI           <No ROI available>
NOTIM           <Not implemented>
RANGE           <Parameter outside permissible range>
TWOVF           <Transfer window overflow>
WDTER           <Problem with workstation description file>

.END
