#!/bin/sh
# E.S.O. - VLT project/ ESO Archive 
# "@(#) $Id: makelinks,v 1.1.1.1 2002/04/04 20:11:53 brighton Exp $"
#
# script to make some links used during development
#
# usage: makelinks
#
# who             when       what
# --------------  --------   ----------------------------------------
# Allan Brighton  14 Nov 96  Created


if [ ! -d ./interp/library ]
then
	echo "$0: you should be one level above the interp directory"
	exit 1
fi

echo "making links in skycat/interp/library..."
cd interp/library
make index
for i in demos 
do
  rm -f $i
  ln -s ../$i .
done

