# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Starlink-AST
version:      0.03
version_from: AST.pm
installdirs:  site
licence:      gpl
recommends:
  Tk: 0
  Graphics::PLplot: 0
requires:
  Data::Dumper: 0
  DynaLoader: 0
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Tim Jenness
dynamic_config: 1
