.TITLE       PSX
.FACILITY    PSX,1510/PREFIX=PSX__


.SEVERITY	ERROR
NOENV	<No translation of an environment variable>
NOALL	<Null pointer returned on memory allocation>
INTYP	<Invalid argument TYPE given in call to PSX_CALLOC>
NOTIM	<Could not get current time with time()>
NOGMT	<Could not get GMT with gmtime()>
NOMEM	<Could not get required memory>
ERRNO   <System error during POSIX call>
TRUNC   <Truncated string>
BADIT	<Unknown item of file information requested>
BDWXP   <Error from word expansion>
.END
