#!/bin/sh -

updatelist="version.h README dvi2bitmap.1 Makefile.starlink"

# Little script to propagate the version stored in the file VERSION.  The
# version strings to be replaced must either be on a line which
# includes the string %%VERSION%% (probably in a comment) or comes
# immediately after such a line.  It must also be the first string
# which matches the regexp.

for f in $updatelist ; do
    if test VERSION -nt $f; then
	echo "Updating $f..."
	sed '/%%VERSION%%/{N;s/[0-9][0-9.-]\+[a-z]*/'`cat VERSION`'/;}' \
		$f >$f.tmp && mv $f.tmp $f && echo "...ok"
    fi
done

