.TITLE		AST
.FACILITY	AST,1515/PREFIX=AST__
.IDENT		'Version 1.0'
!author		15 Jun 98 (Richard Beard, University of Birmingham)

.SEVERITY	ERROR

CONER		<Data conversion error>
TRUNC		<Text truncated>
INVARG		<Invalid argument>
SYMDEF		<Symbol already defined>
FATAL		<Fatal internal ADI error>
IDINV		<Invalid ADI identifier>
ILLKOP		<Illegal operation on kernel object>
NOTSET		<Object data is not set>
EXISTS		<Object already exists>
NOMTH		<No applicable methods>
MTHERR		<Error in method>
NOMEMB		<No such class member>
ISPRIM		<Object is primitive>
ILLOP		<Illegal operation>
OUTMEM		<Unable to allocate dynamic memory>
NOTACT		<ADI is not active>
NOPROP		<No such property>
NOCOMP		<No such structure component>
EXCEED		<Storage space in buffer exceeded>
NOTDEL		<Object not deleted>
NONAME		<Object is not a named object>
PRGERR		<Programming error>
MAPPED		<Object is already mapped>
NOTMAP		<Object is not mapped at this address>
RDONLY		<Object is readonly>
SYNTAX		<Syntax error>
ITREND		<No more items>
NOFUN		<No applicable functions>
INTGTY		<Integrity check failure>
RETRY		<Retry operation>
	
.BASE		50
CALNXTMTH	<>
UNWIND		<>

.END
