.TITLE       SUBPAR
.FACILITY    SUBPAR,170/PREFIX=SUBPAR__


.SEVERITY	INFORMATIONAL

.BASE		100
BIGVEC	<too many values on one line>
IFCOPN	<failed to open compiled interface file>
IVPROMPT	<invalid attempt to prompt, probably not an A-task>
NOPAR	<attempt to access nonexistent parameter>
OUTRANGE	<parameter value violates declared constraints>
SYNTAX	<response to prompt looks like a list of structures>
BADIFC	<error reading compiled interface file>
DYNFULL	<store for dynamic defaults is full>
IVPRTYPE	<invalid primitive type>
ILARCOMP	<illegal array component>
ARRDIM	<array dimension error>
CMDSYER	<syntax error in command line>
INVST	<invalid parameter state specified>
IFNF	<failed to find interface module>
XMXPOS	<too many command line parameter positions allocated>
PNOTAL	<command line parameter position used is not allocated>
CONER	<data conversion error>
MNMXFL	<MIN/MAX storage space full>
MNMXTY	<invalid parameter type for MIN/MAX value>
MNMXEX	<MIN/MAX value outside RANGE>
MNMXAC	<attempted to set MIN/MAX value when parameter active>
NOMNMX	<MIN/MAX value not specified for this parameter>
NAMIN	<invalid HDS object name>
ICACM	<inconsistent parameter access mode>
NOACT	<requested action name is not defined>
OPTER	<error during message delivery>
HLPER	<error on multi-line parameter help>
ERROR	<SUBPAR general bad status>
.END
