#!/bin/sh -xv

unset LANG

export STARCONF_DEFAULT_PREFIX=/home/pdraper/starlink_svn/star

g++ -g3 -o readtable_template \
    -I. \
    -I$STARCONF_DEFAULT_PREFIX/include/tclutil \
    -I$STARCONF_DEFAULT_PREFIX/include/astrotcl \
    readtable_template.C VOTable.C VOTable1.1.cxx VOTable1.1_dns.cxx \
    VOTableStream.C gaiabase64.c gaiagzip.c GaiaUtils.C \
    -L$STARCONF_DEFAULT_PREFIX/lib \
    -lastrotcl2.0 -ltclutil2.0 -lxerces-c
exit
