#!/usr/bin/env python

#  Does the same as "grep -Po". Mainly for use on MacOS where "grep-Po" isn't
#  available. Will read from one or more text files, or from standard input
#  if no text files are specified on the command line.

import fileinput
import sys
import re

if len(sys.argv) < 1:
   sys.exit("Usage: pygrep regex <file>")

pattern = re.compile("{0}".format(sys.argv[1].encode().decode('unicode_escape')))

for line in fileinput.input(files=sys.argv[2:]):
   mt = re.search( pattern, line )
   if mt:
      print( mt.group(0) )
