.TITLE       ARD  ASCII Region Definition library
.FACILITY    ARD,1520/PREFIX=ARD__
.SEVERITY    ERROR

ARGS	<Invalid argument list>
BADAR	<Invalid argument value>
BADDM	<Invalid dimensionality>
BADFL	<Unrecognised field label>
BADIN	<Illegal value supplied for INDEX>
INDET	<Indeterminate mapping or arguments>
INTER	<Internal programming error>
MISOP	<Missing operand >
MSPAR	<Missing parenthesis>
NOT2D	<ARD description is not 2-D>
SCALE	<Current mapping is not isotropic>

.END
