      CHARACTER*(*) FUNCTION MDH_ITOC( INUM )
      CHARACTER*15 DUMMY
      INTEGER INUM
      INTEGER FIND_NOT_BLANK
      WRITE( DUMMY , '( I )' ) INUM
      MDH_ITOC = DUMMY( FIND_NOT_BLANK ( DUMMY ): )
      END
