.TITLE       TRN
.FACILITY    TRN,1502/PREFIX=TRN__


.SEVERITY	INFORMATIONAL

.BASE		100
BADCN	<"bad" constant explicitly specified>

.SEVERITY	WARNING

.BASE		200
OPNOS	<operation not supported>

.SEVERITY	ERROR

.BASE		300
CLSIN	<classification information invalid>
CMPER	<compilation error>
CMTOF	<compiled mapping table overflow>
CONIN	<constant syntax invalid>
DELIN	<delimiting comma invalid>
DIMIN	<dimensions invalid>
DSTIN	<definition status invalid>
DUVAR	<duplicate variable name>
EXPUD	<expression undefined>
ICDIR	<incompatible transformation directions>
MAPUD	<mapping undefined>
MIDIN	<compiled mapping identifier invalid>
MIOPA	<missing or invalid operand>
MIOPR	<missing or invalid operator>
MISVN	<missing variable name>
MLPAR	<missing left parenthesis>
MRPAR	<missing right parenthesis>
NDCMM	<number of data coordinates mis-matched>
NMVMM	<number of module variables mis-matched>
NTVMM	<number of transformation variables mis-matched>
NVRIN	<number of variables invalid>
OPCIN	<operation code invalid>
PRCIN	<precision invalid>
TOKIN	<token name invalid>
TRNUD	<transformation undefined>
TRUNC	<character string truncated>
TYPIN	<type invalid>
VARIN	<variable name invalid>
VARUD	<variable name undefined>
VERMM	<software version mis-match>
WRNFA	<wrong number of function arguments>
.END
